/*
 * generated by Xtext 2.42.0
 */
package tools.refinery.language.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractProblemScopeProvider extends DelegatingScopeProvider {
}
