// This file is part of the SV-Benchmarks collection of verification tasks:
// https://gitlab.com/sosy-lab/benchmarking/sv-benchmarks
//
// SPDX-FileCopyrightText: 2020 Aman Goel
// SPDX-FileCopyrightText: 2022 The SV-Benchmarks Community
//
// SPDX-License-Identifier: GPL-3.0-or-later

// This C program is converted from Btor2 by Btor2C version sha1:a0fa249
//   with arguments: { architecture=64, lazy_modulo=true, use_memmove=false, unroll_inner_loops=false, shortest_type=true, diff_type=true, decimal_constant=true, zero_init=false, sra_extend_sign=true }
// Comments from the original Btor2 file:
// ; source: https://github.com/aman-goel/avr/tree/92362931700b66684418a991d018c9fbdbebc06f/tests
// ; BTOR description generated by Yosys 0.9+431 (git sha1 4a3b5437, clang 4.0.1-6 -fPIC -Os) for module main.
extern unsigned char __VERIFIER_nondet_uchar();
extern unsigned short __VERIFIER_nondet_ushort();
extern unsigned int __VERIFIER_nondet_uint();
extern unsigned long __VERIFIER_nondet_ulong();
extern void abort(void);
extern void __assert_fail(const char *, const char *, unsigned int, const char *);
void reach_error() { __assert_fail("0", "vis_QF_BV_s1269b_p3.c", 0, "reach_error"); }
void __VERIFIER_assert(int cond) { if (!(cond)) { ERROR: { reach_error(); abort(); } } }
void assume_abort_if_not(int cond) { if (!cond) { abort(); } }
int main() {
  // Defining sorts ...
  typedef unsigned char SORT_1;  // BV with 3 bits
  const SORT_1 mask_SORT_1 = (SORT_1)-1 >> (sizeof(SORT_1) * 8 - 3);
  const SORT_1 msb_SORT_1 = (SORT_1)1 << (3 - 1);
  typedef unsigned char SORT_3;  // BV with 1 bits
  const SORT_3 mask_SORT_3 = (SORT_3)-1 >> (sizeof(SORT_3) * 8 - 1);
  const SORT_3 msb_SORT_3 = (SORT_3)1 << (1 - 1);
  typedef unsigned char SORT_12;  // BV with 8 bits
  const SORT_12 mask_SORT_12 = (SORT_12)-1 >> (sizeof(SORT_12) * 8 - 8);
  const SORT_12 msb_SORT_12 = (SORT_12)1 << (8 - 1);
  // Initializing constants ...
  const SORT_3 var_14 = 0;
  const SORT_3 var_29 = 1;
  // Collecting input declarations ...
  SORT_1 input_2;
  SORT_3 input_4;
  SORT_3 input_5;
  SORT_3 input_6;
  SORT_3 input_7;
  SORT_3 input_8;
  SORT_3 input_9;
  SORT_3 input_10;
  SORT_3 input_11;
  SORT_12 input_13;
  SORT_12 input_33;
  SORT_12 input_35;
  SORT_3 input_37;
  SORT_3 input_39;
  SORT_12 input_83;
  SORT_3 input_89;
  SORT_1 input_92;
  SORT_3 input_94;
  SORT_3 input_96;
  SORT_3 input_98;
  // Collecting state declarations ...
  SORT_3 state_15 = __VERIFIER_nondet_uchar() & mask_SORT_3;
  SORT_3 state_17 = __VERIFIER_nondet_uchar() & mask_SORT_3;
  SORT_3 state_20 = __VERIFIER_nondet_uchar() & mask_SORT_3;
  SORT_3 state_24 = __VERIFIER_nondet_uchar() & mask_SORT_3;
  // Initializing states ...
  SORT_3 init_16_arg_1 = var_14;
  state_15 = init_16_arg_1;
  SORT_3 init_18_arg_1 = var_14;
  state_17 = init_18_arg_1;
  SORT_3 init_21_arg_1 = var_14;
  state_20 = init_21_arg_1;
  SORT_3 init_25_arg_1 = var_14;
  state_24 = init_25_arg_1;
  for (;;) {
    // Getting external input values ...
    input_2 = __VERIFIER_nondet_uchar();
    input_4 = __VERIFIER_nondet_uchar();
    input_5 = __VERIFIER_nondet_uchar();
    input_6 = __VERIFIER_nondet_uchar();
    input_7 = __VERIFIER_nondet_uchar();
    input_8 = __VERIFIER_nondet_uchar();
    input_9 = __VERIFIER_nondet_uchar();
    input_10 = __VERIFIER_nondet_uchar();
    input_11 = __VERIFIER_nondet_uchar();
    input_13 = __VERIFIER_nondet_uchar();
    input_33 = __VERIFIER_nondet_uchar();
    input_35 = __VERIFIER_nondet_uchar();
    input_37 = __VERIFIER_nondet_uchar();
    input_39 = __VERIFIER_nondet_uchar();
    input_83 = __VERIFIER_nondet_uchar();
    input_89 = __VERIFIER_nondet_uchar();
    input_92 = __VERIFIER_nondet_uchar();
    input_94 = __VERIFIER_nondet_uchar();
    input_96 = __VERIFIER_nondet_uchar();
    input_98 = __VERIFIER_nondet_uchar();
    // Assuming invariants ...
    // Asserting properties ...
    SORT_3 var_19_arg_0 = state_15;
    SORT_3 var_19_arg_1 = state_17;
    SORT_3 var_19 = var_19_arg_0 | var_19_arg_1;
    SORT_3 var_22_arg_0 = var_19;
    SORT_3 var_22_arg_1 = state_20;
    SORT_3 var_22 = var_22_arg_0 | var_22_arg_1;
    SORT_3 var_23_arg_0 = var_22;
    SORT_3 var_23 = ~var_23_arg_0;
    SORT_3 var_26_arg_0 = var_23;
    SORT_3 var_26_arg_1 = state_24;
    SORT_3 var_26 = var_26_arg_0 | var_26_arg_1;
    SORT_3 var_30_arg_0 = var_26;
    SORT_3 var_30 = ~var_30_arg_0;
    SORT_3 var_31_arg_0 = var_29;
    SORT_3 var_31_arg_1 = var_30;
    SORT_3 var_31 = var_31_arg_0 & var_31_arg_1;
    var_31 = var_31 & mask_SORT_3;
    SORT_3 bad_32_arg_0 = var_31;
    __VERIFIER_assert(!(bad_32_arg_0));
    // Computing next states ...
    SORT_3 var_41_arg_0 = state_17;
    SORT_3 var_41 = ~var_41_arg_0;
    SORT_3 var_42_arg_0 = state_15;
    SORT_3 var_42 = ~var_42_arg_0;
    SORT_3 var_43_arg_0 = var_42;
    SORT_3 var_43_arg_1 = state_20;
    SORT_3 var_43 = var_43_arg_0 & var_43_arg_1;
    SORT_3 var_44_arg_0 = var_43;
    SORT_3 var_44 = ~var_44_arg_0;
    SORT_3 var_45_arg_0 = var_41;
    SORT_3 var_45_arg_1 = var_44;
    SORT_3 var_45 = var_45_arg_0 | var_45_arg_1;
    SORT_3 var_46_arg_0 = var_45;
    SORT_3 var_46 = ~var_46_arg_0;
    SORT_3 var_47_arg_0 = state_17;
    SORT_3 var_47_arg_1 = state_20;
    SORT_3 var_47 = var_47_arg_0 & var_47_arg_1;
    SORT_3 var_48_arg_0 = var_42;
    SORT_3 var_48_arg_1 = var_47;
    SORT_3 var_48 = var_48_arg_0 | var_48_arg_1;
    SORT_3 var_49_arg_0 = var_48;
    SORT_3 var_49 = ~var_49_arg_0;
    SORT_3 var_50_arg_0 = var_46;
    SORT_3 var_50_arg_1 = var_49;
    SORT_3 var_50 = var_50_arg_0 | var_50_arg_1;
    SORT_3 next_100_arg_1 = var_50;
    SORT_3 var_52_arg_0 = state_20;
    SORT_3 var_52 = ~var_52_arg_0;
    SORT_3 var_53_arg_0 = state_17;
    SORT_3 var_53_arg_1 = var_52;
    SORT_3 var_53 = var_53_arg_0 | var_53_arg_1;
    SORT_3 var_54_arg_0 = state_17;
    SORT_3 var_54_arg_1 = var_52;
    SORT_3 var_54 = var_54_arg_0 & var_54_arg_1;
    SORT_3 var_55_arg_0 = var_54;
    SORT_3 var_55 = ~var_55_arg_0;
    SORT_3 var_56_arg_0 = var_53;
    SORT_3 var_56_arg_1 = var_55;
    SORT_3 var_56 = var_56_arg_0 & var_56_arg_1;
    SORT_3 var_57_arg_0 = var_56;
    SORT_3 var_57 = ~var_57_arg_0;
    SORT_3 next_101_arg_1 = var_57;
    SORT_1 var_59_arg_0 = input_2;
    SORT_3 var_59 = var_59_arg_0 >> 0;
    SORT_1 var_60_arg_0 = input_2;
    SORT_3 var_60 = var_60_arg_0 >> 2;
    SORT_3 var_61_arg_0 = var_60;
    SORT_3 var_61 = ~var_61_arg_0;
    SORT_1 var_62_arg_0 = input_2;
    SORT_3 var_62 = var_62_arg_0 >> 1;
    SORT_3 var_63_arg_0 = var_61;
    SORT_3 var_63_arg_1 = var_62;
    SORT_3 var_63 = var_63_arg_0 | var_63_arg_1;
    SORT_3 var_64_arg_0 = var_59;
    SORT_3 var_64_arg_1 = var_63;
    SORT_3 var_64 = var_64_arg_0 | var_64_arg_1;
    SORT_3 var_65_arg_0 = var_64;
    SORT_3 var_65 = ~var_65_arg_0;
    SORT_3 var_66_arg_0 = state_15;
    SORT_3 var_66_arg_1 = state_17;
    SORT_3 var_66 = var_66_arg_0 | var_66_arg_1;
    SORT_3 var_67_arg_0 = var_65;
    SORT_3 var_67_arg_1 = var_66;
    SORT_3 var_67 = var_67_arg_0 | var_67_arg_1;
    SORT_3 var_68_arg_0 = var_67;
    SORT_3 var_68_arg_1 = var_52;
    SORT_3 var_68 = var_68_arg_0 & var_68_arg_1;
    SORT_3 next_102_arg_1 = var_68;
    SORT_3 var_85_arg_0 = var_65;
    SORT_3 var_85_arg_1 = state_17;
    SORT_3 var_85 = var_85_arg_0 | var_85_arg_1;
    SORT_3 var_86_arg_0 = var_85;
    SORT_3 var_86_arg_1 = state_15;
    SORT_3 var_86 = var_86_arg_0 | var_86_arg_1;
    SORT_3 var_87_arg_0 = var_86;
    SORT_3 var_87_arg_1 = state_20;
    SORT_3 var_87 = var_87_arg_0 | var_87_arg_1;
    SORT_3 next_103_arg_1 = var_87;
    // Assigning next states ...
    state_15 = next_100_arg_1;
    state_17 = next_101_arg_1;
    state_20 = next_102_arg_1;
    state_24 = next_103_arg_1;
  }
  return 0;
}
