// This file is part of the SV-Benchmarks collection of verification tasks:
// https://gitlab.com/sosy-lab/benchmarking/sv-benchmarks
//
// SPDX-FileCopyrightText: 2020 Aman Goel
// SPDX-FileCopyrightText: 2022 The SV-Benchmarks Community
//
// SPDX-License-Identifier: GPL-3.0-or-later

// This C program is converted from Btor2 by Btor2C version sha1:a0fa249
//   with arguments: { architecture=64, lazy_modulo=true, use_memmove=false, unroll_inner_loops=false, shortest_type=true, diff_type=true, decimal_constant=true, zero_init=false, sra_extend_sign=true }
// Comments from the original Btor2 file:
// ; source: https://github.com/aman-goel/avr/tree/92362931700b66684418a991d018c9fbdbebc06f/tests
// ; BTOR description generated by Yosys 0.9+431 (git sha1 4a3b5437, clang 4.0.1-6 -fPIC -Os) for module main.
extern unsigned char __VERIFIER_nondet_uchar();
extern unsigned short __VERIFIER_nondet_ushort();
extern unsigned int __VERIFIER_nondet_uint();
extern unsigned long __VERIFIER_nondet_ulong();
extern void abort(void);
extern void __assert_fail(const char *, const char *, unsigned int, const char *);
void reach_error() { __assert_fail("0", "h_b04.c", 0, "reach_error"); }
void __VERIFIER_assert(int cond) { if (!(cond)) { ERROR: { reach_error(); abort(); } } }
void assume_abort_if_not(int cond) { if (!cond) { abort(); } }
int main() {
  // Defining sorts ...
  typedef unsigned char SORT_1;  // BV with 1 bits
  const SORT_1 mask_SORT_1 = (SORT_1)-1 >> (sizeof(SORT_1) * 8 - 1);
  const SORT_1 msb_SORT_1 = (SORT_1)1 << (1 - 1);
  typedef unsigned char SORT_4;  // BV with 8 bits
  const SORT_4 mask_SORT_4 = (SORT_4)-1 >> (sizeof(SORT_4) * 8 - 8);
  const SORT_4 msb_SORT_4 = (SORT_4)1 << (8 - 1);
  typedef unsigned int SORT_12;  // BV with 32 bits
  const SORT_12 mask_SORT_12 = (SORT_12)-1 >> (sizeof(SORT_12) * 8 - 32);
  const SORT_12 msb_SORT_12 = (SORT_12)1 << (32 - 1);
  // Initializing constants ...
  const SORT_4 var_8 = 0;
  const SORT_12 var_14 = 1;
  const SORT_1 var_25 = 1;
  const SORT_1 var_42 = 0;
  // Collecting input declarations ...
  SORT_1 input_2;
  SORT_1 input_3;
  SORT_4 input_5;
  SORT_1 input_6;
  SORT_1 input_7;
  SORT_4 input_29;
  SORT_4 input_31;
  SORT_4 input_33;
  SORT_4 input_35;
  SORT_4 input_37;
  SORT_4 input_39;
  // Collecting state declarations ...
  SORT_4 state_9 = __VERIFIER_nondet_uchar() & mask_SORT_4;
  SORT_4 state_17 = __VERIFIER_nondet_uchar() & mask_SORT_4;
  SORT_1 state_43 = __VERIFIER_nondet_uchar() & mask_SORT_1;
  // Initializing states ...
  SORT_4 init_10_arg_1 = var_8;
  state_9 = init_10_arg_1;
  SORT_4 init_18_arg_1 = var_8;
  state_17 = init_18_arg_1;
  SORT_1 init_44_arg_1 = var_42;
  state_43 = init_44_arg_1;
  for (;;) {
    // Getting external input values ...
    input_2 = __VERIFIER_nondet_uchar();
    input_3 = __VERIFIER_nondet_uchar();
    input_5 = __VERIFIER_nondet_uchar();
    input_6 = __VERIFIER_nondet_uchar();
    input_7 = __VERIFIER_nondet_uchar();
    input_29 = __VERIFIER_nondet_uchar();
    input_31 = __VERIFIER_nondet_uchar();
    input_33 = __VERIFIER_nondet_uchar();
    input_35 = __VERIFIER_nondet_uchar();
    input_37 = __VERIFIER_nondet_uchar();
    input_39 = __VERIFIER_nondet_uchar();
    // Assuming invariants ...
    // Asserting properties ...
    SORT_4 var_11_arg_0 = state_9;
    SORT_1 var_11 = var_11_arg_0 >> 7;
    SORT_1 var_13_arg_0 = var_11;
    var_13_arg_0 = var_13_arg_0 & mask_SORT_1;
    SORT_12 var_13 = var_13_arg_0;
    SORT_12 var_15_arg_0 = var_13;
    SORT_12 var_15_arg_1 = var_14;
    SORT_1 var_15 = var_15_arg_0 == var_15_arg_1;
    SORT_1 var_16_arg_0 = var_15;
    SORT_1 var_16 = ~var_16_arg_0;
    SORT_4 var_19_arg_0 = state_17;
    SORT_1 var_19 = var_19_arg_0 >> 7;
    SORT_1 var_20_arg_0 = var_19;
    var_20_arg_0 = var_20_arg_0 & mask_SORT_1;
    SORT_12 var_20 = var_20_arg_0;
    SORT_12 var_21_arg_0 = var_20;
    SORT_12 var_21_arg_1 = var_14;
    SORT_1 var_21 = var_21_arg_0 == var_21_arg_1;
    SORT_1 var_22_arg_0 = var_16;
    SORT_1 var_22_arg_1 = var_21;
    SORT_1 var_22 = var_22_arg_0 | var_22_arg_1;
    SORT_1 var_26_arg_0 = var_22;
    SORT_1 var_26 = ~var_26_arg_0;
    SORT_1 var_27_arg_0 = var_25;
    SORT_1 var_27_arg_1 = var_26;
    SORT_1 var_27 = var_27_arg_0 & var_27_arg_1;
    var_27 = var_27 & mask_SORT_1;
    SORT_1 bad_28_arg_0 = var_27;
    __VERIFIER_assert(!(bad_28_arg_0));
    // Computing next states ...
    SORT_1 var_45_arg_0 = state_43;
    SORT_4 var_45_arg_1 = input_5;
    SORT_4 var_45_arg_2 = state_9;
    SORT_4 var_45 = var_45_arg_0 ? var_45_arg_1 : var_45_arg_2;
    SORT_4 next_46_arg_1 = var_45;
    SORT_1 var_47_arg_0 = state_43;
    SORT_4 var_47_arg_1 = input_5;
    SORT_4 var_47_arg_2 = state_17;
    SORT_4 var_47 = var_47_arg_0 ? var_47_arg_1 : var_47_arg_2;
    SORT_4 next_48_arg_1 = var_47;
    SORT_1 var_49_arg_0 = state_43;
    SORT_1 var_49_arg_1 = var_42;
    SORT_1 var_49_arg_2 = var_25;
    SORT_1 var_49 = var_49_arg_0 ? var_49_arg_1 : var_49_arg_2;
    var_49 = var_49 & mask_SORT_1;
    SORT_1 next_50_arg_1 = var_49;
    // Assigning next states ...
    state_9 = next_46_arg_1;
    state_17 = next_48_arg_1;
    state_43 = next_50_arg_1;
  }
  return 0;
}
