// This file is part of the SV-Benchmarks collection of verification tasks:
// https://gitlab.com/sosy-lab/benchmarking/sv-benchmarks
//
// SPDX-FileCopyrightText: 2020 Aman Goel
// SPDX-FileCopyrightText: 2022 The SV-Benchmarks Community
//
// SPDX-License-Identifier: GPL-3.0-or-later

// This C program is converted from Btor2 by Btor2C version sha1:a0fa249
//   with arguments: { architecture=64, lazy_modulo=true, use_memmove=false, unroll_inner_loops=false, shortest_type=true, diff_type=true, decimal_constant=true, zero_init=false, sra_extend_sign=true }
// Comments from the original Btor2 file:
// ; source: https://github.com/aman-goel/avr/tree/92362931700b66684418a991d018c9fbdbebc06f/tests
// ; BTOR description generated by Yosys 0.9+431 (git sha1 4a3b5437, clang 4.0.1-6 -fPIC -Os) for module main.
extern unsigned char __VERIFIER_nondet_uchar();
extern unsigned short __VERIFIER_nondet_ushort();
extern unsigned int __VERIFIER_nondet_uint();
extern unsigned long __VERIFIER_nondet_ulong();
extern void abort(void);
extern void __assert_fail(const char *, const char *, unsigned int, const char *);
void reach_error() { __assert_fail("0", "vis_QF_BV_spinner32.c", 0, "reach_error"); }
void __VERIFIER_assert(int cond) { if (!(cond)) { ERROR: { reach_error(); abort(); } } }
void assume_abort_if_not(int cond) { if (!cond) { abort(); } }
int main() {
  // Defining sorts ...
  typedef unsigned char SORT_1;  // BV with 5 bits
  const SORT_1 mask_SORT_1 = (SORT_1)-1 >> (sizeof(SORT_1) * 8 - 5);
  const SORT_1 msb_SORT_1 = (SORT_1)1 << (5 - 1);
  typedef unsigned char SORT_3;  // BV with 1 bits
  const SORT_3 mask_SORT_3 = (SORT_3)-1 >> (sizeof(SORT_3) * 8 - 1);
  const SORT_3 msb_SORT_3 = (SORT_3)1 << (1 - 1);
  typedef unsigned int SORT_5;  // BV with 32 bits
  const SORT_5 mask_SORT_5 = (SORT_5)-1 >> (sizeof(SORT_5) * 8 - 32);
  const SORT_5 msb_SORT_5 = (SORT_5)1 << (32 - 1);
  typedef unsigned int SORT_25;  // BV with 31 bits
  const SORT_25 mask_SORT_25 = (SORT_25)-1 >> (sizeof(SORT_25) * 8 - 31);
  const SORT_25 msb_SORT_25 = (SORT_25)1 << (31 - 1);
  typedef unsigned int SORT_35;  // BV with 30 bits
  const SORT_35 mask_SORT_35 = (SORT_35)-1 >> (sizeof(SORT_35) * 8 - 30);
  const SORT_35 msb_SORT_35 = (SORT_35)1 << (30 - 1);
  typedef unsigned int SORT_37;  // BV with 29 bits
  const SORT_37 mask_SORT_37 = (SORT_37)-1 >> (sizeof(SORT_37) * 8 - 29);
  const SORT_37 msb_SORT_37 = (SORT_37)1 << (29 - 1);
  typedef unsigned char SORT_43;  // BV with 2 bits
  const SORT_43 mask_SORT_43 = (SORT_43)-1 >> (sizeof(SORT_43) * 8 - 2);
  const SORT_43 msb_SORT_43 = (SORT_43)1 << (2 - 1);
  typedef unsigned int SORT_49;  // BV with 28 bits
  const SORT_49 mask_SORT_49 = (SORT_49)-1 >> (sizeof(SORT_49) * 8 - 28);
  const SORT_49 msb_SORT_49 = (SORT_49)1 << (28 - 1);
  typedef unsigned int SORT_51;  // BV with 26 bits
  const SORT_51 mask_SORT_51 = (SORT_51)-1 >> (sizeof(SORT_51) * 8 - 26);
  const SORT_51 msb_SORT_51 = (SORT_51)1 << (26 - 1);
  typedef unsigned char SORT_57;  // BV with 4 bits
  const SORT_57 mask_SORT_57 = (SORT_57)-1 >> (sizeof(SORT_57) * 8 - 4);
  const SORT_57 msb_SORT_57 = (SORT_57)1 << (4 - 1);
  typedef unsigned int SORT_63;  // BV with 24 bits
  const SORT_63 mask_SORT_63 = (SORT_63)-1 >> (sizeof(SORT_63) * 8 - 24);
  const SORT_63 msb_SORT_63 = (SORT_63)1 << (24 - 1);
  typedef unsigned int SORT_65;  // BV with 20 bits
  const SORT_65 mask_SORT_65 = (SORT_65)-1 >> (sizeof(SORT_65) * 8 - 20);
  const SORT_65 msb_SORT_65 = (SORT_65)1 << (20 - 1);
  typedef unsigned char SORT_71;  // BV with 8 bits
  const SORT_71 mask_SORT_71 = (SORT_71)-1 >> (sizeof(SORT_71) * 8 - 8);
  const SORT_71 msb_SORT_71 = (SORT_71)1 << (8 - 1);
  typedef unsigned short SORT_77;  // BV with 16 bits
  const SORT_77 mask_SORT_77 = (SORT_77)-1 >> (sizeof(SORT_77) * 8 - 16);
  const SORT_77 msb_SORT_77 = (SORT_77)1 << (16 - 1);
  // Initializing constants ...
  const SORT_5 var_8 = 0;
  const SORT_5 var_11 = 2863311530;
  const SORT_3 var_15 = 1;
  const SORT_3 var_22 = 0;
  // Collecting input declarations ...
  SORT_1 input_2;
  SORT_3 input_4;
  SORT_5 input_6;
  SORT_3 input_7;
  // Collecting state declarations ...
  SORT_5 state_9 = __VERIFIER_nondet_uint() & mask_SORT_5;
  SORT_5 state_19 = __VERIFIER_nondet_uint() & mask_SORT_5;
  SORT_3 state_23 = __VERIFIER_nondet_uchar() & mask_SORT_3;
  // Initializing states ...
  SORT_5 init_10_arg_1 = var_8;
  state_9 = init_10_arg_1;
  SORT_5 init_20_arg_1 = var_8;
  state_19 = init_20_arg_1;
  SORT_3 init_24_arg_1 = var_22;
  state_23 = init_24_arg_1;
  for (;;) {
    // Getting external input values ...
    input_2 = __VERIFIER_nondet_uchar();
    input_4 = __VERIFIER_nondet_uchar();
    input_6 = __VERIFIER_nondet_uint();
    input_7 = __VERIFIER_nondet_uchar();
    input_7 = input_7 & mask_SORT_3;
    // Assuming invariants ...
    // Asserting properties ...
    SORT_5 var_12_arg_0 = state_9;
    SORT_5 var_12_arg_1 = var_11;
    SORT_3 var_12 = var_12_arg_0 != var_12_arg_1;
    SORT_3 var_16_arg_0 = var_12;
    SORT_3 var_16 = ~var_16_arg_0;
    SORT_3 var_17_arg_0 = var_15;
    SORT_3 var_17_arg_1 = var_16;
    SORT_3 var_17 = var_17_arg_0 & var_17_arg_1;
    var_17 = var_17 & mask_SORT_3;
    SORT_3 bad_18_arg_0 = var_17;
    __VERIFIER_assert(!(bad_18_arg_0));
    // Computing next states ...
    SORT_1 var_81_arg_0 = input_2;
    SORT_3 var_81 = var_81_arg_0 >> 4;
    var_81 = var_81 & mask_SORT_3;
    SORT_1 var_68_arg_0 = input_2;
    SORT_3 var_68 = var_68_arg_0 >> 3;
    var_68 = var_68 & mask_SORT_3;
    SORT_1 var_54_arg_0 = input_2;
    SORT_3 var_54 = var_54_arg_0 >> 2;
    var_54 = var_54 & mask_SORT_3;
    SORT_1 var_40_arg_0 = input_2;
    SORT_3 var_40 = var_40_arg_0 >> 1;
    var_40 = var_40 & mask_SORT_3;
    SORT_1 var_28_arg_0 = input_2;
    SORT_3 var_28 = var_28_arg_0 >> 0;
    var_28 = var_28 & mask_SORT_3;
    SORT_5 var_32_arg_0 = state_19;
    SORT_3 var_32 = var_32_arg_0 >> 0;
    SORT_5 var_31_arg_0 = state_19;
    SORT_3 var_31 = var_31_arg_0 >> 31;
    SORT_3 var_33_arg_0 = var_28;
    SORT_3 var_33_arg_1 = var_32;
    SORT_3 var_33_arg_2 = var_31;
    SORT_3 var_33 = var_33_arg_0 ? var_33_arg_1 : var_33_arg_2;
    SORT_5 var_27_arg_0 = state_19;
    SORT_25 var_27 = var_27_arg_0 >> 1;
    SORT_5 var_26_arg_0 = state_19;
    SORT_25 var_26 = var_26_arg_0 >> 0;
    SORT_3 var_29_arg_0 = var_28;
    SORT_25 var_29_arg_1 = var_27;
    SORT_25 var_29_arg_2 = var_26;
    SORT_25 var_29 = var_29_arg_0 ? var_29_arg_1 : var_29_arg_2;
    SORT_25 var_38_arg_0 = var_29;
    SORT_37 var_38 = var_38_arg_0 >> 2;
    var_38 = var_38 & mask_SORT_37;
    SORT_3 var_39_arg_0 = var_33;
    SORT_37 var_39_arg_1 = var_38;
    SORT_35 var_39 = ((SORT_35)var_39_arg_0 << 29) | var_39_arg_1;
    SORT_25 var_36_arg_0 = var_29;
    SORT_35 var_36 = var_36_arg_0 >> 0;
    SORT_3 var_41_arg_0 = var_40;
    SORT_35 var_41_arg_1 = var_39;
    SORT_35 var_41_arg_2 = var_36;
    SORT_35 var_41 = var_41_arg_0 ? var_41_arg_1 : var_41_arg_2;
    SORT_35 var_60_arg_0 = var_41;
    SORT_57 var_60 = var_60_arg_0 >> 0;
    SORT_25 var_46_arg_0 = var_29;
    SORT_43 var_46 = var_46_arg_0 >> 0;
    SORT_25 var_44_arg_0 = var_29;
    SORT_3 var_44 = var_44_arg_0 >> 30;
    var_44 = var_44 & mask_SORT_3;
    SORT_3 var_45_arg_0 = var_33;
    SORT_3 var_45_arg_1 = var_44;
    SORT_43 var_45 = ((SORT_43)var_45_arg_0 << 1) | var_45_arg_1;
    SORT_3 var_47_arg_0 = var_40;
    SORT_43 var_47_arg_1 = var_46;
    SORT_43 var_47_arg_2 = var_45;
    SORT_43 var_47 = var_47_arg_0 ? var_47_arg_1 : var_47_arg_2;
    SORT_35 var_58_arg_0 = var_41;
    SORT_43 var_58 = var_58_arg_0 >> 28;
    var_58 = var_58 & mask_SORT_43;
    SORT_43 var_59_arg_0 = var_47;
    SORT_43 var_59_arg_1 = var_58;
    SORT_57 var_59 = ((SORT_57)var_59_arg_0 << 2) | var_59_arg_1;
    SORT_3 var_61_arg_0 = var_54;
    SORT_57 var_61_arg_1 = var_60;
    SORT_57 var_61_arg_2 = var_59;
    SORT_57 var_61 = var_61_arg_0 ? var_61_arg_1 : var_61_arg_2;
    SORT_35 var_52_arg_0 = var_41;
    SORT_51 var_52 = var_52_arg_0 >> 4;
    var_52 = var_52 & mask_SORT_51;
    SORT_43 var_53_arg_0 = var_47;
    SORT_51 var_53_arg_1 = var_52;
    SORT_49 var_53 = ((SORT_49)var_53_arg_0 << 26) | var_53_arg_1;
    SORT_35 var_50_arg_0 = var_41;
    SORT_49 var_50 = var_50_arg_0 >> 0;
    SORT_3 var_55_arg_0 = var_54;
    SORT_49 var_55_arg_1 = var_53;
    SORT_49 var_55_arg_2 = var_50;
    SORT_49 var_55 = var_55_arg_0 ? var_55_arg_1 : var_55_arg_2;
    SORT_49 var_66_arg_0 = var_55;
    SORT_65 var_66 = var_66_arg_0 >> 8;
    var_66 = var_66 & mask_SORT_65;
    SORT_57 var_67_arg_0 = var_61;
    SORT_65 var_67_arg_1 = var_66;
    SORT_63 var_67 = ((SORT_63)var_67_arg_0 << 20) | var_67_arg_1;
    SORT_49 var_64_arg_0 = var_55;
    SORT_63 var_64 = var_64_arg_0 >> 0;
    SORT_3 var_69_arg_0 = var_68;
    SORT_63 var_69_arg_1 = var_67;
    SORT_63 var_69_arg_2 = var_64;
    SORT_63 var_69 = var_69_arg_0 ? var_69_arg_1 : var_69_arg_2;
    SORT_63 var_78_arg_0 = var_69;
    SORT_77 var_78 = var_78_arg_0 >> 0;
    SORT_49 var_74_arg_0 = var_55;
    SORT_71 var_74 = var_74_arg_0 >> 0;
    SORT_49 var_72_arg_0 = var_55;
    SORT_57 var_72 = var_72_arg_0 >> 24;
    var_72 = var_72 & mask_SORT_57;
    SORT_57 var_73_arg_0 = var_61;
    SORT_57 var_73_arg_1 = var_72;
    SORT_71 var_73 = ((SORT_71)var_73_arg_0 << 4) | var_73_arg_1;
    SORT_3 var_75_arg_0 = var_68;
    SORT_71 var_75_arg_1 = var_74;
    SORT_71 var_75_arg_2 = var_73;
    SORT_71 var_75 = var_75_arg_0 ? var_75_arg_1 : var_75_arg_2;
    SORT_63 var_79_arg_0 = var_69;
    SORT_71 var_79 = var_79_arg_0 >> 16;
    var_79 = var_79 & mask_SORT_71;
    SORT_71 var_80_arg_0 = var_75;
    SORT_71 var_80_arg_1 = var_79;
    SORT_77 var_80 = ((SORT_77)var_80_arg_0 << 8) | var_80_arg_1;
    SORT_3 var_84_arg_0 = var_81;
    SORT_77 var_84_arg_1 = var_78;
    SORT_77 var_84_arg_2 = var_80;
    SORT_77 var_84 = var_84_arg_0 ? var_84_arg_1 : var_84_arg_2;
    SORT_3 var_82_arg_0 = var_81;
    SORT_77 var_82_arg_1 = var_80;
    SORT_77 var_82_arg_2 = var_78;
    SORT_77 var_82 = var_82_arg_0 ? var_82_arg_1 : var_82_arg_2;
    var_82 = var_82 & mask_SORT_77;
    SORT_77 var_86_arg_0 = var_84;
    SORT_77 var_86_arg_1 = var_82;
    SORT_5 var_86 = ((SORT_5)var_86_arg_0 << 16) | var_86_arg_1;
    var_86 = var_86 & mask_SORT_5;
    SORT_5 next_87_arg_1 = var_86;
    SORT_3 var_88_arg_0 = state_23;
    SORT_5 var_88_arg_1 = state_9;
    SORT_5 var_88_arg_2 = input_6;
    SORT_5 var_88 = var_88_arg_0 ? var_88_arg_1 : var_88_arg_2;
    SORT_5 next_89_arg_1 = var_88;
    SORT_3 next_90_arg_1 = input_7;
    // Assigning next states ...
    state_9 = next_87_arg_1;
    state_19 = next_89_arg_1;
    state_23 = next_90_arg_1;
  }
  return 0;
}
