// This file is part of the SV-Benchmarks collection of verification tasks:
// https://gitlab.com/sosy-lab/benchmarking/sv-benchmarks
//
// SPDX-FileCopyrightText: 2020 Aman Goel
// SPDX-FileCopyrightText: 2022 The SV-Benchmarks Community
//
// SPDX-License-Identifier: GPL-3.0-or-later

// This C program is converted from Btor2 by Btor2C version sha1:a0fa249
//   with arguments: { architecture=64, lazy_modulo=true, use_memmove=false, unroll_inner_loops=false, shortest_type=true, diff_type=true, decimal_constant=true, zero_init=false, sra_extend_sign=true }
// Comments from the original Btor2 file:
// ; source: https://github.com/aman-goel/avr/tree/92362931700b66684418a991d018c9fbdbebc06f/tests
// ; BTOR description generated by Yosys 0.9+431 (git sha1 4a3b5437, clang 4.0.1-6 -fPIC -Os) for module main.
extern unsigned char __VERIFIER_nondet_uchar();
extern unsigned short __VERIFIER_nondet_ushort();
extern unsigned int __VERIFIER_nondet_uint();
extern unsigned long __VERIFIER_nondet_ulong();
extern void abort(void);
extern void __assert_fail(const char *, const char *, unsigned int, const char *);
void reach_error() { __assert_fail("0", "vcegar_QF_BV_itc99_b13_p18.c", 0, "reach_error"); }
void __VERIFIER_assert(int cond) { if (!(cond)) { ERROR: { reach_error(); abort(); } } }
void assume_abort_if_not(int cond) { if (!cond) { abort(); } }
int main() {
  // Defining sorts ...
  typedef unsigned char SORT_1;  // BV with 1 bits
  const SORT_1 mask_SORT_1 = (SORT_1)-1 >> (sizeof(SORT_1) * 8 - 1);
  const SORT_1 msb_SORT_1 = (SORT_1)1 << (1 - 1);
  typedef unsigned char SORT_3;  // BV with 8 bits
  const SORT_3 mask_SORT_3 = (SORT_3)-1 >> (sizeof(SORT_3) * 8 - 8);
  const SORT_3 msb_SORT_3 = (SORT_3)1 << (8 - 1);
  typedef unsigned int SORT_10;  // BV with 32 bits
  const SORT_10 mask_SORT_10 = (SORT_10)-1 >> (sizeof(SORT_10) * 8 - 32);
  const SORT_10 msb_SORT_10 = (SORT_10)1 << (32 - 1);
  typedef unsigned char SORT_30;  // BV with 4 bits
  const SORT_30 mask_SORT_30 = (SORT_30)-1 >> (sizeof(SORT_30) * 8 - 4);
  const SORT_30 msb_SORT_30 = (SORT_30)1 << (4 - 1);
  typedef unsigned short SORT_68;  // BV with 10 bits
  const SORT_68 mask_SORT_68 = (SORT_68)-1 >> (sizeof(SORT_68) * 8 - 10);
  const SORT_68 msb_SORT_68 = (SORT_68)1 << (10 - 1);
  // Initializing constants ...
  const SORT_1 var_7 = 0;
  const SORT_10 var_12 = 1;
  const SORT_1 var_22 = 1;
  // Collecting input declarations ...
  SORT_1 input_2;
  SORT_3 input_4;
  SORT_1 input_5;
  SORT_1 input_6;
  SORT_30 input_31;
  SORT_1 input_33;
  SORT_30 input_35;
  SORT_1 input_37;
  SORT_1 input_39;
  SORT_1 input_41;
  SORT_1 input_43;
  SORT_1 input_45;
  SORT_1 input_47;
  SORT_1 input_49;
  SORT_3 input_51;
  SORT_1 input_54;
  SORT_1 input_56;
  SORT_1 input_60;
  SORT_1 input_62;
  SORT_1 input_64;
  SORT_1 input_66;
  SORT_68 input_69;
  SORT_1 input_71;
  SORT_1 input_79;
  // Collecting state declarations ...
  SORT_1 state_8 = __VERIFIER_nondet_uchar() & mask_SORT_1;
  SORT_1 state_15 = __VERIFIER_nondet_uchar() & mask_SORT_1;
  SORT_1 state_26 = __VERIFIER_nondet_uchar() & mask_SORT_1;
  SORT_1 state_28 = __VERIFIER_nondet_uchar() & mask_SORT_1;
  SORT_1 state_58 = __VERIFIER_nondet_uchar() & mask_SORT_1;
  // Initializing states ...
  SORT_1 init_9_arg_1 = var_7;
  state_8 = init_9_arg_1;
  SORT_1 init_16_arg_1 = var_7;
  state_15 = init_16_arg_1;
  SORT_1 init_27_arg_1 = var_7;
  state_26 = init_27_arg_1;
  SORT_1 init_29_arg_1 = var_7;
  state_28 = init_29_arg_1;
  SORT_1 init_59_arg_1 = var_7;
  state_58 = init_59_arg_1;
  for (;;) {
    // Getting external input values ...
    input_2 = __VERIFIER_nondet_uchar();
    input_4 = __VERIFIER_nondet_uchar();
    input_5 = __VERIFIER_nondet_uchar();
    input_6 = __VERIFIER_nondet_uchar();
    input_31 = __VERIFIER_nondet_uchar();
    input_33 = __VERIFIER_nondet_uchar();
    input_35 = __VERIFIER_nondet_uchar();
    input_37 = __VERIFIER_nondet_uchar();
    input_39 = __VERIFIER_nondet_uchar();
    input_41 = __VERIFIER_nondet_uchar();
    input_43 = __VERIFIER_nondet_uchar();
    input_45 = __VERIFIER_nondet_uchar();
    input_47 = __VERIFIER_nondet_uchar();
    input_49 = __VERIFIER_nondet_uchar();
    input_51 = __VERIFIER_nondet_uchar();
    input_54 = __VERIFIER_nondet_uchar();
    input_56 = __VERIFIER_nondet_uchar();
    input_60 = __VERIFIER_nondet_uchar();
    input_62 = __VERIFIER_nondet_uchar();
    input_64 = __VERIFIER_nondet_uchar();
    input_66 = __VERIFIER_nondet_uchar();
    input_69 = __VERIFIER_nondet_ushort();
    input_71 = __VERIFIER_nondet_uchar();
    input_79 = __VERIFIER_nondet_uchar();
    // Assuming invariants ...
    // Asserting properties ...
    SORT_1 var_11_arg_0 = state_8;
    var_11_arg_0 = var_11_arg_0 & mask_SORT_1;
    SORT_10 var_11 = var_11_arg_0;
    SORT_10 var_13_arg_0 = var_11;
    SORT_10 var_13_arg_1 = var_12;
    SORT_1 var_13 = var_13_arg_0 == var_13_arg_1;
    SORT_1 var_14_arg_0 = var_13;
    SORT_1 var_14 = ~var_14_arg_0;
    SORT_1 var_17_arg_0 = state_15;
    var_17_arg_0 = var_17_arg_0 & mask_SORT_1;
    SORT_10 var_17 = var_17_arg_0;
    SORT_10 var_18_arg_0 = var_17;
    SORT_10 var_18_arg_1 = var_12;
    SORT_1 var_18 = var_18_arg_0 == var_18_arg_1;
    SORT_1 var_19_arg_0 = var_14;
    SORT_1 var_19_arg_1 = var_18;
    SORT_1 var_19 = var_19_arg_0 | var_19_arg_1;
    SORT_1 var_23_arg_0 = var_19;
    SORT_1 var_23 = ~var_23_arg_0;
    SORT_1 var_24_arg_0 = var_22;
    SORT_1 var_24_arg_1 = var_23;
    SORT_1 var_24 = var_24_arg_0 & var_24_arg_1;
    var_24 = var_24 & mask_SORT_1;
    SORT_1 bad_25_arg_0 = var_24;
    __VERIFIER_assert(!(bad_25_arg_0));
    // Computing next states ...
    SORT_1 var_73_arg_0 = state_28;
    SORT_1 var_73_arg_1 = state_8;
    SORT_1 var_73_arg_2 = state_8;
    SORT_1 var_73 = var_73_arg_0 ? var_73_arg_1 : var_73_arg_2;
    SORT_1 next_74_arg_1 = var_73;
    SORT_1 var_75_arg_0 = state_28;
    SORT_1 var_75_arg_1 = state_15;
    SORT_1 var_75_arg_2 = state_15;
    SORT_1 var_75 = var_75_arg_0 ? var_75_arg_1 : var_75_arg_2;
    SORT_1 next_76_arg_1 = var_75;
    SORT_1 var_77_arg_0 = state_26;
    SORT_1 var_77_arg_1 = var_7;
    SORT_1 var_77_arg_2 = var_22;
    SORT_1 var_77 = var_77_arg_0 ? var_77_arg_1 : var_77_arg_2;
    var_77 = var_77 & mask_SORT_1;
    SORT_1 next_78_arg_1 = var_77;
    SORT_1 var_81_arg_0 = state_28;
    SORT_1 var_81_arg_1 = var_7;
    SORT_1 var_81 = var_81_arg_0 == var_81_arg_1;
    SORT_1 var_80_arg_0 = state_58;
    SORT_1 var_80_arg_1 = var_22;
    SORT_1 var_80_arg_2 = var_7;
    SORT_1 var_80 = var_80_arg_0 ? var_80_arg_1 : var_80_arg_2;
    SORT_1 var_82_arg_0 = var_81;
    SORT_1 var_82_arg_1 = var_80;
    SORT_1 var_82_arg_2 = input_79;
    SORT_1 var_82 = var_82_arg_0 ? var_82_arg_1 : var_82_arg_2;
    SORT_1 var_83_arg_0 = state_28;
    SORT_1 var_83_arg_1 = var_7;
    SORT_1 var_83_arg_2 = var_82;
    SORT_1 var_83 = var_83_arg_0 ? var_83_arg_1 : var_83_arg_2;
    var_83 = var_83 & mask_SORT_1;
    SORT_1 next_84_arg_1 = var_83;
    SORT_1 var_85_arg_0 = state_26;
    SORT_1 var_85_arg_1 = state_58;
    SORT_1 var_85_arg_2 = state_58;
    SORT_1 var_85 = var_85_arg_0 ? var_85_arg_1 : var_85_arg_2;
    var_85 = var_85 & mask_SORT_1;
    SORT_1 next_86_arg_1 = var_85;
    // Assigning next states ...
    state_8 = next_74_arg_1;
    state_15 = next_76_arg_1;
    state_26 = next_78_arg_1;
    state_28 = next_84_arg_1;
    state_58 = next_86_arg_1;
  }
  return 0;
}
