// This file is part of the SV-Benchmarks collection of verification tasks:
// https://gitlab.com/sosy-lab/benchmarking/sv-benchmarks
//
// SPDX-FileCopyrightText: 2020 Aman Goel
// SPDX-FileCopyrightText: 2022 The SV-Benchmarks Community
//
// SPDX-License-Identifier: GPL-3.0-or-later

// This C program is converted from Btor2 by Btor2C version sha1:a0fa249
//   with arguments: { architecture=64, lazy_modulo=true, use_memmove=false, unroll_inner_loops=false, shortest_type=true, diff_type=true, decimal_constant=true, zero_init=false, sra_extend_sign=true }
// Comments from the original Btor2 file:
// ; source: https://github.com/aman-goel/avr/tree/92362931700b66684418a991d018c9fbdbebc06f/tests
// ; BTOR description generated by Yosys 0.9+431 (git sha1 4a3b5437, clang 4.0.1-6 -fPIC -Os) for module main.
extern unsigned char __VERIFIER_nondet_uchar();
extern unsigned short __VERIFIER_nondet_ushort();
extern unsigned int __VERIFIER_nondet_uint();
extern unsigned long __VERIFIER_nondet_ulong();
extern void abort(void);
extern void __assert_fail(const char *, const char *, unsigned int, const char *);
void reach_error() { __assert_fail("0", "cav14_example.c", 0, "reach_error"); }
void __VERIFIER_assert(int cond) { if (!(cond)) { ERROR: { reach_error(); abort(); } } }
void assume_abort_if_not(int cond) { if (!cond) { abort(); } }
int main() {
  // Defining sorts ...
  typedef unsigned char SORT_1;  // BV with 1 bits
  const SORT_1 mask_SORT_1 = (SORT_1)-1 >> (sizeof(SORT_1) * 8 - 1);
  const SORT_1 msb_SORT_1 = (SORT_1)1 << (1 - 1);
  typedef unsigned char SORT_3;  // BV with 3 bits
  const SORT_3 mask_SORT_3 = (SORT_3)-1 >> (sizeof(SORT_3) * 8 - 3);
  const SORT_3 msb_SORT_3 = (SORT_3)1 << (3 - 1);
  // Initializing constants ...
  const SORT_3 var_4 = 0;
  const SORT_1 var_13 = 1;
  const SORT_3 var_19 = 7;
  const SORT_3 var_23 = 1;
  // Collecting input declarations ...
  SORT_1 input_2;
  // Collecting state declarations ...
  SORT_3 state_5 = __VERIFIER_nondet_uchar() & mask_SORT_3;
  SORT_3 state_7 = __VERIFIER_nondet_uchar() & mask_SORT_3;
  // Initializing states ...
  SORT_3 init_6_arg_1 = var_4;
  state_5 = init_6_arg_1;
  SORT_3 init_8_arg_1 = var_4;
  state_7 = init_8_arg_1;
  for (;;) {
    // Getting external input values ...
    input_2 = __VERIFIER_nondet_uchar();
    // Assuming invariants ...
    // Asserting properties ...
    SORT_3 var_9_arg_0 = state_5;
    SORT_3 var_9_arg_1 = state_7;
    SORT_1 var_9 = var_9_arg_0 > var_9_arg_1;
    SORT_1 var_10_arg_0 = var_9;
    SORT_1 var_10 = ~var_10_arg_0;
    SORT_1 var_14_arg_0 = var_10;
    SORT_1 var_14 = ~var_14_arg_0;
    SORT_1 var_15_arg_0 = var_13;
    SORT_1 var_15_arg_1 = var_14;
    SORT_1 var_15 = var_15_arg_0 & var_15_arg_1;
    var_15 = var_15 & mask_SORT_1;
    SORT_1 bad_16_arg_0 = var_15;
    __VERIFIER_assert(!(bad_16_arg_0));
    // Computing next states ...
    SORT_3 var_25_arg_0 = state_5;
    SORT_3 var_25_arg_1 = state_7;
    SORT_1 var_25 = var_25_arg_0 == var_25_arg_1;
    SORT_3 var_24_arg_0 = state_5;
    SORT_3 var_24_arg_1 = var_23;
    SORT_3 var_24 = var_24_arg_0 + var_24_arg_1;
    SORT_3 var_18_arg_0 = state_5;
    SORT_3 var_18_arg_1 = state_7;
    SORT_1 var_18 = var_18_arg_0 > var_18_arg_1;
    SORT_3 var_20_arg_0 = state_7;
    SORT_3 var_20_arg_1 = var_19;
    SORT_1 var_20 = var_20_arg_0 != var_20_arg_1;
    SORT_1 var_21_arg_0 = var_18;
    SORT_1 var_21_arg_1 = var_20;
    SORT_1 var_21 = var_21_arg_0 | var_21_arg_1;
    var_21 = var_21 & mask_SORT_1;
    SORT_1 var_22_arg_0 = var_21;
    SORT_3 var_22_arg_1 = state_5;
    SORT_3 var_22_arg_2 = state_7;
    SORT_3 var_22 = var_22_arg_0 ? var_22_arg_1 : var_22_arg_2;
    SORT_1 var_26_arg_0 = var_25;
    SORT_3 var_26_arg_1 = var_24;
    SORT_3 var_26_arg_2 = var_22;
    SORT_3 var_26 = var_26_arg_0 ? var_26_arg_1 : var_26_arg_2;
    var_26 = var_26 & mask_SORT_3;
    SORT_3 next_27_arg_1 = var_26;
    SORT_3 var_33_arg_0 = state_5;
    SORT_3 var_33_arg_1 = state_7;
    SORT_1 var_33 = var_33_arg_0 > var_33_arg_1;
    SORT_3 var_29_arg_0 = state_5;
    SORT_3 var_29_arg_1 = state_7;
    SORT_1 var_29 = var_29_arg_0 == var_29_arg_1;
    SORT_3 var_30_arg_0 = state_7;
    SORT_3 var_30_arg_1 = var_19;
    SORT_1 var_30 = var_30_arg_0 != var_30_arg_1;
    SORT_1 var_31_arg_0 = var_29;
    SORT_1 var_31_arg_1 = var_30;
    SORT_1 var_31 = var_31_arg_0 | var_31_arg_1;
    var_31 = var_31 & mask_SORT_1;
    SORT_3 var_28_arg_0 = state_7;
    SORT_3 var_28_arg_1 = var_23;
    SORT_3 var_28 = var_28_arg_0 + var_28_arg_1;
    SORT_1 var_32_arg_0 = var_31;
    SORT_3 var_32_arg_1 = var_28;
    SORT_3 var_32_arg_2 = state_5;
    SORT_3 var_32 = var_32_arg_0 ? var_32_arg_1 : var_32_arg_2;
    SORT_1 var_34_arg_0 = var_33;
    SORT_3 var_34_arg_1 = state_7;
    SORT_3 var_34_arg_2 = var_32;
    SORT_3 var_34 = var_34_arg_0 ? var_34_arg_1 : var_34_arg_2;
    var_34 = var_34 & mask_SORT_3;
    SORT_3 next_35_arg_1 = var_34;
    // Assigning next states ...
    state_5 = next_27_arg_1;
    state_7 = next_35_arg_1;
  }
  return 0;
}
