// This file is part of the SV-Benchmarks collection of verification tasks:
// https://gitlab.com/sosy-lab/benchmarking/sv-benchmarks
//
// SPDX-FileCopyrightText: 2020 Aman Goel
// SPDX-FileCopyrightText: 2022 The SV-Benchmarks Community
//
// SPDX-License-Identifier: GPL-3.0-or-later

// This C program is converted from Btor2 by Btor2C version sha1:a0fa249
//   with arguments: { architecture=64, lazy_modulo=true, use_memmove=false, unroll_inner_loops=false, shortest_type=true, diff_type=true, decimal_constant=true, zero_init=false, sra_extend_sign=true }
// Comments from the original Btor2 file:
// ; source: https://github.com/aman-goel/avr/tree/92362931700b66684418a991d018c9fbdbebc06f/tests
// ; BTOR description generated by Yosys 0.9+431 (git sha1 4a3b5437, clang 4.0.1-6 -fPIC -Os) for module main.
extern unsigned char __VERIFIER_nondet_uchar();
extern unsigned short __VERIFIER_nondet_ushort();
extern unsigned int __VERIFIER_nondet_uint();
extern unsigned long __VERIFIER_nondet_ulong();
extern void abort(void);
extern void __assert_fail(const char *, const char *, unsigned int, const char *);
void reach_error() { __assert_fail("0", "dyn_partition.c", 0, "reach_error"); }
void __VERIFIER_assert(int cond) { if (!(cond)) { ERROR: { reach_error(); abort(); } } }
void assume_abort_if_not(int cond) { if (!cond) { abort(); } }
int main() {
  // Defining sorts ...
  typedef unsigned char SORT_1;  // BV with 1 bits
  const SORT_1 mask_SORT_1 = (SORT_1)-1 >> (sizeof(SORT_1) * 8 - 1);
  const SORT_1 msb_SORT_1 = (SORT_1)1 << (1 - 1);
  typedef unsigned char SORT_4;  // BV with 3 bits
  const SORT_4 mask_SORT_4 = (SORT_4)-1 >> (sizeof(SORT_4) * 8 - 3);
  const SORT_4 msb_SORT_4 = (SORT_4)1 << (3 - 1);
  typedef unsigned int SORT_23;  // BV with 32 bits
  const SORT_23 mask_SORT_23 = (SORT_23)-1 >> (sizeof(SORT_23) * 8 - 32);
  const SORT_23 msb_SORT_23 = (SORT_23)1 << (32 - 1);
  // Initializing constants ...
  const SORT_4 var_5 = 0;
  const SORT_1 var_13 = 1;
  const SORT_1 var_17 = 0;
  const SORT_23 var_25 = 1;
  // Collecting input declarations ...
  SORT_1 input_2;
  SORT_1 input_3;
  // Collecting state declarations ...
  SORT_4 state_6 = __VERIFIER_nondet_uchar() & mask_SORT_4;
  SORT_4 state_8 = __VERIFIER_nondet_uchar() & mask_SORT_4;
  SORT_1 state_18 = __VERIFIER_nondet_uchar() & mask_SORT_1;
  SORT_1 state_20 = __VERIFIER_nondet_uchar() & mask_SORT_1;
  // Initializing states ...
  SORT_4 init_7_arg_1 = var_5;
  state_6 = init_7_arg_1;
  SORT_4 init_9_arg_1 = var_5;
  state_8 = init_9_arg_1;
  SORT_1 init_19_arg_1 = var_17;
  state_18 = init_19_arg_1;
  SORT_1 init_21_arg_1 = var_17;
  state_20 = init_21_arg_1;
  for (;;) {
    // Getting external input values ...
    input_2 = __VERIFIER_nondet_uchar();
    input_3 = __VERIFIER_nondet_uchar();
    // Assuming invariants ...
    // Asserting properties ...
    SORT_4 var_10_arg_0 = state_6;
    SORT_4 var_10_arg_1 = state_8;
    SORT_1 var_10 = var_10_arg_0 <= var_10_arg_1;
    SORT_1 var_14_arg_0 = var_10;
    SORT_1 var_14 = ~var_14_arg_0;
    SORT_1 var_15_arg_0 = var_13;
    SORT_1 var_15_arg_1 = var_14;
    SORT_1 var_15 = var_15_arg_0 & var_15_arg_1;
    var_15 = var_15 & mask_SORT_1;
    SORT_1 bad_16_arg_0 = var_15;
    __VERIFIER_assert(!(bad_16_arg_0));
    // Computing next states ...
    SORT_1 var_28_arg_0 = state_18;
    SORT_1 var_28_arg_1 = state_20;
    SORT_1 var_28 = var_28_arg_0 == var_28_arg_1;
    SORT_4 var_24_arg_0 = state_6;
    var_24_arg_0 = var_24_arg_0 & mask_SORT_4;
    SORT_23 var_24 = var_24_arg_0;
    SORT_23 var_26_arg_0 = var_24;
    SORT_23 var_26_arg_1 = var_25;
    SORT_23 var_26 = var_26_arg_0 + var_26_arg_1;
    SORT_23 var_27_arg_0 = var_26;
    SORT_4 var_27 = var_27_arg_0 >> 0;
    SORT_1 var_29_arg_0 = var_28;
    SORT_4 var_29_arg_1 = state_6;
    SORT_4 var_29_arg_2 = var_27;
    SORT_4 var_29 = var_29_arg_0 ? var_29_arg_1 : var_29_arg_2;
    var_29 = var_29 & mask_SORT_4;
    SORT_4 next_30_arg_1 = var_29;
    SORT_4 var_31_arg_0 = state_8;
    var_31_arg_0 = var_31_arg_0 & mask_SORT_4;
    SORT_23 var_31 = var_31_arg_0;
    SORT_23 var_32_arg_0 = var_31;
    SORT_23 var_32_arg_1 = var_25;
    SORT_23 var_32 = var_32_arg_0 + var_32_arg_1;
    SORT_23 var_33_arg_0 = var_32;
    SORT_4 var_33 = var_33_arg_0 >> 0;
    SORT_1 var_34_arg_0 = var_28;
    SORT_4 var_34_arg_1 = var_33;
    SORT_4 var_34_arg_2 = state_8;
    SORT_4 var_34 = var_34_arg_0 ? var_34_arg_1 : var_34_arg_2;
    var_34 = var_34 & mask_SORT_4;
    SORT_4 next_35_arg_1 = var_34;
    SORT_1 var_36_arg_0 = state_20;
    SORT_1 var_36 = ~var_36_arg_0;
    var_36 = var_36 & mask_SORT_1;
    SORT_1 next_37_arg_1 = var_36;
    SORT_1 next_38_arg_1 = state_18;
    // Assigning next states ...
    state_6 = next_30_arg_1;
    state_8 = next_35_arg_1;
    state_18 = next_37_arg_1;
    state_20 = next_38_arg_1;
  }
  return 0;
}
