// This file is part of the SV-Benchmarks collection of verification tasks:
// https://gitlab.com/sosy-lab/benchmarking/sv-benchmarks
//
// SPDX-FileCopyrightText: 2020 Aman Goel
// SPDX-FileCopyrightText: 2022 The SV-Benchmarks Community
//
// SPDX-License-Identifier: GPL-3.0-or-later

// This C program is converted from Btor2 by Btor2C version sha1:a0fa249
//   with arguments: { architecture=64, lazy_modulo=true, use_memmove=false, unroll_inner_loops=false, shortest_type=true, diff_type=true, decimal_constant=true, zero_init=false, sra_extend_sign=true }
// Comments from the original Btor2 file:
// ; source: https://github.com/aman-goel/avr/tree/92362931700b66684418a991d018c9fbdbebc06f/tests
// ; BTOR description generated by Yosys 0.9+431 (git sha1 4a3b5437, clang 4.0.1-6 -fPIC -Os) for module main.
extern unsigned char __VERIFIER_nondet_uchar();
extern unsigned short __VERIFIER_nondet_ushort();
extern unsigned int __VERIFIER_nondet_uint();
extern unsigned long __VERIFIER_nondet_ulong();
extern void abort(void);
extern void __assert_fail(const char *, const char *, unsigned int, const char *);
void reach_error() { __assert_fail("0", "synabs2.c", 0, "reach_error"); }
void __VERIFIER_assert(int cond) { if (!(cond)) { ERROR: { reach_error(); abort(); } } }
void assume_abort_if_not(int cond) { if (!cond) { abort(); } }
int main() {
  // Defining sorts ...
  typedef unsigned char SORT_1;  // BV with 1 bits
  const SORT_1 mask_SORT_1 = (SORT_1)-1 >> (sizeof(SORT_1) * 8 - 1);
  const SORT_1 msb_SORT_1 = (SORT_1)1 << (1 - 1);
  typedef unsigned char SORT_4;  // BV with 5 bits
  const SORT_4 mask_SORT_4 = (SORT_4)-1 >> (sizeof(SORT_4) * 8 - 5);
  const SORT_4 msb_SORT_4 = (SORT_4)1 << (5 - 1);
  typedef unsigned int SORT_19;  // BV with 32 bits
  const SORT_19 mask_SORT_19 = (SORT_19)-1 >> (sizeof(SORT_19) * 8 - 32);
  const SORT_19 msb_SORT_19 = (SORT_19)1 << (32 - 1);
  // Initializing constants ...
  const SORT_4 var_5 = 0;
  const SORT_4 var_8 = 6;
  const SORT_1 var_14 = 1;
  const SORT_19 var_21 = 2;
  // Collecting input declarations ...
  SORT_1 input_2;
  SORT_1 input_3;
  // Collecting state declarations ...
  SORT_4 state_6 = __VERIFIER_nondet_uchar() & mask_SORT_4;
  SORT_4 state_9 = __VERIFIER_nondet_uchar() & mask_SORT_4;
  // Initializing states ...
  SORT_4 init_7_arg_1 = var_5;
  state_6 = init_7_arg_1;
  SORT_4 init_10_arg_1 = var_8;
  state_9 = init_10_arg_1;
  for (;;) {
    // Getting external input values ...
    input_2 = __VERIFIER_nondet_uchar();
    input_3 = __VERIFIER_nondet_uchar();
    // Assuming invariants ...
    // Asserting properties ...
    SORT_4 var_11_arg_0 = state_6;
    SORT_4 var_11_arg_1 = state_9;
    SORT_1 var_11 = var_11_arg_0 < var_11_arg_1;
    SORT_1 var_15_arg_0 = var_11;
    SORT_1 var_15 = ~var_15_arg_0;
    SORT_1 var_16_arg_0 = var_14;
    SORT_1 var_16_arg_1 = var_15;
    SORT_1 var_16 = var_16_arg_0 & var_16_arg_1;
    var_16 = var_16 & mask_SORT_1;
    SORT_1 bad_17_arg_0 = var_16;
    __VERIFIER_assert(!(bad_17_arg_0));
    // Computing next states ...
    SORT_4 var_20_arg_0 = state_6;
    var_20_arg_0 = var_20_arg_0 & mask_SORT_4;
    SORT_19 var_20 = var_20_arg_0;
    SORT_19 var_22_arg_0 = var_20;
    SORT_19 var_22_arg_1 = var_21;
    SORT_19 var_22 = var_22_arg_0 + var_22_arg_1;
    SORT_19 var_23_arg_0 = var_22;
    SORT_4 var_23 = var_23_arg_0 >> 0;
    var_23 = var_23 & mask_SORT_4;
    SORT_4 next_24_arg_1 = var_23;
    SORT_4 var_25_arg_0 = state_9;
    var_25_arg_0 = var_25_arg_0 & mask_SORT_4;
    SORT_19 var_25 = var_25_arg_0;
    SORT_19 var_26_arg_0 = var_25;
    SORT_19 var_26_arg_1 = var_21;
    SORT_19 var_26 = var_26_arg_0 + var_26_arg_1;
    SORT_19 var_27_arg_0 = var_26;
    SORT_4 var_27 = var_27_arg_0 >> 0;
    var_27 = var_27 & mask_SORT_4;
    SORT_4 next_28_arg_1 = var_27;
    // Assigning next states ...
    state_6 = next_24_arg_1;
    state_9 = next_28_arg_1;
  }
  return 0;
}
