name: 'Report on benchexec tests'
description: 'Collecting results of benchexec runs, and creating report'
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
    - name: Install benchexec
      shell: bash
      run: |
        sudo add-apt-repository -y ppa:sosy-lab/benchmarking
        sudo apt-get update -y
        sudo apt-get install -y benchexec || true
    - name: Ensure xmlstarlet is installed
      shell: bash
      run: |
        sudo apt-get update -y
        sudo apt-get install -y xmlstarlet || true
    - name: Download artifacts
      uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v3.0.2
      with:
        path: artifacts
    - name: Generate tables
      id: generate
      shell: bash
      run: |
        cd artifacts
        unzip *.zip
        EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
        echo "Message<<$EOF" >> $GITHUB_OUTPUT
        echo "| Rundefinition | Correct | Incorrect | All | Status |" >> $GITHUB_OUTPUT
        echo "|--|--|--|--|--|" >> $GITHUB_OUTPUT
        lasttask=""
        for i in *
        do 
          if (ls "$i"/*xml.bz2 >/dev/null 2>/dev/null)
          then
            pushd "$i"
            filename=${i#BenchexecResults-}
            portfolio=${filename##*-}
            task=${filename%-$portfolio}
            if [ "$task" != "$lasttask" ]
            then printf "| $task | " >> $GITHUB_OUTPUT
            fi
            lasttask="$task"
            # Compute correct/incorrect/all from XML directly
            correct=0
            incorrect=0
            all=0
            for xf in *.xml.bz2; do
              [ -e "$xf" ] || continue
              new_correct=$(bzcat "$xf" | xmlstarlet sel -t -v "count(/result/run/column[@title='category' and @value='correct'])" 2>/dev/null || echo 0)
              new_incorrect=$(bzcat "$xf" | xmlstarlet sel -t -v "count(/result/run/column[@title='category' and @value='incorrect'])" 2>/dev/null || echo 0)
              new_all=$(bzcat "$xf" | xmlstarlet sel -t -v "count(/result/run)" 2>/dev/null || echo 0)
              correct=$((correct + ${new_correct:-0}))
              incorrect=$((incorrect + ${new_incorrect:-0}))
              all=$((all + ${new_all:-0}))
            done
            emoji=":white_check_mark:"
            [ "$correct" -eq 0 ] && emoji=":question:"
            [ "$incorrect" -eq 0 ] || emoji=":exclamation:"
            printf "$correct | $incorrect | $all | $emoji |\n" >> $GITHUB_OUTPUT
            popd
          else
            rm -rf "$i"
          fi
        done
        echo "$EOF" >> $GITHUB_OUTPUT
    - name: Upload results
      uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v3.1.2
      with:
        name: BenchexecResults
        path: artifacts
    - name: Comment on PR
      if: github.event_name == 'pull_request'
      uses: thollander/actions-comment-pull-request@dadb7667129e23f12ca3925c90dc5cd7121ab57e
      continue-on-error: true # if we are in a fork, this will fail, but we don't care (tables will be missing)
      with: 
        comment_tag: 'diffcheck'
        mode: 'recreate'
        message: |
          Benchexec test report for a selection of SV-Benchmarks (correct / incorrect / all):

          ${{ steps.generate.outputs.Message }}
