name: 'Report on benchexec tests'
description: 'Collecting results of benchexec runs, and creating report'
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
    - name: Install benchexec
      shell: bash
      run: |
        sudo add-apt-repository ppa:sosy-lab/benchmarking
        sudo apt install benchexec
    - name: Download artifacts
      uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
      with:
        path: artifacts
    - name: Generate tables
      id: generate
      shell: bash
      run: |
        cd artifacts
        EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
        echo "Message<<$EOF" >> $GITHUB_OUTPUT
        for i in *
        do 
          pushd $i
          if (ls *xml.bz2 >/dev/null 2>/dev/null)
          then
            table-generator -d *xml.bz2
            sed -i 's/\.\.\/sv-benchmarks/https:\/\/gitlab\.com\/sosy-lab\/benchmarking\/sv-benchmarks\/-\/raw\/main/g' *.html
            unzip *.zip
            echo "<details><summary>${i#BenchexecResults-} ($(echo $(tail -n9 *.txt | grep Score | awk ' { $1=""; print $0 } ')))</summary>" >> $GITHUB_OUTPUT
            echo '```'  >> $GITHUB_OUTPUT
            tail -n9 *.txt  >> $GITHUB_OUTPUT
            echo '```'  >> $GITHUB_OUTPUT
            echo "</details>" >> $GITHUB_OUTPUT
            echo >> $GITHUB_OUTPUT
            echo >> $GITHUB_OUTPUT
          fi
          popd
        done
        echo "$EOF" >> $GITHUB_OUTPUT
    - name: Upload results
      uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
      with:
        name: BenchexecResults-${{ matrix.task }}
        path: results
    - name: See PR message
      shell: bash
      run: |
        echo "${{ steps.generate.outputs.Message }}"
    - name: Comment on PR
      if: github.event_name == 'pull_request'
      uses: thollander/actions-comment-pull-request@dadb7667129e23f12ca3925c90dc5cd7121ab57e
      with: 
        comment_tag: 'diffcheck'
        mode: 'recreate'
        message: |
          Benchexec test report for a selection of SV-Benchmarks:

          ${{ steps.generate.outputs.Message }}