sudo: required
dist: trusty
language: java
jdk:
  - oraclejdk8
install:
  - sudo apt-get install antlr
script:
  - cd hu.bme.mit.inf.theta.core
  - antlr4 CoreDsl.g4 -o src-gen/hu/bme/mit/inf/theta/core/dsl/gen -package hu.bme.mit.inf.theta.core.dsl.gen -Werror -visitor
  - hu.bme.mit.inf.theta.formalism
  - antlr4 TcfaDsl.g4 -o src-gen/hu/bme/mit/inf/theta/formalism/tcfa/dsl/gen -package hu.bme.mit.inf.theta.formalism.tcfa.dsl.gen -Werror -visitor
  - ./gradlew assemble
  - ./gradlew check --continue
