name: 'Gradle build action'
description: 'Running gradle build without tests'
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
    - name: Setup java 17
      uses: actions/setup-java@5ffc13f4174014e2d4d4572b3d74c3fa61aeb2c2 # v3.11.0
      with:
        distribution: temurin
        java-version: 17
    - name: Build using gradle (without tests)
      uses: ./.github/actions/cache-build
      with:
        arguments: build -x test