/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hu_bme_mit_theta_llvm2xcfa_LlvmIrProvider */

#ifndef _Included_hu_bme_mit_theta_llvm2xcfa_LlvmIrProvider
#define _Included_hu_bme_mit_theta_llvm2xcfa_LlvmIrProvider
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hu_bme_mit_theta_llvm2xcfa_LlvmIrProvider
 * Method:    JniParseIr
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL
Java_hu_bme_mit_theta_llvm2xcfa_LlvmIrProvider_JniParseIr
(JNIEnv
*, jobject, jstring);

/*
 * Class:     hu_bme_mit_theta_llvm2xcfa_LlvmIrProvider
 * Method:    JniDisableInlining
 * Signature: ()V
 */
JNIEXPORT void JNICALL
Java_hu_bme_mit_theta_llvm2xcfa_LlvmIrProvider_JniDisableInlining
(JNIEnv
*, jobject);

/*
 * Class:     hu_bme_mit_theta_llvm2xcfa_LlvmIrProvider
 * Method:    JniDisableOptimizationPasses
 * Signature: ()V
 */
JNIEXPORT void JNICALL
Java_hu_bme_mit_theta_llvm2xcfa_LlvmIrProvider_JniDisableOptimizationPasses
(JNIEnv
*, jobject);

/*
 * Class:     hu_bme_mit_theta_llvm2xcfa_LlvmIrProvider
 * Method:    JniDisableCleanupPasses
 * Signature: ()V
 */
JNIEXPORT void JNICALL
Java_hu_bme_mit_theta_llvm2xcfa_LlvmIrProvider_JniDisableCleanupPasses
(JNIEnv
*, jobject);

/*
 * Class:     hu_bme_mit_theta_llvm2xcfa_LlvmIrProvider
 * Method:    JniDisablePrintDebugIr
 * Signature: ()V
 */
JNIEXPORT void JNICALL
Java_hu_bme_mit_theta_llvm2xcfa_LlvmIrProvider_JniDisablePrintDebugIr
(JNIEnv
*, jobject);

/*
 * Class:     hu_bme_mit_theta_llvm2xcfa_LlvmIrProvider
 * Method:    JniGetGlobalVariablesNum
 * Signature: ()I
 */
JNIEXPORT jint
JNICALL Java_hu_bme_mit_theta_llvm2xcfa_LlvmIrProvider_JniGetGlobalVariablesNum
        (JNIEnv * , jobject);

/*
 * Class:     hu_bme_mit_theta_llvm2xcfa_LlvmIrProvider
 * Method:    JniGetGlobalVariableName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring
JNICALL Java_hu_bme_mit_theta_llvm2xcfa_LlvmIrProvider_JniGetGlobalVariableName
        (JNIEnv * , jobject, jint);

/*
 * Class:     hu_bme_mit_theta_llvm2xcfa_LlvmIrProvider
 * Method:    JniGetGlobalVariableType
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring
JNICALL Java_hu_bme_mit_theta_llvm2xcfa_LlvmIrProvider_JniGetGlobalVariableType
        (JNIEnv * , jobject, jint);

/*
 * Class:     hu_bme_mit_theta_llvm2xcfa_LlvmIrProvider
 * Method:    JniGetGlobalVariableValue
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring
JNICALL Java_hu_bme_mit_theta_llvm2xcfa_LlvmIrProvider_JniGetGlobalVariableValue
        (JNIEnv * , jobject, jint);

/*
 * Class:     hu_bme_mit_theta_llvm2xcfa_LlvmIrProvider
 * Method:    JniGetFunctionsNum
 * Signature: ()I
 */
JNIEXPORT jint
JNICALL Java_hu_bme_mit_theta_llvm2xcfa_LlvmIrProvider_JniGetFunctionsNum
        (JNIEnv * , jobject);

/*
 * Class:     hu_bme_mit_theta_llvm2xcfa_LlvmIrProvider
 * Method:    JniGetFunctionRetType
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring
JNICALL Java_hu_bme_mit_theta_llvm2xcfa_LlvmIrProvider_JniGetFunctionRetType
        (JNIEnv * , jobject, jint);

/*
 * Class:     hu_bme_mit_theta_llvm2xcfa_LlvmIrProvider
 * Method:    JniGetFunctionName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring
JNICALL Java_hu_bme_mit_theta_llvm2xcfa_LlvmIrProvider_JniGetFunctionName
        (JNIEnv * , jobject, jint);

/*
 * Class:     hu_bme_mit_theta_llvm2xcfa_LlvmIrProvider
 * Method:    JniGetNumOfFunctionParameters
 * Signature: (I)I
 */
JNIEXPORT jint
JNICALL Java_hu_bme_mit_theta_llvm2xcfa_LlvmIrProvider_JniGetNumOfFunctionParameters
        (JNIEnv * , jobject, jint);

/*
 * Class:     hu_bme_mit_theta_llvm2xcfa_LlvmIrProvider
 * Method:    JniGetParameterType
 * Signature: (II)Ljava/lang/String;
 */
JNIEXPORT jstring
JNICALL Java_hu_bme_mit_theta_llvm2xcfa_LlvmIrProvider_JniGetParameterType
        (JNIEnv * , jobject, jint, jint);

/*
 * Class:     hu_bme_mit_theta_llvm2xcfa_LlvmIrProvider
 * Method:    JniGetParameterName
 * Signature: (II)Ljava/lang/String;
 */
JNIEXPORT jstring
JNICALL Java_hu_bme_mit_theta_llvm2xcfa_LlvmIrProvider_JniGetParameterName
        (JNIEnv * , jobject, jint, jint);

/*
 * Class:     hu_bme_mit_theta_llvm2xcfa_LlvmIrProvider
 * Method:    JniGetNumOfBasicBlocks
 * Signature: (I)I
 */
JNIEXPORT jint
JNICALL Java_hu_bme_mit_theta_llvm2xcfa_LlvmIrProvider_JniGetNumOfBasicBlocks
        (JNIEnv * , jobject, jint);

/*
 * Class:     hu_bme_mit_theta_llvm2xcfa_LlvmIrProvider
 * Method:    JniGetFunctionIndex
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint
JNICALL Java_hu_bme_mit_theta_llvm2xcfa_LlvmIrProvider_JniGetFunctionIndex
        (JNIEnv * , jobject, jstring);

/*
 * Class:     hu_bme_mit_theta_llvm2xcfa_LlvmIrProvider
 * Method:    JniGetBlockName
 * Signature: (II)Ljava/lang/String;
 */
JNIEXPORT jstring
JNICALL Java_hu_bme_mit_theta_llvm2xcfa_LlvmIrProvider_JniGetBlockName
        (JNIEnv * , jobject, jint, jint);

/*
 * Class:     hu_bme_mit_theta_llvm2xcfa_LlvmIrProvider
 * Method:    JniGetBlockIndex
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint
JNICALL Java_hu_bme_mit_theta_llvm2xcfa_LlvmIrProvider_JniGetBlockIndex
        (JNIEnv * , jobject, jint, jstring);

/*
 * Class:     hu_bme_mit_theta_llvm2xcfa_LlvmIrProvider
 * Method:    JniGetNumOfInstructions
 * Signature: (II)I
 */
JNIEXPORT jint
JNICALL Java_hu_bme_mit_theta_llvm2xcfa_LlvmIrProvider_JniGetNumOfInstructions
        (JNIEnv * , jobject, jint, jint);

/*
 * Class:     hu_bme_mit_theta_llvm2xcfa_LlvmIrProvider
 * Method:    JniGetInstructionLineNumber
 * Signature: (III)I
 */
JNIEXPORT jint
JNICALL Java_hu_bme_mit_theta_llvm2xcfa_LlvmIrProvider_JniGetInstructionLineNumber
        (JNIEnv * , jobject, jint, jint, jint);

/*
 * Class:     hu_bme_mit_theta_llvm2xcfa_LlvmIrProvider
 * Method:    JniGetInstructionOpcode
 * Signature: (III)Ljava/lang/String;
 */
JNIEXPORT jstring
JNICALL Java_hu_bme_mit_theta_llvm2xcfa_LlvmIrProvider_JniGetInstructionOpcode
        (JNIEnv * , jobject, jint, jint, jint);

/*
 * Class:     hu_bme_mit_theta_llvm2xcfa_LlvmIrProvider
 * Method:    JniGetInstructionRetType
 * Signature: (III)Ljava/lang/String;
 */
JNIEXPORT jstring
JNICALL Java_hu_bme_mit_theta_llvm2xcfa_LlvmIrProvider_JniGetInstructionRetType
        (JNIEnv * , jobject, jint, jint, jint);

/*
 * Class:     hu_bme_mit_theta_llvm2xcfa_LlvmIrProvider
 * Method:    JniGetInstructionRetName
 * Signature: (III)Ljava/lang/String;
 */
JNIEXPORT jstring
JNICALL Java_hu_bme_mit_theta_llvm2xcfa_LlvmIrProvider_JniGetInstructionRetName
        (JNIEnv * , jobject, jint, jint, jint);

/*
 * Class:     hu_bme_mit_theta_llvm2xcfa_LlvmIrProvider
 * Method:    JniGetInstructionNumOfOperands
 * Signature: (III)I
 */
JNIEXPORT jint
JNICALL Java_hu_bme_mit_theta_llvm2xcfa_LlvmIrProvider_JniGetInstructionNumOfOperands
        (JNIEnv * , jobject, jint, jint, jint);

/*
 * Class:     hu_bme_mit_theta_llvm2xcfa_LlvmIrProvider
 * Method:    JniGetInstructionOperandVarType
 * Signature: (IIII)Ljava/lang/String;
 */
JNIEXPORT jstring
JNICALL Java_hu_bme_mit_theta_llvm2xcfa_LlvmIrProvider_JniGetInstructionOperandVarType
        (JNIEnv * , jobject, jint, jint, jint, jint);

/*
 * Class:     hu_bme_mit_theta_llvm2xcfa_LlvmIrProvider
 * Method:    JniGetInstructionOperandVarName
 * Signature: (IIII)Ljava/lang/String;
 */
JNIEXPORT jstring
JNICALL Java_hu_bme_mit_theta_llvm2xcfa_LlvmIrProvider_JniGetInstructionOperandVarName
        (JNIEnv * , jobject, jint, jint, jint, jint);

/*
 * Class:     hu_bme_mit_theta_llvm2xcfa_LlvmIrProvider
 * Method:    JniGetStructAnalysisResult
 * Signature: ()I
 */
JNIEXPORT jboolean
JNICALL Java_hu_bme_mit_theta_llvm2xcfa_LlvmIrProvider_JniGetStructAnalysisResult
        (JNIEnv * , jobject);

/*
 * Class:     hu_bme_mit_theta_llvm2xcfa_LlvmIrProvider
 * Method:    JniGetBitwiseArithmeticAnalysisResult
 * Signature: ()I
 */
JNIEXPORT jboolean
JNICALL Java_hu_bme_mit_theta_llvm2xcfa_LlvmIrProvider_JniGetBitwiseArithmeticAnalysisResult
        (JNIEnv * , jobject);

#ifdef __cplusplus
}
#endif
#endif
