format_version: '2.0'

# old file name: mergeSort_true-termination.c.i
input_files: 'mergeSort.i'

properties:
  - property_file: ../properties/termination.prp
    expected_verdict: true
  - property_file: ../properties/coverage-branches.prp
  - property_file: ../properties/coverage-conditions.prp
  - property_file: ../properties/coverage-statements.prp

options:
  language: C
  data_model: LP64
