format_version: '2.0'

# old file name: structure_assignment_true-termination.c_true-unreach-call.i
input_files: 'structure_assignment.i'

properties:
  - property_file: ../properties/valid-memsafety.prp
    expected_verdict: true
  - property_file: ../properties/termination.prp
    expected_verdict: true
  - property_file: ../properties/unreach-call.prp
    expected_verdict: true

options:
  language: C
  data_model: ILP32
