/*
 * generated by Xtext 2.42.0
 */
package tools.refinery.language.serializer;

import com.google.inject.Inject;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AlternativeAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.GroupAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;
import tools.refinery.language.services.ProblemGrammarAccess;

@SuppressWarnings("all")
public class ProblemSyntacticSequencer extends AbstractSyntacticSequencer {

	protected ProblemGrammarAccess grammarAccess;
	protected AbstractElementAlias match_AnnotatedStatement_DeclareKeyword_1_9_1_1_0_q;
	protected AbstractElementAlias match_AnnotatedStatement_FullStopKeyword_1_0_5_1_or___LeftCurlyBracketKeyword_1_0_5_0_0_RightCurlyBracketKeyword_1_0_5_0_2__;
	protected AbstractElementAlias match_AnnotatedStatement_FullStopKeyword_1_1_3_1_or___LeftCurlyBracketKeyword_1_1_3_0_0_RightCurlyBracketKeyword_1_1_3_0_2__;
	protected AbstractElementAlias match_AnnotatedStatement_SemicolonKeyword_1_0_5_0_1_1_q;
	protected AbstractElementAlias match_AnnotatedStatement___CommaKeyword_1_1_3_0_1_2_0_or_SemicolonKeyword_1_1_3_0_1_2_1__q;
	protected AbstractElementAlias match_Annotation___LeftParenthesisKeyword_2_0_RightParenthesisKeyword_2_2__q;
	protected AbstractElementAlias match_UnaryExpr_LeftParenthesisKeyword_7_0_a;
	protected AbstractElementAlias match_UnaryExpr_LeftParenthesisKeyword_7_0_p;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (ProblemGrammarAccess) access;
		match_AnnotatedStatement_DeclareKeyword_1_9_1_1_0_q = new TokenAlias(false, true, grammarAccess.getAnnotatedStatementAccess().getDeclareKeyword_1_9_1_1_0());
		match_AnnotatedStatement_FullStopKeyword_1_0_5_1_or___LeftCurlyBracketKeyword_1_0_5_0_0_RightCurlyBracketKeyword_1_0_5_0_2__ = new AlternativeAlias(false, false, new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getAnnotatedStatementAccess().getLeftCurlyBracketKeyword_1_0_5_0_0()), new TokenAlias(false, false, grammarAccess.getAnnotatedStatementAccess().getRightCurlyBracketKeyword_1_0_5_0_2())), new TokenAlias(false, false, grammarAccess.getAnnotatedStatementAccess().getFullStopKeyword_1_0_5_1()));
		match_AnnotatedStatement_FullStopKeyword_1_1_3_1_or___LeftCurlyBracketKeyword_1_1_3_0_0_RightCurlyBracketKeyword_1_1_3_0_2__ = new AlternativeAlias(false, false, new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getAnnotatedStatementAccess().getLeftCurlyBracketKeyword_1_1_3_0_0()), new TokenAlias(false, false, grammarAccess.getAnnotatedStatementAccess().getRightCurlyBracketKeyword_1_1_3_0_2())), new TokenAlias(false, false, grammarAccess.getAnnotatedStatementAccess().getFullStopKeyword_1_1_3_1()));
		match_AnnotatedStatement_SemicolonKeyword_1_0_5_0_1_1_q = new TokenAlias(false, true, grammarAccess.getAnnotatedStatementAccess().getSemicolonKeyword_1_0_5_0_1_1());
		match_AnnotatedStatement___CommaKeyword_1_1_3_0_1_2_0_or_SemicolonKeyword_1_1_3_0_1_2_1__q = new AlternativeAlias(false, true, new TokenAlias(false, false, grammarAccess.getAnnotatedStatementAccess().getCommaKeyword_1_1_3_0_1_2_0()), new TokenAlias(false, false, grammarAccess.getAnnotatedStatementAccess().getSemicolonKeyword_1_1_3_0_1_2_1()));
		match_Annotation___LeftParenthesisKeyword_2_0_RightParenthesisKeyword_2_2__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getAnnotationAccess().getLeftParenthesisKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getAnnotationAccess().getRightParenthesisKeyword_2_2()));
		match_UnaryExpr_LeftParenthesisKeyword_7_0_a = new TokenAlias(true, true, grammarAccess.getUnaryExprAccess().getLeftParenthesisKeyword_7_0());
		match_UnaryExpr_LeftParenthesisKeyword_7_0_p = new TokenAlias(true, false, grammarAccess.getUnaryExprAccess().getLeftParenthesisKeyword_7_0());
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (ruleCall.getRule() == grammarAccess.getTRANSITIVE_CLOSURERule())
			return getTRANSITIVE_CLOSUREToken(semanticObject, ruleCall, node);
		return "";
	}
	
	/**
	 * Synthetic terminal rule. The concrete syntax is to be specified by clients.
	 * Defaults to the empty string.
	 */
	protected String getTRANSITIVE_CLOSUREToken(EObject semanticObject, RuleCall ruleCall, INode node) { return ""; }
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_AnnotatedStatement_DeclareKeyword_1_9_1_1_0_q.equals(syntax))
				emit_AnnotatedStatement_DeclareKeyword_1_9_1_1_0_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_AnnotatedStatement_FullStopKeyword_1_0_5_1_or___LeftCurlyBracketKeyword_1_0_5_0_0_RightCurlyBracketKeyword_1_0_5_0_2__.equals(syntax))
				emit_AnnotatedStatement_FullStopKeyword_1_0_5_1_or___LeftCurlyBracketKeyword_1_0_5_0_0_RightCurlyBracketKeyword_1_0_5_0_2__(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_AnnotatedStatement_FullStopKeyword_1_1_3_1_or___LeftCurlyBracketKeyword_1_1_3_0_0_RightCurlyBracketKeyword_1_1_3_0_2__.equals(syntax))
				emit_AnnotatedStatement_FullStopKeyword_1_1_3_1_or___LeftCurlyBracketKeyword_1_1_3_0_0_RightCurlyBracketKeyword_1_1_3_0_2__(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_AnnotatedStatement_SemicolonKeyword_1_0_5_0_1_1_q.equals(syntax))
				emit_AnnotatedStatement_SemicolonKeyword_1_0_5_0_1_1_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_AnnotatedStatement___CommaKeyword_1_1_3_0_1_2_0_or_SemicolonKeyword_1_1_3_0_1_2_1__q.equals(syntax))
				emit_AnnotatedStatement___CommaKeyword_1_1_3_0_1_2_0_or_SemicolonKeyword_1_1_3_0_1_2_1__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Annotation___LeftParenthesisKeyword_2_0_RightParenthesisKeyword_2_2__q.equals(syntax))
				emit_Annotation___LeftParenthesisKeyword_2_0_RightParenthesisKeyword_2_2__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_UnaryExpr_LeftParenthesisKeyword_7_0_a.equals(syntax))
				emit_UnaryExpr_LeftParenthesisKeyword_7_0_a(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_UnaryExpr_LeftParenthesisKeyword_7_0_p.equals(syntax))
				emit_UnaryExpr_LeftParenthesisKeyword_7_0_p(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     'declare'?
	 *
	 * This ambiguous syntax occurs at:
	 *     {NodeDeclaration.annotations=} (ambiguity) kind=NodeKind
	 
	 * </pre>
	 */
	protected void emit_AnnotatedStatement_DeclareKeyword_1_9_1_1_0_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     ('{' '}') | '.'
	 *
	 * This ambiguous syntax occurs at:
	 *     name=Identifier (ambiguity) (rule end)
	 *     superTypes+=[Relation|QualifiedName] (ambiguity) (rule end)
	 
	 * </pre>
	 */
	protected void emit_AnnotatedStatement_FullStopKeyword_1_0_5_1_or___LeftCurlyBracketKeyword_1_0_5_0_0_RightCurlyBracketKeyword_1_0_5_0_2__(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     ('{' '}') | '.'
	 *
	 * This ambiguous syntax occurs at:
	 *     name=Identifier (ambiguity) (rule end)
	 
	 * </pre>
	 */
	protected void emit_AnnotatedStatement_FullStopKeyword_1_1_3_1_or___LeftCurlyBracketKeyword_1_1_3_0_0_RightCurlyBracketKeyword_1_1_3_0_2__(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     ';'?
	 *
	 * This ambiguous syntax occurs at:
	 *     featureDeclarations+=ReferenceDeclaration (ambiguity) '}' (rule end)
	 *     featureDeclarations+=ReferenceDeclaration (ambiguity) featureDeclarations+=ReferenceDeclaration
	 
	 * </pre>
	 */
	protected void emit_AnnotatedStatement_SemicolonKeyword_1_0_5_0_1_1_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     (',' | ';')?
	 *
	 * This ambiguous syntax occurs at:
	 *     literals+=EnumLiteral (ambiguity) '}' (rule end)
	 
	 * </pre>
	 */
	protected void emit_AnnotatedStatement___CommaKeyword_1_1_3_0_1_2_0_or_SemicolonKeyword_1_1_3_0_1_2_1__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     ('(' ')')?
	 *
	 * This ambiguous syntax occurs at:
	 *     declaration=[AnnotationDeclaration|QualifiedName] (ambiguity) (rule end)
	 
	 * </pre>
	 */
	protected void emit_Annotation___LeftParenthesisKeyword_2_0_RightParenthesisKeyword_2_2__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     '('*
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) '!' body=UnaryExpr
	 *     (rule start) (ambiguity) '*' (rule start)
	 *     (rule start) (ambiguity) aggregator=[AggregatorDeclaration|QualifiedName]
	 *     (rule start) (ambiguity) concreteness=Concreteness
	 *     (rule start) (ambiguity) element=[NamedElement|QualifiedName]
	 *     (rule start) (ambiguity) intValue=Integer
	 *     (rule start) (ambiguity) logicValue=LogicValue
	 *     (rule start) (ambiguity) modality=Modality
	 *     (rule start) (ambiguity) op=UnaryOp
	 *     (rule start) (ambiguity) realValue=Real
	 *     (rule start) (ambiguity) relation=[Relation|QualifiedName]
	 *     (rule start) (ambiguity) stringValue=STRING
	 *     (rule start) (ambiguity) {ArithmeticBinaryExpr.left=}
	 *     (rule start) (ambiguity) {AssignmentExpr.left=}
	 *     (rule start) (ambiguity) {ComparisonExpr.left=}
	 *     (rule start) (ambiguity) {LatticeBinaryExpr.left=}
	 *     (rule start) (ambiguity) {RangeExpr.left=}
	 
	 * </pre>
	 */
	protected void emit_UnaryExpr_LeftParenthesisKeyword_7_0_a(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     '('+
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) {ArithmeticBinaryExpr.left=}
	 *     (rule start) (ambiguity) {AssignmentExpr.left=}
	 *     (rule start) (ambiguity) {ComparisonExpr.left=}
	 *     (rule start) (ambiguity) {LatticeBinaryExpr.left=}
	 *     (rule start) (ambiguity) {RangeExpr.left=}
	 
	 * </pre>
	 */
	protected void emit_UnaryExpr_LeftParenthesisKeyword_7_0_p(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
