/*
 * generated by Xtext 2.42.0
 */
package tools.refinery.language.serializer;

import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;
import tools.refinery.language.model.problem.AggregationExpr;
import tools.refinery.language.model.problem.AggregatorDeclaration;
import tools.refinery.language.model.problem.Annotation;
import tools.refinery.language.model.problem.AnnotationArgument;
import tools.refinery.language.model.problem.AnnotationContainer;
import tools.refinery.language.model.problem.AnnotationDeclaration;
import tools.refinery.language.model.problem.ArithmeticBinaryExpr;
import tools.refinery.language.model.problem.ArithmeticUnaryExpr;
import tools.refinery.language.model.problem.Assertion;
import tools.refinery.language.model.problem.AssertionAction;
import tools.refinery.language.model.problem.AssignmentExpr;
import tools.refinery.language.model.problem.Atom;
import tools.refinery.language.model.problem.Case;
import tools.refinery.language.model.problem.ClassDeclaration;
import tools.refinery.language.model.problem.ComparisonExpr;
import tools.refinery.language.model.problem.Conjunction;
import tools.refinery.language.model.problem.Consequent;
import tools.refinery.language.model.problem.DatatypeDeclaration;
import tools.refinery.language.model.problem.EnumDeclaration;
import tools.refinery.language.model.problem.ExactMultiplicity;
import tools.refinery.language.model.problem.FunctionDefinition;
import tools.refinery.language.model.problem.ImportStatement;
import tools.refinery.language.model.problem.InfiniteConstant;
import tools.refinery.language.model.problem.IntConstant;
import tools.refinery.language.model.problem.LatticeBinaryExpr;
import tools.refinery.language.model.problem.LogicConstant;
import tools.refinery.language.model.problem.ModalExpr;
import tools.refinery.language.model.problem.NegationExpr;
import tools.refinery.language.model.problem.Node;
import tools.refinery.language.model.problem.NodeAssertionArgument;
import tools.refinery.language.model.problem.NodeDeclaration;
import tools.refinery.language.model.problem.OverloadedDeclaration;
import tools.refinery.language.model.problem.PredicateDefinition;
import tools.refinery.language.model.problem.Problem;
import tools.refinery.language.model.problem.ProblemPackage;
import tools.refinery.language.model.problem.RangeExpr;
import tools.refinery.language.model.problem.RangeMultiplicity;
import tools.refinery.language.model.problem.RealConstant;
import tools.refinery.language.model.problem.ReferenceDeclaration;
import tools.refinery.language.model.problem.RuleDefinition;
import tools.refinery.language.model.problem.ScopeDeclaration;
import tools.refinery.language.model.problem.StringConstant;
import tools.refinery.language.model.problem.TheoryAction;
import tools.refinery.language.model.problem.TopLevelAnnotation;
import tools.refinery.language.model.problem.TypeScope;
import tools.refinery.language.model.problem.UnboundedMultiplicity;
import tools.refinery.language.model.problem.VariableOrNodeExpr;
import tools.refinery.language.model.problem.WildcardAssertionArgument;
import tools.refinery.language.services.ProblemGrammarAccess;

@SuppressWarnings("all")
public class ProblemSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private ProblemGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == ProblemPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case ProblemPackage.AGGREGATION_EXPR:
				sequence_AggregationExpr(context, (AggregationExpr) semanticObject); 
				return; 
			case ProblemPackage.AGGREGATOR_DECLARATION:
				sequence_AnnotatedStatement(context, (AggregatorDeclaration) semanticObject); 
				return; 
			case ProblemPackage.ANNOTATION:
				sequence_Annotation(context, (Annotation) semanticObject); 
				return; 
			case ProblemPackage.ANNOTATION_ARGUMENT:
				sequence_AnnotationArgument(context, (AnnotationArgument) semanticObject); 
				return; 
			case ProblemPackage.ANNOTATION_CONTAINER:
				sequence_AnnotationContainer(context, (AnnotationContainer) semanticObject); 
				return; 
			case ProblemPackage.ANNOTATION_DECLARATION:
				sequence_AnnotatedStatement(context, (AnnotationDeclaration) semanticObject); 
				return; 
			case ProblemPackage.ARITHMETIC_BINARY_EXPR:
				sequence_AdditiveExpr_BooleanExpr_ExponentialExpr_MultiplicativeExpr(context, (ArithmeticBinaryExpr) semanticObject); 
				return; 
			case ProblemPackage.ARITHMETIC_UNARY_EXPR:
				sequence_ArithmeticUnaryExpr(context, (ArithmeticUnaryExpr) semanticObject); 
				return; 
			case ProblemPackage.ASSERTION:
				sequence_Assertion(context, (Assertion) semanticObject); 
				return; 
			case ProblemPackage.ASSERTION_ACTION:
				sequence_AssertionAction(context, (AssertionAction) semanticObject); 
				return; 
			case ProblemPackage.ASSIGNMENT_EXPR:
				sequence_AssignmentExpr(context, (AssignmentExpr) semanticObject); 
				return; 
			case ProblemPackage.ATOM:
				sequence_Atom(context, (Atom) semanticObject); 
				return; 
			case ProblemPackage.CASE:
				sequence_Case(context, (Case) semanticObject); 
				return; 
			case ProblemPackage.CLASS_DECLARATION:
				sequence_AnnotatedStatement(context, (ClassDeclaration) semanticObject); 
				return; 
			case ProblemPackage.COMPARISON_EXPR:
				sequence_ComparisonExpr(context, (ComparisonExpr) semanticObject); 
				return; 
			case ProblemPackage.CONJUNCTION:
				sequence_Conjunction(context, (Conjunction) semanticObject); 
				return; 
			case ProblemPackage.CONSEQUENT:
				sequence_Consequent(context, (Consequent) semanticObject); 
				return; 
			case ProblemPackage.DATATYPE_DECLARATION:
				sequence_AnnotatedStatement(context, (DatatypeDeclaration) semanticObject); 
				return; 
			case ProblemPackage.ENUM_DECLARATION:
				sequence_AnnotatedStatement(context, (EnumDeclaration) semanticObject); 
				return; 
			case ProblemPackage.EXACT_MULTIPLICITY:
				sequence_ExactMultiplicity(context, (ExactMultiplicity) semanticObject); 
				return; 
			case ProblemPackage.FUNCTION_DEFINITION:
				sequence_AnnotatedStatement(context, (FunctionDefinition) semanticObject); 
				return; 
			case ProblemPackage.IMPORT_STATEMENT:
				sequence_ImportStatement(context, (ImportStatement) semanticObject); 
				return; 
			case ProblemPackage.INFINITE_CONSTANT:
				sequence_InfiniteConstant(context, (InfiniteConstant) semanticObject); 
				return; 
			case ProblemPackage.INT_CONSTANT:
				sequence_IntConstant(context, (IntConstant) semanticObject); 
				return; 
			case ProblemPackage.LATTICE_BINARY_EXPR:
				sequence_ComparisonExpr_LatticeExpr(context, (LatticeBinaryExpr) semanticObject); 
				return; 
			case ProblemPackage.LOGIC_CONSTANT:
				if (rule == grammarAccess.getExprRule()
						|| rule == grammarAccess.getAssignmentExprRule()
						|| action == grammarAccess.getAssignmentExprAccess().getAssignmentExprLeftAction_1_0()
						|| rule == grammarAccess.getBooleanExprRule()
						|| action == grammarAccess.getBooleanExprAccess().getArithmeticBinaryExprLeftAction_1_0()
						|| rule == grammarAccess.getComparisonExprRule()
						|| action == grammarAccess.getComparisonExprAccess().getComparisonExprLeftAction_1_0_0()
						|| action == grammarAccess.getComparisonExprAccess().getLatticeBinaryExprLeftAction_1_1_0()
						|| rule == grammarAccess.getLatticeExprRule()
						|| action == grammarAccess.getLatticeExprAccess().getLatticeBinaryExprLeftAction_1_0()
						|| rule == grammarAccess.getAdditiveExprRule()
						|| action == grammarAccess.getAdditiveExprAccess().getArithmeticBinaryExprLeftAction_1_0()
						|| rule == grammarAccess.getMultiplicativeExprRule()
						|| action == grammarAccess.getMultiplicativeExprAccess().getArithmeticBinaryExprLeftAction_1_0()
						|| rule == grammarAccess.getExponentialExprRule()
						|| action == grammarAccess.getExponentialExprAccess().getArithmeticBinaryExprLeftAction_1_0()
						|| rule == grammarAccess.getRangeExprRule()
						|| action == grammarAccess.getRangeExprAccess().getRangeExprLeftAction_1_0()
						|| rule == grammarAccess.getUnaryExprRule()
						|| rule == grammarAccess.getConstantRule()
						|| rule == grammarAccess.getLogicConstantRule()) {
					sequence_LogicConstant(context, (LogicConstant) semanticObject); 
					return; 
				}
				else if (rule == grammarAccess.getShortLogicConstantRule()) {
					sequence_ShortLogicConstant(context, (LogicConstant) semanticObject); 
					return; 
				}
				else break;
			case ProblemPackage.MODAL_EXPR:
				sequence_ModalExpr(context, (ModalExpr) semanticObject); 
				return; 
			case ProblemPackage.NEGATION_EXPR:
				sequence_NegationExpr(context, (NegationExpr) semanticObject); 
				return; 
			case ProblemPackage.NODE:
				sequence_EnumLiteral(context, (Node) semanticObject); 
				return; 
			case ProblemPackage.NODE_ASSERTION_ARGUMENT:
				sequence_NodeAssertionArgument(context, (NodeAssertionArgument) semanticObject); 
				return; 
			case ProblemPackage.NODE_DECLARATION:
				sequence_AnnotatedStatement(context, (NodeDeclaration) semanticObject); 
				return; 
			case ProblemPackage.OVERLOADED_DECLARATION:
				sequence_AnnotatedStatement(context, (OverloadedDeclaration) semanticObject); 
				return; 
			case ProblemPackage.PARAMETER:
				sequence_Parameter(context, (tools.refinery.language.model.problem.Parameter) semanticObject); 
				return; 
			case ProblemPackage.PREDICATE_DEFINITION:
				sequence_AnnotatedStatement(context, (PredicateDefinition) semanticObject); 
				return; 
			case ProblemPackage.PROBLEM:
				sequence_Problem(context, (Problem) semanticObject); 
				return; 
			case ProblemPackage.RANGE_EXPR:
				sequence_RangeExpr(context, (RangeExpr) semanticObject); 
				return; 
			case ProblemPackage.RANGE_MULTIPLICITY:
				sequence_RangeMultiplicity(context, (RangeMultiplicity) semanticObject); 
				return; 
			case ProblemPackage.REAL_CONSTANT:
				sequence_RealConstant(context, (RealConstant) semanticObject); 
				return; 
			case ProblemPackage.REFERENCE_DECLARATION:
				sequence_ReferenceDeclaration(context, (ReferenceDeclaration) semanticObject); 
				return; 
			case ProblemPackage.RULE_DEFINITION:
				sequence_AnnotatedStatement(context, (RuleDefinition) semanticObject); 
				return; 
			case ProblemPackage.SCOPE_DECLARATION:
				sequence_ScopeDeclaration(context, (ScopeDeclaration) semanticObject); 
				return; 
			case ProblemPackage.STRING_CONSTANT:
				sequence_StringConstant(context, (StringConstant) semanticObject); 
				return; 
			case ProblemPackage.THEORY_ACTION:
				sequence_TheoryAction(context, (TheoryAction) semanticObject); 
				return; 
			case ProblemPackage.TOP_LEVEL_ANNOTATION:
				sequence_TopLevelAnnotation(context, (TopLevelAnnotation) semanticObject); 
				return; 
			case ProblemPackage.TYPE_SCOPE:
				sequence_TypeScope(context, (TypeScope) semanticObject); 
				return; 
			case ProblemPackage.UNBOUNDED_MULTIPLICITY:
				sequence_UnboundedMultiplicity(context, (UnboundedMultiplicity) semanticObject); 
				return; 
			case ProblemPackage.VARIABLE_OR_NODE_EXPR:
				sequence_VariableOrNodeExpr(context, (VariableOrNodeExpr) semanticObject); 
				return; 
			case ProblemPackage.WILDCARD_ASSERTION_ARGUMENT:
				sequence_WildcardAssertionArgument(context, (WildcardAssertionArgument) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * <pre>
	 * Contexts:
	 *     Expr returns ArithmeticBinaryExpr
	 *     AssignmentExpr returns ArithmeticBinaryExpr
	 *     AssignmentExpr.AssignmentExpr_1_0 returns ArithmeticBinaryExpr
	 *     BooleanExpr returns ArithmeticBinaryExpr
	 *     BooleanExpr.ArithmeticBinaryExpr_1_0 returns ArithmeticBinaryExpr
	 *     ComparisonExpr returns ArithmeticBinaryExpr
	 *     ComparisonExpr.ComparisonExpr_1_0_0 returns ArithmeticBinaryExpr
	 *     ComparisonExpr.LatticeBinaryExpr_1_1_0 returns ArithmeticBinaryExpr
	 *     LatticeExpr returns ArithmeticBinaryExpr
	 *     LatticeExpr.LatticeBinaryExpr_1_0 returns ArithmeticBinaryExpr
	 *     AdditiveExpr returns ArithmeticBinaryExpr
	 *     AdditiveExpr.ArithmeticBinaryExpr_1_0 returns ArithmeticBinaryExpr
	 *     MultiplicativeExpr returns ArithmeticBinaryExpr
	 *     MultiplicativeExpr.ArithmeticBinaryExpr_1_0 returns ArithmeticBinaryExpr
	 *     ExponentialExpr returns ArithmeticBinaryExpr
	 *     ExponentialExpr.ArithmeticBinaryExpr_1_0 returns ArithmeticBinaryExpr
	 *     RangeExpr returns ArithmeticBinaryExpr
	 *     RangeExpr.RangeExpr_1_0 returns ArithmeticBinaryExpr
	 *     UnaryExpr returns ArithmeticBinaryExpr
	 *
	 * Constraint:
	 *     (
	 *         (left=BooleanExpr_ArithmeticBinaryExpr_1_0 op=BooleanBinaryOp right=ComparisonExpr) | 
	 *         (left=AdditiveExpr_ArithmeticBinaryExpr_1_0 op=AdditiveOp right=MultiplicativeExpr) | 
	 *         (left=MultiplicativeExpr_ArithmeticBinaryExpr_1_0 op=MultiplicativeOp right=ExponentialExpr) | 
	 *         (left=ExponentialExpr_ArithmeticBinaryExpr_1_0 op=ExponentialOp right=ExponentialExpr)
	 *     )
	 * </pre>
	 */
	protected void sequence_AdditiveExpr_BooleanExpr_ExponentialExpr_MultiplicativeExpr(ISerializationContext context, ArithmeticBinaryExpr semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Expr returns AggregationExpr
	 *     AssignmentExpr returns AggregationExpr
	 *     AssignmentExpr.AssignmentExpr_1_0 returns AggregationExpr
	 *     BooleanExpr returns AggregationExpr
	 *     BooleanExpr.ArithmeticBinaryExpr_1_0 returns AggregationExpr
	 *     ComparisonExpr returns AggregationExpr
	 *     ComparisonExpr.ComparisonExpr_1_0_0 returns AggregationExpr
	 *     ComparisonExpr.LatticeBinaryExpr_1_1_0 returns AggregationExpr
	 *     LatticeExpr returns AggregationExpr
	 *     LatticeExpr.LatticeBinaryExpr_1_0 returns AggregationExpr
	 *     AdditiveExpr returns AggregationExpr
	 *     AdditiveExpr.ArithmeticBinaryExpr_1_0 returns AggregationExpr
	 *     MultiplicativeExpr returns AggregationExpr
	 *     MultiplicativeExpr.ArithmeticBinaryExpr_1_0 returns AggregationExpr
	 *     ExponentialExpr returns AggregationExpr
	 *     ExponentialExpr.ArithmeticBinaryExpr_1_0 returns AggregationExpr
	 *     RangeExpr returns AggregationExpr
	 *     RangeExpr.RangeExpr_1_0 returns AggregationExpr
	 *     UnaryExpr returns AggregationExpr
	 *     AggregationExpr returns AggregationExpr
	 *
	 * Constraint:
	 *     (aggregator=[AggregatorDeclaration|QualifiedName] condition=Expr value=Expr?)
	 * </pre>
	 */
	protected void sequence_AggregationExpr(ISerializationContext context, AggregationExpr semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Statement returns AggregatorDeclaration
	 *     AnnotatedStatement returns AggregatorDeclaration
	 *
	 * Constraint:
	 *     (annotations=AnnotatedStatement_AggregatorDeclaration_1_3_0 name=Identifier)
	 * </pre>
	 */
	protected void sequence_AnnotatedStatement(ISerializationContext context, AggregatorDeclaration semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, ProblemPackage.Literals.ANNOTATED_ELEMENT__ANNOTATIONS) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ProblemPackage.Literals.ANNOTATED_ELEMENT__ANNOTATIONS));
			if (transientValues.isValueTransient(semanticObject, ProblemPackage.Literals.NAMED_ELEMENT__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ProblemPackage.Literals.NAMED_ELEMENT__NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getAnnotatedStatementAccess().getAggregatorDeclarationAnnotationsAction_1_3_0(), semanticObject.getAnnotations());
		feeder.accept(grammarAccess.getAnnotatedStatementAccess().getNameIdentifierParserRuleCall_1_3_3_0(), semanticObject.getName());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Statement returns AnnotationDeclaration
	 *     AnnotatedStatement returns AnnotationDeclaration
	 *
	 * Constraint:
	 *     (annotations=AnnotatedStatement_AnnotationDeclaration_1_8_0 name=Identifier (parameters+=Parameter parameters+=Parameter*)?)
	 * </pre>
	 */
	protected void sequence_AnnotatedStatement(ISerializationContext context, AnnotationDeclaration semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Statement returns ClassDeclaration
	 *     AnnotatedStatement returns ClassDeclaration
	 *
	 * Constraint:
	 *     (
	 *         annotations=AnnotatedStatement_ClassDeclaration_1_0_0 
	 *         abstract?='abstract'? 
	 *         name=Identifier 
	 *         (superTypes+=[Relation|QualifiedName] superTypes+=[Relation|QualifiedName]*)? 
	 *         featureDeclarations+=ReferenceDeclaration*
	 *     )
	 * </pre>
	 */
	protected void sequence_AnnotatedStatement(ISerializationContext context, ClassDeclaration semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Statement returns DatatypeDeclaration
	 *     AnnotatedStatement returns DatatypeDeclaration
	 *
	 * Constraint:
	 *     (annotations=AnnotatedStatement_DatatypeDeclaration_1_2_0 name=Identifier)
	 * </pre>
	 */
	protected void sequence_AnnotatedStatement(ISerializationContext context, DatatypeDeclaration semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, ProblemPackage.Literals.ANNOTATED_ELEMENT__ANNOTATIONS) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ProblemPackage.Literals.ANNOTATED_ELEMENT__ANNOTATIONS));
			if (transientValues.isValueTransient(semanticObject, ProblemPackage.Literals.NAMED_ELEMENT__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ProblemPackage.Literals.NAMED_ELEMENT__NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getAnnotatedStatementAccess().getDatatypeDeclarationAnnotationsAction_1_2_0(), semanticObject.getAnnotations());
		feeder.accept(grammarAccess.getAnnotatedStatementAccess().getNameIdentifierParserRuleCall_1_2_3_0(), semanticObject.getName());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Statement returns EnumDeclaration
	 *     AnnotatedStatement returns EnumDeclaration
	 *
	 * Constraint:
	 *     (annotations=AnnotatedStatement_EnumDeclaration_1_1_0 name=Identifier (literals+=EnumLiteral literals+=EnumLiteral*)?)
	 * </pre>
	 */
	protected void sequence_AnnotatedStatement(ISerializationContext context, EnumDeclaration semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Statement returns FunctionDefinition
	 *     AnnotatedStatement returns FunctionDefinition
	 *
	 * Constraint:
	 *     (
	 *         annotations=AnnotatedStatement_FunctionDefinition_1_6_0 
	 *         shadow?='shadow'? 
	 *         functionType=[Relation|QualifiedName] 
	 *         name=Identifier 
	 *         (parameters+=Parameter parameters+=Parameter*)? 
	 *         (cases+=Case cases+=Case*)?
	 *     )
	 * </pre>
	 */
	protected void sequence_AnnotatedStatement(ISerializationContext context, FunctionDefinition semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Statement returns NodeDeclaration
	 *     AnnotatedStatement returns NodeDeclaration
	 *
	 * Constraint:
	 *     (annotations=AnnotatedStatement_NodeDeclaration_1_9_0 kind=NodeKind? nodes+=EnumLiteral nodes+=EnumLiteral*)
	 * </pre>
	 */
	protected void sequence_AnnotatedStatement(ISerializationContext context, NodeDeclaration semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Statement returns OverloadedDeclaration
	 *     AnnotatedStatement returns OverloadedDeclaration
	 *
	 * Constraint:
	 *     (annotations=AnnotatedStatement_OverloadedDeclaration_1_4_0 shadow?='shadow'? name=Identifier (parameters+=Parameter parameters+=Parameter*)?)
	 * </pre>
	 */
	protected void sequence_AnnotatedStatement(ISerializationContext context, OverloadedDeclaration semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Statement returns PredicateDefinition
	 *     AnnotatedStatement returns PredicateDefinition
	 *
	 * Constraint:
	 *     (
	 *         annotations=AnnotatedStatement_PredicateDefinition_1_5_0 
	 *         (kind=ErrorPredicateKind | kind=PredicateKind)? 
	 *         name=Identifier 
	 *         (parameters+=Parameter parameters+=Parameter*)? 
	 *         (superSets+=[ReferenceDeclaration|QualifiedName] superSets+=[ReferenceDeclaration|QualifiedName]*)? 
	 *         (bodies+=Conjunction bodies+=Conjunction*)?
	 *     )
	 * </pre>
	 */
	protected void sequence_AnnotatedStatement(ISerializationContext context, PredicateDefinition semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Statement returns RuleDefinition
	 *     AnnotatedStatement returns RuleDefinition
	 *
	 * Constraint:
	 *     (
	 *         annotations=AnnotatedStatement_RuleDefinition_1_7_0 
	 *         kind=RuleKind? 
	 *         name=Identifier 
	 *         (parameters+=Parameter parameters+=Parameter*)? 
	 *         (preconditions+=Conjunction preconditions+=Conjunction*)? 
	 *         (consequents+=Consequent consequents+=Consequent*)?
	 *     )
	 * </pre>
	 */
	protected void sequence_AnnotatedStatement(ISerializationContext context, RuleDefinition semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     AnnotationArgument returns AnnotationArgument
	 *
	 * Constraint:
	 *     (parameter=[Parameter|Identifier]? value=Expr)
	 * </pre>
	 */
	protected void sequence_AnnotationArgument(ISerializationContext context, AnnotationArgument semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     AnnotatedStatement.ClassDeclaration_1_0_0 returns AnnotationContainer
	 *     AnnotatedStatement.EnumDeclaration_1_1_0 returns AnnotationContainer
	 *     AnnotatedStatement.DatatypeDeclaration_1_2_0 returns AnnotationContainer
	 *     AnnotatedStatement.AggregatorDeclaration_1_3_0 returns AnnotationContainer
	 *     AnnotatedStatement.OverloadedDeclaration_1_4_0 returns AnnotationContainer
	 *     AnnotatedStatement.PredicateDefinition_1_5_0 returns AnnotationContainer
	 *     AnnotatedStatement.FunctionDefinition_1_6_0 returns AnnotationContainer
	 *     AnnotatedStatement.RuleDefinition_1_7_0 returns AnnotationContainer
	 *     AnnotatedStatement.AnnotationDeclaration_1_8_0 returns AnnotationContainer
	 *     AnnotatedStatement.NodeDeclaration_1_9_0 returns AnnotationContainer
	 *     AnnotationContainer returns AnnotationContainer
	 *
	 * Constraint:
	 *     annotations+=Annotation*
	 * </pre>
	 */
	protected void sequence_AnnotationContainer(ISerializationContext context, AnnotationContainer semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Annotation returns Annotation
	 *
	 * Constraint:
	 *     (declaration=[AnnotationDeclaration|QualifiedName] (arguments+=AnnotationArgument arguments+=AnnotationArgument*)?)
	 * </pre>
	 */
	protected void sequence_Annotation(ISerializationContext context, Annotation semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Expr returns ArithmeticUnaryExpr
	 *     AssignmentExpr returns ArithmeticUnaryExpr
	 *     AssignmentExpr.AssignmentExpr_1_0 returns ArithmeticUnaryExpr
	 *     BooleanExpr returns ArithmeticUnaryExpr
	 *     BooleanExpr.ArithmeticBinaryExpr_1_0 returns ArithmeticUnaryExpr
	 *     ComparisonExpr returns ArithmeticUnaryExpr
	 *     ComparisonExpr.ComparisonExpr_1_0_0 returns ArithmeticUnaryExpr
	 *     ComparisonExpr.LatticeBinaryExpr_1_1_0 returns ArithmeticUnaryExpr
	 *     LatticeExpr returns ArithmeticUnaryExpr
	 *     LatticeExpr.LatticeBinaryExpr_1_0 returns ArithmeticUnaryExpr
	 *     AdditiveExpr returns ArithmeticUnaryExpr
	 *     AdditiveExpr.ArithmeticBinaryExpr_1_0 returns ArithmeticUnaryExpr
	 *     MultiplicativeExpr returns ArithmeticUnaryExpr
	 *     MultiplicativeExpr.ArithmeticBinaryExpr_1_0 returns ArithmeticUnaryExpr
	 *     ExponentialExpr returns ArithmeticUnaryExpr
	 *     ExponentialExpr.ArithmeticBinaryExpr_1_0 returns ArithmeticUnaryExpr
	 *     RangeExpr returns ArithmeticUnaryExpr
	 *     RangeExpr.RangeExpr_1_0 returns ArithmeticUnaryExpr
	 *     UnaryExpr returns ArithmeticUnaryExpr
	 *     ArithmeticUnaryExpr returns ArithmeticUnaryExpr
	 *
	 * Constraint:
	 *     (op=UnaryOp body=UnaryExpr)
	 * </pre>
	 */
	protected void sequence_ArithmeticUnaryExpr(ISerializationContext context, ArithmeticUnaryExpr semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, ProblemPackage.Literals.ARITHMETIC_UNARY_EXPR__OP) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ProblemPackage.Literals.ARITHMETIC_UNARY_EXPR__OP));
			if (transientValues.isValueTransient(semanticObject, ProblemPackage.Literals.UNARY_EXPR__BODY) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ProblemPackage.Literals.UNARY_EXPR__BODY));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getArithmeticUnaryExprAccess().getOpUnaryOpEnumRuleCall_0_0(), semanticObject.getOp());
		feeder.accept(grammarAccess.getArithmeticUnaryExprAccess().getBodyUnaryExprParserRuleCall_1_0(), semanticObject.getBody());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Action returns AssertionAction
	 *     AssertionAction returns AssertionAction
	 *
	 * Constraint:
	 *     (
	 *         (relation=[Relation|QualifiedName] (arguments+=AssertionArgument arguments+=AssertionArgument*)? value=Expr) | 
	 *         (value=ShortLogicConstant relation=[Relation|QualifiedName] (arguments+=AssertionArgument arguments+=AssertionArgument*)?)
	 *     )
	 * </pre>
	 */
	protected void sequence_AssertionAction(ISerializationContext context, AssertionAction semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Statement returns Assertion
	 *     Assertion returns Assertion
	 *
	 * Constraint:
	 *     (
	 *         default?='default'? 
	 *         (
	 *             (relation=[Relation|QualifiedName] (arguments+=AssertionArgument arguments+=AssertionArgument*)? value=Expr) | 
	 *             (value=ShortLogicConstant relation=[Relation|QualifiedName] (arguments+=AssertionArgument arguments+=AssertionArgument*)?)
	 *         )
	 *     )
	 * </pre>
	 */
	protected void sequence_Assertion(ISerializationContext context, Assertion semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Expr returns AssignmentExpr
	 *     AssignmentExpr returns AssignmentExpr
	 *     AssignmentExpr.AssignmentExpr_1_0 returns AssignmentExpr
	 *     BooleanExpr returns AssignmentExpr
	 *     BooleanExpr.ArithmeticBinaryExpr_1_0 returns AssignmentExpr
	 *     ComparisonExpr returns AssignmentExpr
	 *     ComparisonExpr.ComparisonExpr_1_0_0 returns AssignmentExpr
	 *     ComparisonExpr.LatticeBinaryExpr_1_1_0 returns AssignmentExpr
	 *     LatticeExpr returns AssignmentExpr
	 *     LatticeExpr.LatticeBinaryExpr_1_0 returns AssignmentExpr
	 *     AdditiveExpr returns AssignmentExpr
	 *     AdditiveExpr.ArithmeticBinaryExpr_1_0 returns AssignmentExpr
	 *     MultiplicativeExpr returns AssignmentExpr
	 *     MultiplicativeExpr.ArithmeticBinaryExpr_1_0 returns AssignmentExpr
	 *     ExponentialExpr returns AssignmentExpr
	 *     ExponentialExpr.ArithmeticBinaryExpr_1_0 returns AssignmentExpr
	 *     RangeExpr returns AssignmentExpr
	 *     RangeExpr.RangeExpr_1_0 returns AssignmentExpr
	 *     UnaryExpr returns AssignmentExpr
	 *
	 * Constraint:
	 *     (left=AssignmentExpr_AssignmentExpr_1_0 right=BooleanExpr)
	 * </pre>
	 */
	protected void sequence_AssignmentExpr(ISerializationContext context, AssignmentExpr semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, ProblemPackage.Literals.BINARY_EXPR__LEFT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ProblemPackage.Literals.BINARY_EXPR__LEFT));
			if (transientValues.isValueTransient(semanticObject, ProblemPackage.Literals.BINARY_EXPR__RIGHT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ProblemPackage.Literals.BINARY_EXPR__RIGHT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getAssignmentExprAccess().getAssignmentExprLeftAction_1_0(), semanticObject.getLeft());
		feeder.accept(grammarAccess.getAssignmentExprAccess().getRightBooleanExprParserRuleCall_1_2_0(), semanticObject.getRight());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Expr returns Atom
	 *     AssignmentExpr returns Atom
	 *     AssignmentExpr.AssignmentExpr_1_0 returns Atom
	 *     BooleanExpr returns Atom
	 *     BooleanExpr.ArithmeticBinaryExpr_1_0 returns Atom
	 *     ComparisonExpr returns Atom
	 *     ComparisonExpr.ComparisonExpr_1_0_0 returns Atom
	 *     ComparisonExpr.LatticeBinaryExpr_1_1_0 returns Atom
	 *     LatticeExpr returns Atom
	 *     LatticeExpr.LatticeBinaryExpr_1_0 returns Atom
	 *     AdditiveExpr returns Atom
	 *     AdditiveExpr.ArithmeticBinaryExpr_1_0 returns Atom
	 *     MultiplicativeExpr returns Atom
	 *     MultiplicativeExpr.ArithmeticBinaryExpr_1_0 returns Atom
	 *     ExponentialExpr returns Atom
	 *     ExponentialExpr.ArithmeticBinaryExpr_1_0 returns Atom
	 *     RangeExpr returns Atom
	 *     RangeExpr.RangeExpr_1_0 returns Atom
	 *     UnaryExpr returns Atom
	 *     Atom returns Atom
	 *
	 * Constraint:
	 *     (relation=[Relation|QualifiedName] transitiveClosure?=TRANSITIVE_CLOSURE? (arguments+=Expr arguments+=Expr*)?)
	 * </pre>
	 */
	protected void sequence_Atom(ISerializationContext context, Atom semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Case returns Case
	 *
	 * Constraint:
	 *     (condition=Conjunction value=Expr?)
	 * </pre>
	 */
	protected void sequence_Case(ISerializationContext context, Case semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Expr returns ComparisonExpr
	 *     AssignmentExpr returns ComparisonExpr
	 *     AssignmentExpr.AssignmentExpr_1_0 returns ComparisonExpr
	 *     BooleanExpr returns ComparisonExpr
	 *     BooleanExpr.ArithmeticBinaryExpr_1_0 returns ComparisonExpr
	 *     ComparisonExpr returns ComparisonExpr
	 *     ComparisonExpr.ComparisonExpr_1_0_0 returns ComparisonExpr
	 *     ComparisonExpr.LatticeBinaryExpr_1_1_0 returns ComparisonExpr
	 *     LatticeExpr returns ComparisonExpr
	 *     LatticeExpr.LatticeBinaryExpr_1_0 returns ComparisonExpr
	 *     AdditiveExpr returns ComparisonExpr
	 *     AdditiveExpr.ArithmeticBinaryExpr_1_0 returns ComparisonExpr
	 *     MultiplicativeExpr returns ComparisonExpr
	 *     MultiplicativeExpr.ArithmeticBinaryExpr_1_0 returns ComparisonExpr
	 *     ExponentialExpr returns ComparisonExpr
	 *     ExponentialExpr.ArithmeticBinaryExpr_1_0 returns ComparisonExpr
	 *     RangeExpr returns ComparisonExpr
	 *     RangeExpr.RangeExpr_1_0 returns ComparisonExpr
	 *     UnaryExpr returns ComparisonExpr
	 *
	 * Constraint:
	 *     (left=ComparisonExpr_ComparisonExpr_1_0_0 op=ComparisonOp right=LatticeExpr)
	 * </pre>
	 */
	protected void sequence_ComparisonExpr(ISerializationContext context, ComparisonExpr semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, ProblemPackage.Literals.BINARY_EXPR__LEFT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ProblemPackage.Literals.BINARY_EXPR__LEFT));
			if (transientValues.isValueTransient(semanticObject, ProblemPackage.Literals.COMPARISON_EXPR__OP) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ProblemPackage.Literals.COMPARISON_EXPR__OP));
			if (transientValues.isValueTransient(semanticObject, ProblemPackage.Literals.BINARY_EXPR__RIGHT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ProblemPackage.Literals.BINARY_EXPR__RIGHT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getComparisonExprAccess().getComparisonExprLeftAction_1_0_0(), semanticObject.getLeft());
		feeder.accept(grammarAccess.getComparisonExprAccess().getOpComparisonOpEnumRuleCall_1_0_1_0(), semanticObject.getOp());
		feeder.accept(grammarAccess.getComparisonExprAccess().getRightLatticeExprParserRuleCall_1_0_2_0(), semanticObject.getRight());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Expr returns LatticeBinaryExpr
	 *     AssignmentExpr returns LatticeBinaryExpr
	 *     AssignmentExpr.AssignmentExpr_1_0 returns LatticeBinaryExpr
	 *     BooleanExpr returns LatticeBinaryExpr
	 *     BooleanExpr.ArithmeticBinaryExpr_1_0 returns LatticeBinaryExpr
	 *     ComparisonExpr returns LatticeBinaryExpr
	 *     ComparisonExpr.ComparisonExpr_1_0_0 returns LatticeBinaryExpr
	 *     ComparisonExpr.LatticeBinaryExpr_1_1_0 returns LatticeBinaryExpr
	 *     LatticeExpr returns LatticeBinaryExpr
	 *     LatticeExpr.LatticeBinaryExpr_1_0 returns LatticeBinaryExpr
	 *     AdditiveExpr returns LatticeBinaryExpr
	 *     AdditiveExpr.ArithmeticBinaryExpr_1_0 returns LatticeBinaryExpr
	 *     MultiplicativeExpr returns LatticeBinaryExpr
	 *     MultiplicativeExpr.ArithmeticBinaryExpr_1_0 returns LatticeBinaryExpr
	 *     ExponentialExpr returns LatticeBinaryExpr
	 *     ExponentialExpr.ArithmeticBinaryExpr_1_0 returns LatticeBinaryExpr
	 *     RangeExpr returns LatticeBinaryExpr
	 *     RangeExpr.RangeExpr_1_0 returns LatticeBinaryExpr
	 *     UnaryExpr returns LatticeBinaryExpr
	 *
	 * Constraint:
	 *     (
	 *         (left=ComparisonExpr_LatticeBinaryExpr_1_1_0 op=LatticeComparisonOp right=LatticeExpr) | 
	 *         (left=LatticeExpr_LatticeBinaryExpr_1_0 op=LatticeBinaryOp right=AdditiveExpr)
	 *     )
	 * </pre>
	 */
	protected void sequence_ComparisonExpr_LatticeExpr(ISerializationContext context, LatticeBinaryExpr semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Conjunction returns Conjunction
	 *
	 * Constraint:
	 *     (literals+=Expr literals+=Expr*)
	 * </pre>
	 */
	protected void sequence_Conjunction(ISerializationContext context, Conjunction semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Consequent returns Consequent
	 *
	 * Constraint:
	 *     (actions+=Action actions+=Action*)
	 * </pre>
	 */
	protected void sequence_Consequent(ISerializationContext context, Consequent semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     EnumLiteral returns Node
	 *
	 * Constraint:
	 *     (annotations=AnnotationContainer name=Identifier)
	 * </pre>
	 */
	protected void sequence_EnumLiteral(ISerializationContext context, Node semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, ProblemPackage.Literals.ANNOTATED_ELEMENT__ANNOTATIONS) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ProblemPackage.Literals.ANNOTATED_ELEMENT__ANNOTATIONS));
			if (transientValues.isValueTransient(semanticObject, ProblemPackage.Literals.NAMED_ELEMENT__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ProblemPackage.Literals.NAMED_ELEMENT__NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getEnumLiteralAccess().getAnnotationsAnnotationContainerParserRuleCall_0_0(), semanticObject.getAnnotations());
		feeder.accept(grammarAccess.getEnumLiteralAccess().getNameIdentifierParserRuleCall_1_0(), semanticObject.getName());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     ReferenceMultiplicity returns ExactMultiplicity
	 *     Multiplicity returns ExactMultiplicity
	 *     DefiniteMultiplicity returns ExactMultiplicity
	 *     ExactMultiplicity returns ExactMultiplicity
	 *
	 * Constraint:
	 *     exactValue=INT
	 * </pre>
	 */
	protected void sequence_ExactMultiplicity(ISerializationContext context, ExactMultiplicity semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, ProblemPackage.Literals.EXACT_MULTIPLICITY__EXACT_VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ProblemPackage.Literals.EXACT_MULTIPLICITY__EXACT_VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getExactMultiplicityAccess().getExactValueINTTerminalRuleCall_0(), semanticObject.getExactValue());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Statement returns ImportStatement
	 *     ImportStatement returns ImportStatement
	 *
	 * Constraint:
	 *     (importedModule=[Problem|QualifiedName] alias=ID?)
	 * </pre>
	 */
	protected void sequence_ImportStatement(ISerializationContext context, ImportStatement semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Expr returns InfiniteConstant
	 *     AssignmentExpr returns InfiniteConstant
	 *     AssignmentExpr.AssignmentExpr_1_0 returns InfiniteConstant
	 *     BooleanExpr returns InfiniteConstant
	 *     BooleanExpr.ArithmeticBinaryExpr_1_0 returns InfiniteConstant
	 *     ComparisonExpr returns InfiniteConstant
	 *     ComparisonExpr.ComparisonExpr_1_0_0 returns InfiniteConstant
	 *     ComparisonExpr.LatticeBinaryExpr_1_1_0 returns InfiniteConstant
	 *     LatticeExpr returns InfiniteConstant
	 *     LatticeExpr.LatticeBinaryExpr_1_0 returns InfiniteConstant
	 *     AdditiveExpr returns InfiniteConstant
	 *     AdditiveExpr.ArithmeticBinaryExpr_1_0 returns InfiniteConstant
	 *     MultiplicativeExpr returns InfiniteConstant
	 *     MultiplicativeExpr.ArithmeticBinaryExpr_1_0 returns InfiniteConstant
	 *     ExponentialExpr returns InfiniteConstant
	 *     ExponentialExpr.ArithmeticBinaryExpr_1_0 returns InfiniteConstant
	 *     RangeExpr returns InfiniteConstant
	 *     RangeExpr.RangeExpr_1_0 returns InfiniteConstant
	 *     UnaryExpr returns InfiniteConstant
	 *     Constant returns InfiniteConstant
	 *     InfiniteConstant returns InfiniteConstant
	 *
	 * Constraint:
	 *     {InfiniteConstant}
	 * </pre>
	 */
	protected void sequence_InfiniteConstant(ISerializationContext context, InfiniteConstant semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Expr returns IntConstant
	 *     AssignmentExpr returns IntConstant
	 *     AssignmentExpr.AssignmentExpr_1_0 returns IntConstant
	 *     BooleanExpr returns IntConstant
	 *     BooleanExpr.ArithmeticBinaryExpr_1_0 returns IntConstant
	 *     ComparisonExpr returns IntConstant
	 *     ComparisonExpr.ComparisonExpr_1_0_0 returns IntConstant
	 *     ComparisonExpr.LatticeBinaryExpr_1_1_0 returns IntConstant
	 *     LatticeExpr returns IntConstant
	 *     LatticeExpr.LatticeBinaryExpr_1_0 returns IntConstant
	 *     AdditiveExpr returns IntConstant
	 *     AdditiveExpr.ArithmeticBinaryExpr_1_0 returns IntConstant
	 *     MultiplicativeExpr returns IntConstant
	 *     MultiplicativeExpr.ArithmeticBinaryExpr_1_0 returns IntConstant
	 *     ExponentialExpr returns IntConstant
	 *     ExponentialExpr.ArithmeticBinaryExpr_1_0 returns IntConstant
	 *     RangeExpr returns IntConstant
	 *     RangeExpr.RangeExpr_1_0 returns IntConstant
	 *     UnaryExpr returns IntConstant
	 *     Constant returns IntConstant
	 *     IntConstant returns IntConstant
	 *
	 * Constraint:
	 *     intValue=Integer
	 * </pre>
	 */
	protected void sequence_IntConstant(ISerializationContext context, IntConstant semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, ProblemPackage.Literals.INT_CONSTANT__INT_VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ProblemPackage.Literals.INT_CONSTANT__INT_VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getIntConstantAccess().getIntValueIntegerParserRuleCall_0(), semanticObject.getIntValue());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Expr returns LogicConstant
	 *     AssignmentExpr returns LogicConstant
	 *     AssignmentExpr.AssignmentExpr_1_0 returns LogicConstant
	 *     BooleanExpr returns LogicConstant
	 *     BooleanExpr.ArithmeticBinaryExpr_1_0 returns LogicConstant
	 *     ComparisonExpr returns LogicConstant
	 *     ComparisonExpr.ComparisonExpr_1_0_0 returns LogicConstant
	 *     ComparisonExpr.LatticeBinaryExpr_1_1_0 returns LogicConstant
	 *     LatticeExpr returns LogicConstant
	 *     LatticeExpr.LatticeBinaryExpr_1_0 returns LogicConstant
	 *     AdditiveExpr returns LogicConstant
	 *     AdditiveExpr.ArithmeticBinaryExpr_1_0 returns LogicConstant
	 *     MultiplicativeExpr returns LogicConstant
	 *     MultiplicativeExpr.ArithmeticBinaryExpr_1_0 returns LogicConstant
	 *     ExponentialExpr returns LogicConstant
	 *     ExponentialExpr.ArithmeticBinaryExpr_1_0 returns LogicConstant
	 *     RangeExpr returns LogicConstant
	 *     RangeExpr.RangeExpr_1_0 returns LogicConstant
	 *     UnaryExpr returns LogicConstant
	 *     Constant returns LogicConstant
	 *     LogicConstant returns LogicConstant
	 *
	 * Constraint:
	 *     logicValue=LogicValue
	 * </pre>
	 */
	protected void sequence_LogicConstant(ISerializationContext context, LogicConstant semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, ProblemPackage.Literals.LOGIC_CONSTANT__LOGIC_VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ProblemPackage.Literals.LOGIC_CONSTANT__LOGIC_VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getLogicConstantAccess().getLogicValueLogicValueEnumRuleCall_0(), semanticObject.getLogicValue());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Expr returns ModalExpr
	 *     AssignmentExpr returns ModalExpr
	 *     AssignmentExpr.AssignmentExpr_1_0 returns ModalExpr
	 *     BooleanExpr returns ModalExpr
	 *     BooleanExpr.ArithmeticBinaryExpr_1_0 returns ModalExpr
	 *     ComparisonExpr returns ModalExpr
	 *     ComparisonExpr.ComparisonExpr_1_0_0 returns ModalExpr
	 *     ComparisonExpr.LatticeBinaryExpr_1_1_0 returns ModalExpr
	 *     LatticeExpr returns ModalExpr
	 *     LatticeExpr.LatticeBinaryExpr_1_0 returns ModalExpr
	 *     AdditiveExpr returns ModalExpr
	 *     AdditiveExpr.ArithmeticBinaryExpr_1_0 returns ModalExpr
	 *     MultiplicativeExpr returns ModalExpr
	 *     MultiplicativeExpr.ArithmeticBinaryExpr_1_0 returns ModalExpr
	 *     ExponentialExpr returns ModalExpr
	 *     ExponentialExpr.ArithmeticBinaryExpr_1_0 returns ModalExpr
	 *     RangeExpr returns ModalExpr
	 *     RangeExpr.RangeExpr_1_0 returns ModalExpr
	 *     UnaryExpr returns ModalExpr
	 *     ModalExpr returns ModalExpr
	 *
	 * Constraint:
	 *     (((concreteness=Concreteness modality=Modality?) | (modality=Modality concreteness=Concreteness?)) body=UnaryExpr)
	 * </pre>
	 */
	protected void sequence_ModalExpr(ISerializationContext context, ModalExpr semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Expr returns NegationExpr
	 *     AssignmentExpr returns NegationExpr
	 *     AssignmentExpr.AssignmentExpr_1_0 returns NegationExpr
	 *     BooleanExpr returns NegationExpr
	 *     BooleanExpr.ArithmeticBinaryExpr_1_0 returns NegationExpr
	 *     ComparisonExpr returns NegationExpr
	 *     ComparisonExpr.ComparisonExpr_1_0_0 returns NegationExpr
	 *     ComparisonExpr.LatticeBinaryExpr_1_1_0 returns NegationExpr
	 *     LatticeExpr returns NegationExpr
	 *     LatticeExpr.LatticeBinaryExpr_1_0 returns NegationExpr
	 *     AdditiveExpr returns NegationExpr
	 *     AdditiveExpr.ArithmeticBinaryExpr_1_0 returns NegationExpr
	 *     MultiplicativeExpr returns NegationExpr
	 *     MultiplicativeExpr.ArithmeticBinaryExpr_1_0 returns NegationExpr
	 *     ExponentialExpr returns NegationExpr
	 *     ExponentialExpr.ArithmeticBinaryExpr_1_0 returns NegationExpr
	 *     RangeExpr returns NegationExpr
	 *     RangeExpr.RangeExpr_1_0 returns NegationExpr
	 *     UnaryExpr returns NegationExpr
	 *     NegationExpr returns NegationExpr
	 *
	 * Constraint:
	 *     body=UnaryExpr
	 * </pre>
	 */
	protected void sequence_NegationExpr(ISerializationContext context, NegationExpr semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, ProblemPackage.Literals.UNARY_EXPR__BODY) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ProblemPackage.Literals.UNARY_EXPR__BODY));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getNegationExprAccess().getBodyUnaryExprParserRuleCall_1_0(), semanticObject.getBody());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     AssertionArgument returns NodeAssertionArgument
	 *     NodeAssertionArgument returns NodeAssertionArgument
	 *
	 * Constraint:
	 *     node=[Node|QualifiedName]
	 * </pre>
	 */
	protected void sequence_NodeAssertionArgument(ISerializationContext context, NodeAssertionArgument semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, ProblemPackage.Literals.NODE_ASSERTION_ARGUMENT__NODE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ProblemPackage.Literals.NODE_ASSERTION_ARGUMENT__NODE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getNodeAssertionArgumentAccess().getNodeNodeQualifiedNameParserRuleCall_0_1(), semanticObject.eGet(ProblemPackage.Literals.NODE_ASSERTION_ARGUMENT__NODE, false));
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Parameter returns Parameter
	 *
	 * Constraint:
	 *     (annotations=AnnotationContainer (kind=ParameterKind | parameterType=[Relation|QualifiedName])? name=Identifier)
	 * </pre>
	 */
	protected void sequence_Parameter(ISerializationContext context, tools.refinery.language.model.problem.Parameter semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Problem returns Problem
	 *
	 * Constraint:
	 *     ((kind=ModuleKind name=QualifiedName? statements+=Statement+) | statements+=Statement+)?
	 * </pre>
	 */
	protected void sequence_Problem(ISerializationContext context, Problem semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Expr returns RangeExpr
	 *     AssignmentExpr returns RangeExpr
	 *     AssignmentExpr.AssignmentExpr_1_0 returns RangeExpr
	 *     BooleanExpr returns RangeExpr
	 *     BooleanExpr.ArithmeticBinaryExpr_1_0 returns RangeExpr
	 *     ComparisonExpr returns RangeExpr
	 *     ComparisonExpr.ComparisonExpr_1_0_0 returns RangeExpr
	 *     ComparisonExpr.LatticeBinaryExpr_1_1_0 returns RangeExpr
	 *     LatticeExpr returns RangeExpr
	 *     LatticeExpr.LatticeBinaryExpr_1_0 returns RangeExpr
	 *     AdditiveExpr returns RangeExpr
	 *     AdditiveExpr.ArithmeticBinaryExpr_1_0 returns RangeExpr
	 *     MultiplicativeExpr returns RangeExpr
	 *     MultiplicativeExpr.ArithmeticBinaryExpr_1_0 returns RangeExpr
	 *     ExponentialExpr returns RangeExpr
	 *     ExponentialExpr.ArithmeticBinaryExpr_1_0 returns RangeExpr
	 *     RangeExpr returns RangeExpr
	 *     RangeExpr.RangeExpr_1_0 returns RangeExpr
	 *     UnaryExpr returns RangeExpr
	 *
	 * Constraint:
	 *     (left=RangeExpr_RangeExpr_1_0 right=UnaryExpr)
	 * </pre>
	 */
	protected void sequence_RangeExpr(ISerializationContext context, RangeExpr semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, ProblemPackage.Literals.BINARY_EXPR__LEFT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ProblemPackage.Literals.BINARY_EXPR__LEFT));
			if (transientValues.isValueTransient(semanticObject, ProblemPackage.Literals.BINARY_EXPR__RIGHT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ProblemPackage.Literals.BINARY_EXPR__RIGHT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getRangeExprAccess().getRangeExprLeftAction_1_0(), semanticObject.getLeft());
		feeder.accept(grammarAccess.getRangeExprAccess().getRightUnaryExprParserRuleCall_1_2_0(), semanticObject.getRight());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     ReferenceMultiplicity returns RangeMultiplicity
	 *     Multiplicity returns RangeMultiplicity
	 *     DefiniteMultiplicity returns RangeMultiplicity
	 *     RangeMultiplicity returns RangeMultiplicity
	 *
	 * Constraint:
	 *     (lowerBound=INT upperBound=UpperBound)
	 * </pre>
	 */
	protected void sequence_RangeMultiplicity(ISerializationContext context, RangeMultiplicity semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, ProblemPackage.Literals.RANGE_MULTIPLICITY__LOWER_BOUND) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ProblemPackage.Literals.RANGE_MULTIPLICITY__LOWER_BOUND));
			if (transientValues.isValueTransient(semanticObject, ProblemPackage.Literals.RANGE_MULTIPLICITY__UPPER_BOUND) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ProblemPackage.Literals.RANGE_MULTIPLICITY__UPPER_BOUND));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getRangeMultiplicityAccess().getLowerBoundINTTerminalRuleCall_0_0(), semanticObject.getLowerBound());
		feeder.accept(grammarAccess.getRangeMultiplicityAccess().getUpperBoundUpperBoundParserRuleCall_2_0(), semanticObject.getUpperBound());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Expr returns RealConstant
	 *     AssignmentExpr returns RealConstant
	 *     AssignmentExpr.AssignmentExpr_1_0 returns RealConstant
	 *     BooleanExpr returns RealConstant
	 *     BooleanExpr.ArithmeticBinaryExpr_1_0 returns RealConstant
	 *     ComparisonExpr returns RealConstant
	 *     ComparisonExpr.ComparisonExpr_1_0_0 returns RealConstant
	 *     ComparisonExpr.LatticeBinaryExpr_1_1_0 returns RealConstant
	 *     LatticeExpr returns RealConstant
	 *     LatticeExpr.LatticeBinaryExpr_1_0 returns RealConstant
	 *     AdditiveExpr returns RealConstant
	 *     AdditiveExpr.ArithmeticBinaryExpr_1_0 returns RealConstant
	 *     MultiplicativeExpr returns RealConstant
	 *     MultiplicativeExpr.ArithmeticBinaryExpr_1_0 returns RealConstant
	 *     ExponentialExpr returns RealConstant
	 *     ExponentialExpr.ArithmeticBinaryExpr_1_0 returns RealConstant
	 *     RangeExpr returns RealConstant
	 *     RangeExpr.RangeExpr_1_0 returns RealConstant
	 *     UnaryExpr returns RealConstant
	 *     Constant returns RealConstant
	 *     RealConstant returns RealConstant
	 *
	 * Constraint:
	 *     realValue=Real
	 * </pre>
	 */
	protected void sequence_RealConstant(ISerializationContext context, RealConstant semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, ProblemPackage.Literals.REAL_CONSTANT__REAL_VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ProblemPackage.Literals.REAL_CONSTANT__REAL_VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getRealConstantAccess().getRealValueRealParserRuleCall_0(), semanticObject.getRealValue());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     ReferenceDeclaration returns ReferenceDeclaration
	 *
	 * Constraint:
	 *     (
	 *         annotations=AnnotationContainer 
	 *         (referenceType=[Relation|NonContainmentQualifiedName] | (kind=ReferenceKind referenceType=[Relation|QualifiedName])) 
	 *         multiplicity=ReferenceMultiplicity? 
	 *         name=Identifier 
	 *         (
	 *             opposite=[ReferenceDeclaration|QualifiedName]? 
	 *             (superSets+=[ReferenceDeclaration|QualifiedName] superSets+=[ReferenceDeclaration|QualifiedName]*)?
	 *         )+
	 *     )
	 * </pre>
	 */
	protected void sequence_ReferenceDeclaration(ISerializationContext context, ReferenceDeclaration semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Statement returns ScopeDeclaration
	 *     ScopeDeclaration returns ScopeDeclaration
	 *
	 * Constraint:
	 *     (typeScopes+=TypeScope typeScopes+=TypeScope*)
	 * </pre>
	 */
	protected void sequence_ScopeDeclaration(ISerializationContext context, ScopeDeclaration semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     ShortLogicConstant returns LogicConstant
	 *
	 * Constraint:
	 *     logicValue=ShortLogicValue?
	 * </pre>
	 */
	protected void sequence_ShortLogicConstant(ISerializationContext context, LogicConstant semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Expr returns StringConstant
	 *     AssignmentExpr returns StringConstant
	 *     AssignmentExpr.AssignmentExpr_1_0 returns StringConstant
	 *     BooleanExpr returns StringConstant
	 *     BooleanExpr.ArithmeticBinaryExpr_1_0 returns StringConstant
	 *     ComparisonExpr returns StringConstant
	 *     ComparisonExpr.ComparisonExpr_1_0_0 returns StringConstant
	 *     ComparisonExpr.LatticeBinaryExpr_1_1_0 returns StringConstant
	 *     LatticeExpr returns StringConstant
	 *     LatticeExpr.LatticeBinaryExpr_1_0 returns StringConstant
	 *     AdditiveExpr returns StringConstant
	 *     AdditiveExpr.ArithmeticBinaryExpr_1_0 returns StringConstant
	 *     MultiplicativeExpr returns StringConstant
	 *     MultiplicativeExpr.ArithmeticBinaryExpr_1_0 returns StringConstant
	 *     ExponentialExpr returns StringConstant
	 *     ExponentialExpr.ArithmeticBinaryExpr_1_0 returns StringConstant
	 *     RangeExpr returns StringConstant
	 *     RangeExpr.RangeExpr_1_0 returns StringConstant
	 *     UnaryExpr returns StringConstant
	 *     Constant returns StringConstant
	 *     StringConstant returns StringConstant
	 *
	 * Constraint:
	 *     stringValue=STRING
	 * </pre>
	 */
	protected void sequence_StringConstant(ISerializationContext context, StringConstant semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, ProblemPackage.Literals.STRING_CONSTANT__STRING_VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ProblemPackage.Literals.STRING_CONSTANT__STRING_VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getStringConstantAccess().getStringValueSTRINGTerminalRuleCall_0(), semanticObject.getStringValue());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Action returns TheoryAction
	 *     TheoryAction returns TheoryAction
	 *
	 * Constraint:
	 *     term=Expr
	 * </pre>
	 */
	protected void sequence_TheoryAction(ISerializationContext context, TheoryAction semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, ProblemPackage.Literals.THEORY_ACTION__TERM) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ProblemPackage.Literals.THEORY_ACTION__TERM));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getTheoryActionAccess().getTermExprParserRuleCall_1_0(), semanticObject.getTerm());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Statement returns TopLevelAnnotation
	 *     TopLevelAnnotation returns TopLevelAnnotation
	 *
	 * Constraint:
	 *     annotation=Annotation
	 * </pre>
	 */
	protected void sequence_TopLevelAnnotation(ISerializationContext context, TopLevelAnnotation semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, ProblemPackage.Literals.TOP_LEVEL_ANNOTATION__ANNOTATION) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ProblemPackage.Literals.TOP_LEVEL_ANNOTATION__ANNOTATION));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getTopLevelAnnotationAccess().getAnnotationAnnotationParserRuleCall_1_0(), semanticObject.getAnnotation());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     TypeScope returns TypeScope
	 *
	 * Constraint:
	 *     (targetType=[Relation|QualifiedName] increment?='+='? multiplicity=DefiniteMultiplicity)
	 * </pre>
	 */
	protected void sequence_TypeScope(ISerializationContext context, TypeScope semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     ReferenceMultiplicity returns UnboundedMultiplicity
	 *     Multiplicity returns UnboundedMultiplicity
	 *     UnboundedMultiplicity returns UnboundedMultiplicity
	 *
	 * Constraint:
	 *     {UnboundedMultiplicity}
	 * </pre>
	 */
	protected void sequence_UnboundedMultiplicity(ISerializationContext context, UnboundedMultiplicity semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Expr returns VariableOrNodeExpr
	 *     AssignmentExpr returns VariableOrNodeExpr
	 *     AssignmentExpr.AssignmentExpr_1_0 returns VariableOrNodeExpr
	 *     BooleanExpr returns VariableOrNodeExpr
	 *     BooleanExpr.ArithmeticBinaryExpr_1_0 returns VariableOrNodeExpr
	 *     ComparisonExpr returns VariableOrNodeExpr
	 *     ComparisonExpr.ComparisonExpr_1_0_0 returns VariableOrNodeExpr
	 *     ComparisonExpr.LatticeBinaryExpr_1_1_0 returns VariableOrNodeExpr
	 *     LatticeExpr returns VariableOrNodeExpr
	 *     LatticeExpr.LatticeBinaryExpr_1_0 returns VariableOrNodeExpr
	 *     AdditiveExpr returns VariableOrNodeExpr
	 *     AdditiveExpr.ArithmeticBinaryExpr_1_0 returns VariableOrNodeExpr
	 *     MultiplicativeExpr returns VariableOrNodeExpr
	 *     MultiplicativeExpr.ArithmeticBinaryExpr_1_0 returns VariableOrNodeExpr
	 *     ExponentialExpr returns VariableOrNodeExpr
	 *     ExponentialExpr.ArithmeticBinaryExpr_1_0 returns VariableOrNodeExpr
	 *     RangeExpr returns VariableOrNodeExpr
	 *     RangeExpr.RangeExpr_1_0 returns VariableOrNodeExpr
	 *     UnaryExpr returns VariableOrNodeExpr
	 *     VariableOrNodeExpr returns VariableOrNodeExpr
	 *
	 * Constraint:
	 *     element=[NamedElement|QualifiedName]
	 * </pre>
	 */
	protected void sequence_VariableOrNodeExpr(ISerializationContext context, VariableOrNodeExpr semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, ProblemPackage.Literals.VARIABLE_OR_NODE_EXPR__ELEMENT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ProblemPackage.Literals.VARIABLE_OR_NODE_EXPR__ELEMENT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getVariableOrNodeExprAccess().getElementNamedElementQualifiedNameParserRuleCall_0_1(), semanticObject.eGet(ProblemPackage.Literals.VARIABLE_OR_NODE_EXPR__ELEMENT, false));
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     AssertionArgument returns WildcardAssertionArgument
	 *     WildcardAssertionArgument returns WildcardAssertionArgument
	 *
	 * Constraint:
	 *     {WildcardAssertionArgument}
	 * </pre>
	 */
	protected void sequence_WildcardAssertionArgument(ISerializationContext context, WildcardAssertionArgument semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
