/*
 * generated by Xtext 2.42.0
 */
package tools.refinery.language.web;

import org.eclipse.xtext.web.server.DefaultWebModule;

/**
 * Manual modifications go to {@link ProblemWebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractProblemWebModule extends DefaultWebModule {

}
