<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="model" nsURI="http://www.inf.mit.bme.hu/theta/statechart/Model"
    nsPrefix="hu.bme.mit.inf.theta.statechart">
  <eClassifiers xsi:type="ecore:EClass" name="StatechartSpecification" eSuperTypes="../../hu.bme.mit.inf.theta.constraint.model/model/constraint.ecore#//ConstraintSpecification">
    <eStructuralFeatures xsi:type="ecore:EReference" name="signalDeclarations" upperBound="-1"
        eType="#//SignalDeclaration" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="statechartDeclarations"
        upperBound="-1" eType="#//StatechartDeclaration" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SignalDeclaration" eSuperTypes="../../hu.bme.mit.inf.theta.constraint.model/model/constraint.ecore#//NamedElement ../../hu.bme.mit.inf.theta.constraint.model/model/constraint.ecore#//ParametricElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="VariableDeclaration" eSuperTypes="../../hu.bme.mit.inf.theta.constraint.model/model/constraint.ecore#//DefinableDeclaration"/>
  <eClassifiers xsi:type="ecore:EClass" name="StatechartDeclaration" eSuperTypes="../../hu.bme.mit.inf.theta.constraint.model/model/constraint.ecore#//NamedElement ../../hu.bme.mit.inf.theta.constraint.model/model/constraint.ecore#//ParametricElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="statechart" lowerBound="1"
        eType="#//Statechart" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Statechart" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="StatechartDefinition" eSuperTypes="#//Statechart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variableDeclarations" upperBound="-1"
        eType="#//VariableDeclaration" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="timeoutDeclarations" upperBound="-1"
        eType="#//TimeoutDeclaration" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="region" lowerBound="1"
        eType="#//Region" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TimeoutDeclaration" eSuperTypes="../../hu.bme.mit.inf.theta.constraint.model/model/constraint.ecore#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="StatechartReference" eSuperTypes="#//Statechart ../../hu.bme.mit.inf.theta.constraint.model/model/constraint.ecore#//ParameterizedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="reference" lowerBound="1"
        eType="#//StatechartDeclaration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Region" eSuperTypes="../../hu.bme.mit.inf.theta.constraint.model/model/constraint.ecore#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="stateNodes" upperBound="-1"
        eType="#//StateNode" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transitions" upperBound="-1"
        eType="#//Transition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StateNode" abstract="true" eSuperTypes="../../hu.bme.mit.inf.theta.constraint.model/model/constraint.ecore#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="State" eSuperTypes="#//StateNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="invariants" upperBound="-1"
        eType="ecore:EClass ../../hu.bme.mit.inf.theta.constraint.model/model/constraint.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entryActions" upperBound="-1"
        eType="#//Action" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="exitActions" upperBound="-1"
        eType="#//Action" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="regions" upperBound="-1"
        eType="#//Region" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StateReferenceExpression" eSuperTypes="../../hu.bme.mit.inf.theta.constraint.model/model/constraint.ecore#//NullaryExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="reference" lowerBound="1"
        eType="#//State"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PseudoState" abstract="true" eSuperTypes="#//StateNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="ChoiceState" eSuperTypes="#//PseudoState"/>
  <eClassifiers xsi:type="ecore:EClass" name="MergeState" eSuperTypes="#//PseudoState"/>
  <eClassifiers xsi:type="ecore:EClass" name="ForkState" eSuperTypes="#//PseudoState"/>
  <eClassifiers xsi:type="ecore:EClass" name="JoinState" eSuperTypes="#//PseudoState"/>
  <eClassifiers xsi:type="ecore:EClass" name="InitialState" eSuperTypes="#//PseudoState"/>
  <eClassifiers xsi:type="ecore:EClass" name="Transition" eSuperTypes="../../hu.bme.mit.inf.theta.constraint.model/model/constraint.ecore#//ParametricElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceState" eType="#//StateNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetState" eType="#//StateNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="trigger" upperBound="-1"
        eType="#//Event" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="guard" eType="ecore:EClass ../../hu.bme.mit.inf.theta.constraint.model/model/constraint.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="effects" upperBound="-1"
        eType="#//Action" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Event" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DefaultEvent" eSuperTypes="#//Event"/>
  <eClassifiers xsi:type="ecore:EClass" name="SignalEvent" eSuperTypes="#//Event ../../hu.bme.mit.inf.theta.constraint.model/model/constraint.ecore#//ParameterizedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="signalDeclaration" lowerBound="1"
        eType="#//SignalDeclaration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TimeoutEvent" eSuperTypes="#//Event">
    <eStructuralFeatures xsi:type="ecore:EReference" name="timeoutDeclaration" lowerBound="1"
        eType="#//TimeoutDeclaration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Action" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="SignalAction" eSuperTypes="#//Action ../../hu.bme.mit.inf.theta.constraint.model/model/constraint.ecore#//ParameterizedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="signalDeclaration" lowerBound="1"
        eType="#//SignalDeclaration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TimeoutAction" abstract="true" eSuperTypes="#//Action">
    <eStructuralFeatures xsi:type="ecore:EReference" name="timeoutDeclaration" lowerBound="1"
        eType="#//TimeoutDeclaration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SetTimeoutAction" eSuperTypes="#//TimeoutAction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="time" lowerBound="1" eType="ecore:EClass ../../hu.bme.mit.inf.theta.constraint.model/model/constraint.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeactivateTimeoutAction" eSuperTypes="#//TimeoutAction"/>
  <eClassifiers xsi:type="ecore:EClass" name="AssignmentAction" eSuperTypes="#//Action">
    <eStructuralFeatures xsi:type="ecore:EReference" name="lhs" lowerBound="1" eType="ecore:EClass ../../hu.bme.mit.inf.theta.constraint.model/model/constraint.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rhs" lowerBound="1" eType="ecore:EClass ../../hu.bme.mit.inf.theta.constraint.model/model/constraint.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
