name: 'Gradle build action'
description: 'Running gradle build and cache the results'
inputs:
    arguments:
        required: true
runs:
  using: "composite"
  steps:
    - name: fetch
      shell: bash
      run: |
        git fetch origin      
    - name: build gradle
      uses: burrunan/gradle-cache-action@4a07779efc8120348ea6dfd35314bc30a586eb0f #rel/3.0.1
      with:
        arguments: ${{ inputs.arguments }} --info --stacktrace --build-cache