name: 'Gradle build action'
description: 'Running gradle build and cache the results'
inputs:
    arguments:
        required: true
runs:
  using: "composite"
  steps:
    - name: fetch
      shell: bash
      run: |
        git fetch origin      
    - name: build gradle
      uses: gradle/actions/setup-gradle@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2 # v2.5.1
      with:
        add-job-summary-as-pr-comment: 'on-failure'
        cache-encryption-key: "mT489CT3NPkLtnWbYOrrrg==" # static key for caching, never important to keep secret
    - name: Run gradle wrapper with arguments
      shell: bash
      run: ./gradlew ${{ inputs.arguments }} --info --stacktrace --configuration-cache