name: 'Deploy to DockerHub'
description: 'Deploy to DockerHub'
inputs:
    project:
        required: true
    version:
        required: true
    user-dockerhub:
        required: true
    user-ghcr:
        required: true
    push:
        required: true
runs: 
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
    - name: Extract metadata (tags, labels) for DockerHub
      id: metaDH
      uses: docker/metadata-action@c4ee3adeed93b1fa6a762f209fb01608c1a22f1e
      with:
        images: ${{ inputs.user-dockerhub }}/${{ inputs.project }}
        tags: type:raw, value=${{ inputs.version }}
    - name: Extract metadata (tags, labels) for ghcr.io
      id: metaGH
      uses: docker/metadata-action@c4ee3adeed93b1fa6a762f209fb01608c1a22f1e
      with:
        images: ghcr.io/${{ inputs.user-ghcr }}/${{ inputs.project }}
        tags: type:raw, value=${{ inputs.version }}
    - name: Creating path
      id: 'path'
      shell: bash
      run: |
        echo "path=./docker/${{ inputs.project }}.Dockerfile" >> $GITHUB_OUTPUT
    - name: Build and push to DockerHub
      uses: docker/build-push-action@2eb1c1961a95fc15694676618e422e8ba1d63825
      with:
        context: .
        file: ${{ steps.path.outputs.path }}
        push: ${{ inputs.push }}
        tags: ${{ steps.metaDH.outputs.tags }}
    - name: Build and push to ghcr.io
      uses: docker/build-push-action@2eb1c1961a95fc15694676618e422e8ba1d63825
      with:
        context: .
        file: ${{ steps.path.outputs.path }}
        push: ${{ inputs.push }}
        tags: ${{ steps.metaGH.outputs.tags }}
