/*
 *  Copyright 2026 Budapest University of Technology and Economics
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package hu.bme.mit.theta.c2xcfa

import hu.bme.mit.theta.common.logging.NullLogger
import hu.bme.mit.theta.frontend.ParseContext
import hu.bme.mit.theta.frontend.transformation.ArchitectureConfig.ArchitectureType
import hu.bme.mit.theta.frontend.transformation.model.types.complex.compound.CStruct
import hu.bme.mit.theta.frontend.transformation.model.types.complex.compound.ObjectLayout
import hu.bme.mit.theta.frontend.transformation.model.types.simple.Struct
import hu.bme.mit.theta.xcfa.ErrorDetection
import hu.bme.mit.theta.xcfa.XcfaProperty
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Test

/**
 * [ObjectLayout] over types parsed from actual C, rather than types built by hand. This is what
 * exercises the plumbing: the grammar has always matched `__attribute__((packed))` and dropped it,
 * and unnamed bitfields never reached a field list at all. `ObjectLayoutTest` pins the arithmetic;
 * this pins that the arithmetic is given the right input.
 *
 * As there, every expectation is generated by compiling the same struct with `gcc -m32`/`-m64` and
 * printing `sizeof`/`_Alignof`/`offsetof`.
 */
class ObjectLayoutFromSourceTest {

  /** Parse [src], then look the named struct back up and lay it out for [arch]. */
  private fun layoutOf(
    src: String,
    tag: String,
    arch: ArchitectureType,
    union: Boolean = false,
  ): ObjectLayout.Layout {
    val parseContext = ParseContext()
    parseContext.architecture = arch
    getXcfaFromC(
      src.byteInputStream(),
      parseContext,
      false,
      XcfaProperty(ErrorDetection.ERROR_LOCATION),
      NullLogger.getInstance(),
    )
    val struct =
      requireNotNull(Struct.getByName(tag, union)) { "struct $tag was not registered by the parser" }
    return ObjectLayout.of(struct.actualType as CStruct, arch)
  }

  private fun bothModels(block: (ArchitectureType) -> Unit) {
    listOf(ArchitectureType.ILP32, ArchitectureType.LP64).forEach(block)
  }

  @Test
  fun packedRemovesEveryPad() {
    // gcc both models: struct P1 { char a; int b; } __attribute__((packed)) -> size 5, align 1, b=1
    // Unpacked this is size 8 with b at 4, so the attribute is doing all the work here.
    bothModels { arch ->
      val layout =
        layoutOf(
          """
          struct P1 { char a; int b; } __attribute__((packed));
          struct P1 g;
          int main() { g.a = 1; return g.a; }
          """
            .trimIndent(),
          "P1",
          arch,
        )
      assertEquals(40, layout.bitSize, "size = 5 bytes, $arch")
      assertEquals(8, layout.bitAlignment, "alignment = 1 byte, $arch")
      assertEquals(8, layout.field("b")!!.bitOffset, "b at byte 1, $arch")
    }
  }

  @Test
  fun packedStructWithAlignedStillRoundsUp() {
    // gcc both: struct M1 { char a; int b; } __attribute__((packed, aligned(8)))
    //   -> size 8, align 8, b=1.  Both attributes apply: packed places b at byte 1, aligned(8)
    // sets the struct's alignment and therefore its rounded-up size.
    bothModels { arch ->
      val layout =
        layoutOf(
          """
          struct M1 { char a; int b; } __attribute__((packed, aligned(8)));
          struct M1 g;
          int main() { g.a = 1; return g.a; }
          """
            .trimIndent(),
          "M1",
          arch,
        )
      assertEquals(64, layout.bitSize, "size = 8 bytes, $arch")
      assertEquals(64, layout.bitAlignment, "alignment = 8 bytes, $arch")
      assertEquals(8, layout.field("b")!!.bitOffset, "b still at byte 1, $arch")
    }
  }

  @Test
  fun alignedOnTheStructRaisesItsAlignmentOnly() {
    // gcc both: struct A1 { char a; int b; } __attribute__((aligned(16))) -> size 16, align 16, b=4
    // Not packed, so b keeps its natural offset; only the outer size/alignment change.
    bothModels { arch ->
      val layout =
        layoutOf(
          """
          struct A1 { char a; int b; } __attribute__((aligned(16)));
          struct A1 g;
          int main() { g.a = 1; return g.a; }
          """
            .trimIndent(),
          "A1",
          arch,
        )
      assertEquals(128, layout.bitSize, "size = 16 bytes, $arch")
      assertEquals(128, layout.bitAlignment, "alignment = 16 bytes, $arch")
      assertEquals(32, layout.field("b")!!.bitOffset, "b at byte 4, $arch")
    }
  }

  @Test
  fun alignedOnAMemberMovesThatMemberAndTheStruct() {
    // gcc both: struct A2 { char a; int b __attribute__((aligned(8))); } -> size 16, align 8, b=8
    bothModels { arch ->
      val layout =
        layoutOf(
          """
          struct A2 { char a; int b __attribute__((aligned(8))); };
          struct A2 g;
          int main() { g.a = 1; return g.a; }
          """
            .trimIndent(),
          "A2",
          arch,
        )
      assertEquals(128, layout.bitSize, "size = 16 bytes, $arch")
      assertEquals(64, layout.bitAlignment, "alignment = 8 bytes, $arch")
      assertEquals(64, layout.field("b")!!.bitOffset, "b at byte 8, $arch")
    }
  }

  @Test
  fun zeroWidthUnnamedBitfieldClosesTheStorageUnit() {
    // gcc both: struct Z1 { unsigned a:4; unsigned :0; unsigned b:4; } -> size 8, align 4
    // Without the `:0` this is 4 bytes with b at bit 4 -- the whole point of the idiom, and it was
    // invisible before because unnamed bitfields never reached the field list.
    bothModels { arch ->
      val layout =
        layoutOf(
          """
          struct Z1 { unsigned a:4; unsigned :0; unsigned b:4; };
          struct Z1 g;
          int main() { g.a = 1; return g.a; }
          """
            .trimIndent(),
          "Z1",
          arch,
        )
      assertEquals(64, layout.bitSize, "size = 8 bytes, $arch")
      assertEquals(32, layout.field("b")!!.bitOffset, "b restarts at bit 32, $arch")
    }
  }

  @Test
  fun nonZeroUnnamedBitfieldReservesBitsWithoutAligning() {
    // gcc -m64: struct Q1 { char a; int :3; char b; } -> size 3, align 1, b=2
    // Two things at once: the :3 pushes b past bit 11 (so byte 2), and it does NOT drag the
    // struct's alignment up to the int's 4 -- a named `int` bitfield would have.
    bothModels { arch ->
      val layout =
        layoutOf(
          """
          struct Q1 { char a; int :3; char b; };
          struct Q1 g;
          int main() { g.a = 1; return g.a; }
          """
            .trimIndent(),
          "Q1",
          arch,
        )
      assertEquals(24, layout.bitSize, "size = 3 bytes, $arch")
      assertEquals(8, layout.bitAlignment, "alignment stays 1 byte, $arch")
      assertEquals(16, layout.field("b")!!.bitOffset, "b at byte 2, $arch")
    }
  }

  @Test
  fun aTrailingUnnamedBitfieldStillGrowsTheStruct() {
    // gcc both: struct Q3 { char a; int :24; char b; } -> size 5, align 1, b=4
    bothModels { arch ->
      val layout =
        layoutOf(
          """
          struct Q3 { char a; int :24; char b; };
          struct Q3 g;
          int main() { g.a = 1; return g.a; }
          """
            .trimIndent(),
          "Q3",
          arch,
        )
      assertEquals(40, layout.bitSize, "size = 5 bytes, $arch")
      assertEquals(32, layout.field("b")!!.bitOffset, "b at byte 4, $arch")
    }
  }

  @Test
  fun anUnattributedStructIsUnchanged() {
    // The control: the same struct without attributes must keep the natural layout, so the
    // plumbing cannot be "working" by applying packed everywhere.
    // gcc both: struct N1 { char a; int b; } -> size 8, align 4, b=4
    bothModels { arch ->
      val layout =
        layoutOf(
          """
          struct N1 { char a; int b; };
          struct N1 g;
          int main() { g.a = 1; return g.a; }
          """
            .trimIndent(),
          "N1",
          arch,
        )
      assertEquals(64, layout.bitSize, "size = 8 bytes, $arch")
      assertEquals(32, layout.bitAlignment, "alignment = 4 bytes, $arch")
      assertEquals(32, layout.field("b")!!.bitOffset, "b at byte 4, $arch")
    }
  }
}
