name: 'Run tests using benchexec'
description: 'Running benchexec tests on xcfa-cli'
inputs:
    name:
        required: true
        description: 'The name for the benchexec run (used for result artifact naming)'
    tool:
        required: true
        description: 'The name of the tool artifact to download'
    input_type:
        required: true
        description: 'The type of input files to benchmark (e.g., "c" for C files)'
    config_options:
        required: true
        description: 'A space-separated list of configuration options to apply to the XML input file'
    timeout:
        required: true
        description: 'The overall timeout for the benchexec run in seconds'
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
    - name: Install benchexec and dependencies
      shell: bash
      run: |
        sudo add-apt-repository ppa:sosy-lab/benchmarking
        sudo apt install benchexec openjdk-21-jre-headless libgomp1 libmpfr-dev
    - uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v3.0.2
      name: Get tool
      with:
        name: ${{ inputs.tool }}
        path: release/
    - name: Unzip tool
      shell: bash
      run: |
        unzip release/*.zip
    - name: Run benchexec
      shell: bash
      run: |
        XML=integration-tests/${{ inputs.input_type }}/theta.xml
        for config in ${{ inputs.config_options }}
        do
          echo "Applying config option: $config"
          escaped_config=$(printf '%s\n' "$config" | sed -e 's/[\/&]/\\&/g')
          sed -i "s|<!-- config -->|<!-- config -->\n$escaped_config|g" "$XML"
        done
        cat "$XML"

        folder=$(dirname $(find . -name "theta.jar" | head -n1))
        timeout=$((${{inputs.timeout}} / tasks_num))
        echo "timeout --kill-after 15 $timeout benchexec $XML -n 2 --no-container --tool-directory $folder || true"
        timeout --kill-after 15 "$timeout" benchexec "$XML" -n 2 --no-container --tool-directory "$folder" || true
    - name: Upload results
      uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v3.1.2
      with:
        name: BenchexecResults-${{ inputs.name }}-${{ inputs.input_type }}
        path: results
