name: 'Run tests using benchexec'
description: 'Running benchexec tests on xcfa-cli'
inputs:
    rundef:
        required: true
    portfolio:
        required: true
    tool:
        required: true
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
    - name: Install benchexec and dependencies
      shell: bash
      run: |
        sudo add-apt-repository ppa:sosy-lab/benchmarking
        sudo apt install benchexec openjdk-17-jre-headless libgomp1 libmpfr-dev
    - name: Get benchmark definition file
      shell: bash
      run: |
        mkdir -p xml
        cp $GITHUB_ACTION_PATH/theta.xml xml/
    - name: Get sv-benchmarks (retry max. 3 times)
      uses: nick-fields/retry@7152eba30c6575329ac0576536151aca5a72780e # v3.0.0
      with:
        timeout_minutes: 15
        max_attempts: 3
        shell: bash
        command: git clone --filter=blob:none --no-checkout --depth 1 --sparse https://gitlab.com/sosy-lab/benchmarking/sv-benchmarks.git
    - name: Get C folder (retry max. 3 times)
      uses: nick-fields/retry@7152eba30c6575329ac0576536151aca5a72780e # v3.0.0
      with:
        timeout_minutes: 15
        max_attempts: 3
        shell: bash
        command: |
          cd sv-benchmarks
          git sparse-checkout add c
          git checkout
    - uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
      name: Get zip
      with:
        name: ${{ inputs.tool }}
        path: release/
    - name: Unzip 
      shell: bash
      run: |
        unzip release/*.zip
    - name: Run benchexec
      shell: bash
      run: |
        sed -i 's/<option name="--portfolio">STABLE<\/option>/<option name="--portfolio">${{ inputs.portfolio }}<\/option>/g' xml/theta.xml
        cat xml/theta.xml
        for task in $(cat xml/theta.xml | grep 'rundefinition name=' | grep -oP '(?<=").*(?=")')
        do
          timeout 60 benchexec xml/theta.xml -n 2 --no-container --tool-directory Theta -r ${{ inputs.rundef }} -t "$task" || true
        done
    - name: Upload results
      uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
      with:
        name: BenchexecResults-${{ inputs.rundef }}-${{ inputs.portfolio }}
        path: results
