/*
 * generated by Xtext 2.42.0
 */
package tools.refinery.language.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class ProblemAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("tools/refinery/language/parser/antlr/internal/InternalProblemParser.tokens");
	}
}
