name: 'Gradle build action'
description: 'Running gradle build without tests'
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
#    - name: macOS library hack
#      if: runner.os == 'macOS'
#      shell: bash
#      run: |
#        # cp lib/*dylib ./
#        # cp lib/*jnilib ./
#        # cp libmpfr.dylib libmpfr.4.dylib
#        # cp libmpfr_java-1.4.jnilib libmpfr_java.jnilib
#        # sudo ln -sf $PWD/libmpfr.4.dylib /usr/local/lib/
#        # for i in subprojects/*/*; do cp *dylib $i/; done
#        # for i in subprojects/*/*; do cp *jnilib $i/; done
#        # export LD_LIBRARY_PATH=$PWD/lib
    - name: Setup java 17
      uses: actions/setup-java@5ffc13f4174014e2d4d4572b3d74c3fa61aeb2c2 # v3.11.0
      with:
        distribution: temurin
        java-version: 17
    - name: build gradle
      uses: ./.github/actions/cache-build
      with:
        arguments: test
