name: 'Create release'
description: 'Create release and deploy JARs'
inputs:
    OSSRH_PASSWORD:
        required: true
    OSSRH_USERNAME:
        required: true
    PGP_KEY:
        required: true
    PGP_KEY_ID:
        required: true
    PGP_PWD:
        required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
    - uses: actions/setup-java@5ffc13f4174014e2d4d4572b3d74c3fa61aeb2c2 # v3.11.0
      with:
        distribution: temurin
        java-version: 17
    - name: Publish to Maven Staging
      uses: ./.github/actions/cache-build
      env:
        OSSRH_PASSWORD: ${{ inputs.OSSRH_PASSWORD }}
        OSSRH_USERNAME: ${{ inputs.OSSRH_USERNAME }}
        PGP_KEY: ${{ inputs.PGP_KEY }}
        PGP_KEY_ID: ${{ inputs.PGP_KEY_ID }}
        PGP_PWD: ${{ inputs.PGP_PWD }} 
      with:
        arguments: publish
    - name: Close staging and publish release
      uses: ./.github/actions/cache-build
      env:
        OSSRH_PASSWORD: ${{ inputs.OSSRH_PASSWORD }}
        OSSRH_USERNAME: ${{ inputs.OSSRH_USERNAME }}
      with:
        arguments: closeAndReleaseRepository