/*
 * generated by Xtext 2.42.0
 */
package tools.refinery.language.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.antlr.runtime.CharStream;
import org.antlr.runtime.TokenSource;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import tools.refinery.language.ide.contentassist.antlr.internal.InternalProblemParser;
import tools.refinery.language.services.ProblemGrammarAccess;

public class ProblemParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(ProblemGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, ProblemGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getStatementAccess().getAlternatives(), "rule__Statement__Alternatives");
			builder.put(grammarAccess.getAnnotatedStatementAccess().getAlternatives_1(), "rule__AnnotatedStatement__Alternatives_1");
			builder.put(grammarAccess.getAnnotatedStatementAccess().getAlternatives_1_0_5(), "rule__AnnotatedStatement__Alternatives_1_0_5");
			builder.put(grammarAccess.getAnnotatedStatementAccess().getAlternatives_1_1_3(), "rule__AnnotatedStatement__Alternatives_1_1_3");
			builder.put(grammarAccess.getAnnotatedStatementAccess().getAlternatives_1_1_3_0_1_2(), "rule__AnnotatedStatement__Alternatives_1_1_3_0_1_2");
			builder.put(grammarAccess.getAnnotatedStatementAccess().getAlternatives_1_5_1(), "rule__AnnotatedStatement__Alternatives_1_5_1");
			builder.put(grammarAccess.getAnnotatedStatementAccess().getAlternatives_1_9_1(), "rule__AnnotatedStatement__Alternatives_1_9_1");
			builder.put(grammarAccess.getReferenceDeclarationAccess().getAlternatives_1(), "rule__ReferenceDeclaration__Alternatives_1");
			builder.put(grammarAccess.getParameterAccess().getAlternatives_1(), "rule__Parameter__Alternatives_1");
			builder.put(grammarAccess.getActionAccess().getAlternatives(), "rule__Action__Alternatives");
			builder.put(grammarAccess.getAssertionActionAccess().getAlternatives(), "rule__AssertionAction__Alternatives");
			builder.put(grammarAccess.getComparisonExprAccess().getAlternatives_1(), "rule__ComparisonExpr__Alternatives_1");
			builder.put(grammarAccess.getUnaryExprAccess().getAlternatives(), "rule__UnaryExpr__Alternatives");
			builder.put(grammarAccess.getModalExprAccess().getAlternatives_0(), "rule__ModalExpr__Alternatives_0");
			builder.put(grammarAccess.getConstantAccess().getAlternatives(), "rule__Constant__Alternatives");
			builder.put(grammarAccess.getAssertionAccess().getAlternatives_1(), "rule__Assertion__Alternatives_1");
			builder.put(grammarAccess.getAssertionArgumentAccess().getAlternatives(), "rule__AssertionArgument__Alternatives");
			builder.put(grammarAccess.getTypeScopeAccess().getAlternatives_1(), "rule__TypeScope__Alternatives_1");
			builder.put(grammarAccess.getMultiplicityAccess().getAlternatives(), "rule__Multiplicity__Alternatives");
			builder.put(grammarAccess.getDefiniteMultiplicityAccess().getAlternatives(), "rule__DefiniteMultiplicity__Alternatives");
			builder.put(grammarAccess.getUpperBoundAccess().getAlternatives(), "rule__UpperBound__Alternatives");
			builder.put(grammarAccess.getNonContainmentQualifiedNameAccess().getAlternatives_0(), "rule__NonContainmentQualifiedName__Alternatives_0");
			builder.put(grammarAccess.getIdentifierAccess().getAlternatives(), "rule__Identifier__Alternatives");
			builder.put(grammarAccess.getNonContainmentIdentifierAccess().getAlternatives(), "rule__NonContainmentIdentifier__Alternatives");
			builder.put(grammarAccess.getRealAccess().getAlternatives(), "rule__Real__Alternatives");
			builder.put(grammarAccess.getRealAccess().getAlternatives_1_2(), "rule__Real__Alternatives_1_2");
			builder.put(grammarAccess.getModuleKindAccess().getAlternatives(), "rule__ModuleKind__Alternatives");
			builder.put(grammarAccess.getReferenceKindAccess().getAlternatives(), "rule__ReferenceKind__Alternatives");
			builder.put(grammarAccess.getPredicateKindAccess().getAlternatives(), "rule__PredicateKind__Alternatives");
			builder.put(grammarAccess.getRuleKindAccess().getAlternatives(), "rule__RuleKind__Alternatives");
			builder.put(grammarAccess.getBooleanBinaryOpAccess().getAlternatives(), "rule__BooleanBinaryOp__Alternatives");
			builder.put(grammarAccess.getComparisonOpAccess().getAlternatives(), "rule__ComparisonOp__Alternatives");
			builder.put(grammarAccess.getLatticeComparisonOpAccess().getAlternatives(), "rule__LatticeComparisonOp__Alternatives");
			builder.put(grammarAccess.getLatticeBinaryOpAccess().getAlternatives(), "rule__LatticeBinaryOp__Alternatives");
			builder.put(grammarAccess.getAdditiveOpAccess().getAlternatives(), "rule__AdditiveOp__Alternatives");
			builder.put(grammarAccess.getMultiplicativeOpAccess().getAlternatives(), "rule__MultiplicativeOp__Alternatives");
			builder.put(grammarAccess.getUnaryOpAccess().getAlternatives(), "rule__UnaryOp__Alternatives");
			builder.put(grammarAccess.getConcretenessAccess().getAlternatives(), "rule__Concreteness__Alternatives");
			builder.put(grammarAccess.getModalityAccess().getAlternatives(), "rule__Modality__Alternatives");
			builder.put(grammarAccess.getLogicValueAccess().getAlternatives(), "rule__LogicValue__Alternatives");
			builder.put(grammarAccess.getShortLogicValueAccess().getAlternatives(), "rule__ShortLogicValue__Alternatives");
			builder.put(grammarAccess.getNodeKindAccess().getAlternatives(), "rule__NodeKind__Alternatives");
			builder.put(grammarAccess.getProblemAccess().getGroup(), "rule__Problem__Group__0");
			builder.put(grammarAccess.getProblemAccess().getGroup_0(), "rule__Problem__Group_0__0");
			builder.put(grammarAccess.getAnnotatedStatementAccess().getGroup(), "rule__AnnotatedStatement__Group__0");
			builder.put(grammarAccess.getAnnotatedStatementAccess().getGroup_1_0(), "rule__AnnotatedStatement__Group_1_0__0");
			builder.put(grammarAccess.getAnnotatedStatementAccess().getGroup_1_0_4(), "rule__AnnotatedStatement__Group_1_0_4__0");
			builder.put(grammarAccess.getAnnotatedStatementAccess().getGroup_1_0_4_2(), "rule__AnnotatedStatement__Group_1_0_4_2__0");
			builder.put(grammarAccess.getAnnotatedStatementAccess().getGroup_1_0_5_0(), "rule__AnnotatedStatement__Group_1_0_5_0__0");
			builder.put(grammarAccess.getAnnotatedStatementAccess().getGroup_1_0_5_0_1(), "rule__AnnotatedStatement__Group_1_0_5_0_1__0");
			builder.put(grammarAccess.getAnnotatedStatementAccess().getGroup_1_1(), "rule__AnnotatedStatement__Group_1_1__0");
			builder.put(grammarAccess.getAnnotatedStatementAccess().getGroup_1_1_3_0(), "rule__AnnotatedStatement__Group_1_1_3_0__0");
			builder.put(grammarAccess.getAnnotatedStatementAccess().getGroup_1_1_3_0_1(), "rule__AnnotatedStatement__Group_1_1_3_0_1__0");
			builder.put(grammarAccess.getAnnotatedStatementAccess().getGroup_1_1_3_0_1_1(), "rule__AnnotatedStatement__Group_1_1_3_0_1_1__0");
			builder.put(grammarAccess.getAnnotatedStatementAccess().getGroup_1_2(), "rule__AnnotatedStatement__Group_1_2__0");
			builder.put(grammarAccess.getAnnotatedStatementAccess().getGroup_1_3(), "rule__AnnotatedStatement__Group_1_3__0");
			builder.put(grammarAccess.getAnnotatedStatementAccess().getGroup_1_4(), "rule__AnnotatedStatement__Group_1_4__0");
			builder.put(grammarAccess.getAnnotatedStatementAccess().getGroup_1_4_6(), "rule__AnnotatedStatement__Group_1_4_6__0");
			builder.put(grammarAccess.getAnnotatedStatementAccess().getGroup_1_4_6_1(), "rule__AnnotatedStatement__Group_1_4_6_1__0");
			builder.put(grammarAccess.getAnnotatedStatementAccess().getGroup_1_5(), "rule__AnnotatedStatement__Group_1_5__0");
			builder.put(grammarAccess.getAnnotatedStatementAccess().getGroup_1_5_1_1(), "rule__AnnotatedStatement__Group_1_5_1_1__0");
			builder.put(grammarAccess.getAnnotatedStatementAccess().getGroup_1_5_4(), "rule__AnnotatedStatement__Group_1_5_4__0");
			builder.put(grammarAccess.getAnnotatedStatementAccess().getGroup_1_5_4_1(), "rule__AnnotatedStatement__Group_1_5_4_1__0");
			builder.put(grammarAccess.getAnnotatedStatementAccess().getGroup_1_5_6(), "rule__AnnotatedStatement__Group_1_5_6__0");
			builder.put(grammarAccess.getAnnotatedStatementAccess().getGroup_1_5_6_2(), "rule__AnnotatedStatement__Group_1_5_6_2__0");
			builder.put(grammarAccess.getAnnotatedStatementAccess().getGroup_1_5_7(), "rule__AnnotatedStatement__Group_1_5_7__0");
			builder.put(grammarAccess.getAnnotatedStatementAccess().getGroup_1_5_7_2(), "rule__AnnotatedStatement__Group_1_5_7_2__0");
			builder.put(grammarAccess.getAnnotatedStatementAccess().getGroup_1_6(), "rule__AnnotatedStatement__Group_1_6__0");
			builder.put(grammarAccess.getAnnotatedStatementAccess().getGroup_1_6_5(), "rule__AnnotatedStatement__Group_1_6_5__0");
			builder.put(grammarAccess.getAnnotatedStatementAccess().getGroup_1_6_5_1(), "rule__AnnotatedStatement__Group_1_6_5_1__0");
			builder.put(grammarAccess.getAnnotatedStatementAccess().getGroup_1_6_7(), "rule__AnnotatedStatement__Group_1_6_7__0");
			builder.put(grammarAccess.getAnnotatedStatementAccess().getGroup_1_6_7_2(), "rule__AnnotatedStatement__Group_1_6_7_2__0");
			builder.put(grammarAccess.getAnnotatedStatementAccess().getGroup_1_7(), "rule__AnnotatedStatement__Group_1_7__0");
			builder.put(grammarAccess.getAnnotatedStatementAccess().getGroup_1_7_5(), "rule__AnnotatedStatement__Group_1_7_5__0");
			builder.put(grammarAccess.getAnnotatedStatementAccess().getGroup_1_7_5_1(), "rule__AnnotatedStatement__Group_1_7_5_1__0");
			builder.put(grammarAccess.getAnnotatedStatementAccess().getGroup_1_7_7(), "rule__AnnotatedStatement__Group_1_7_7__0");
			builder.put(grammarAccess.getAnnotatedStatementAccess().getGroup_1_7_7_2(), "rule__AnnotatedStatement__Group_1_7_7_2__0");
			builder.put(grammarAccess.getAnnotatedStatementAccess().getGroup_1_7_8(), "rule__AnnotatedStatement__Group_1_7_8__0");
			builder.put(grammarAccess.getAnnotatedStatementAccess().getGroup_1_7_8_2(), "rule__AnnotatedStatement__Group_1_7_8_2__0");
			builder.put(grammarAccess.getAnnotatedStatementAccess().getGroup_1_8(), "rule__AnnotatedStatement__Group_1_8__0");
			builder.put(grammarAccess.getAnnotatedStatementAccess().getGroup_1_8_5(), "rule__AnnotatedStatement__Group_1_8_5__0");
			builder.put(grammarAccess.getAnnotatedStatementAccess().getGroup_1_8_5_1(), "rule__AnnotatedStatement__Group_1_8_5_1__0");
			builder.put(grammarAccess.getAnnotatedStatementAccess().getGroup_1_9(), "rule__AnnotatedStatement__Group_1_9__0");
			builder.put(grammarAccess.getAnnotatedStatementAccess().getGroup_1_9_1_1(), "rule__AnnotatedStatement__Group_1_9_1_1__0");
			builder.put(grammarAccess.getAnnotatedStatementAccess().getGroup_1_9_3(), "rule__AnnotatedStatement__Group_1_9_3__0");
			builder.put(grammarAccess.getAnnotationContainerAccess().getGroup(), "rule__AnnotationContainer__Group__0");
			builder.put(grammarAccess.getAnnotationContainerAccess().getGroup_1(), "rule__AnnotationContainer__Group_1__0");
			builder.put(grammarAccess.getTopLevelAnnotationAccess().getGroup(), "rule__TopLevelAnnotation__Group__0");
			builder.put(grammarAccess.getAnnotationAccess().getGroup(), "rule__Annotation__Group__0");
			builder.put(grammarAccess.getAnnotationAccess().getGroup_2(), "rule__Annotation__Group_2__0");
			builder.put(grammarAccess.getAnnotationAccess().getGroup_2_1(), "rule__Annotation__Group_2_1__0");
			builder.put(grammarAccess.getAnnotationAccess().getGroup_2_1_1(), "rule__Annotation__Group_2_1_1__0");
			builder.put(grammarAccess.getAnnotationArgumentAccess().getGroup(), "rule__AnnotationArgument__Group__0");
			builder.put(grammarAccess.getAnnotationArgumentAccess().getGroup_1(), "rule__AnnotationArgument__Group_1__0");
			builder.put(grammarAccess.getImportStatementAccess().getGroup(), "rule__ImportStatement__Group__0");
			builder.put(grammarAccess.getImportStatementAccess().getGroup_2(), "rule__ImportStatement__Group_2__0");
			builder.put(grammarAccess.getEnumLiteralAccess().getGroup(), "rule__EnumLiteral__Group__0");
			builder.put(grammarAccess.getReferenceDeclarationAccess().getGroup(), "rule__ReferenceDeclaration__Group__0");
			builder.put(grammarAccess.getReferenceDeclarationAccess().getGroup_1_1(), "rule__ReferenceDeclaration__Group_1_1__0");
			builder.put(grammarAccess.getReferenceDeclarationAccess().getGroup_4_0(), "rule__ReferenceDeclaration__Group_4_0__0");
			builder.put(grammarAccess.getReferenceDeclarationAccess().getGroup_4_1(), "rule__ReferenceDeclaration__Group_4_1__0");
			builder.put(grammarAccess.getReferenceDeclarationAccess().getGroup_4_1_2(), "rule__ReferenceDeclaration__Group_4_1_2__0");
			builder.put(grammarAccess.getReferenceMultiplicityAccess().getGroup(), "rule__ReferenceMultiplicity__Group__0");
			builder.put(grammarAccess.getConjunctionAccess().getGroup(), "rule__Conjunction__Group__0");
			builder.put(grammarAccess.getConjunctionAccess().getGroup_1(), "rule__Conjunction__Group_1__0");
			builder.put(grammarAccess.getCaseAccess().getGroup(), "rule__Case__Group__0");
			builder.put(grammarAccess.getCaseAccess().getGroup_1(), "rule__Case__Group_1__0");
			builder.put(grammarAccess.getParameterAccess().getGroup(), "rule__Parameter__Group__0");
			builder.put(grammarAccess.getConsequentAccess().getGroup(), "rule__Consequent__Group__0");
			builder.put(grammarAccess.getConsequentAccess().getGroup_1(), "rule__Consequent__Group_1__0");
			builder.put(grammarAccess.getAssertionActionAccess().getGroup_0(), "rule__AssertionAction__Group_0__0");
			builder.put(grammarAccess.getAssertionActionAccess().getGroup_0_2(), "rule__AssertionAction__Group_0_2__0");
			builder.put(grammarAccess.getAssertionActionAccess().getGroup_0_2_1(), "rule__AssertionAction__Group_0_2_1__0");
			builder.put(grammarAccess.getAssertionActionAccess().getGroup_1(), "rule__AssertionAction__Group_1__0");
			builder.put(grammarAccess.getAssertionActionAccess().getGroup_1_3(), "rule__AssertionAction__Group_1_3__0");
			builder.put(grammarAccess.getAssertionActionAccess().getGroup_1_3_1(), "rule__AssertionAction__Group_1_3_1__0");
			builder.put(grammarAccess.getTheoryActionAccess().getGroup(), "rule__TheoryAction__Group__0");
			builder.put(grammarAccess.getAssignmentExprAccess().getGroup(), "rule__AssignmentExpr__Group__0");
			builder.put(grammarAccess.getAssignmentExprAccess().getGroup_1(), "rule__AssignmentExpr__Group_1__0");
			builder.put(grammarAccess.getBooleanExprAccess().getGroup(), "rule__BooleanExpr__Group__0");
			builder.put(grammarAccess.getBooleanExprAccess().getGroup_1(), "rule__BooleanExpr__Group_1__0");
			builder.put(grammarAccess.getComparisonExprAccess().getGroup(), "rule__ComparisonExpr__Group__0");
			builder.put(grammarAccess.getComparisonExprAccess().getGroup_1_0(), "rule__ComparisonExpr__Group_1_0__0");
			builder.put(grammarAccess.getComparisonExprAccess().getGroup_1_1(), "rule__ComparisonExpr__Group_1_1__0");
			builder.put(grammarAccess.getLatticeExprAccess().getGroup(), "rule__LatticeExpr__Group__0");
			builder.put(grammarAccess.getLatticeExprAccess().getGroup_1(), "rule__LatticeExpr__Group_1__0");
			builder.put(grammarAccess.getAdditiveExprAccess().getGroup(), "rule__AdditiveExpr__Group__0");
			builder.put(grammarAccess.getAdditiveExprAccess().getGroup_1(), "rule__AdditiveExpr__Group_1__0");
			builder.put(grammarAccess.getMultiplicativeExprAccess().getGroup(), "rule__MultiplicativeExpr__Group__0");
			builder.put(grammarAccess.getMultiplicativeExprAccess().getGroup_1(), "rule__MultiplicativeExpr__Group_1__0");
			builder.put(grammarAccess.getExponentialExprAccess().getGroup(), "rule__ExponentialExpr__Group__0");
			builder.put(grammarAccess.getExponentialExprAccess().getGroup_1(), "rule__ExponentialExpr__Group_1__0");
			builder.put(grammarAccess.getRangeExprAccess().getGroup(), "rule__RangeExpr__Group__0");
			builder.put(grammarAccess.getRangeExprAccess().getGroup_1(), "rule__RangeExpr__Group_1__0");
			builder.put(grammarAccess.getUnaryExprAccess().getGroup_7(), "rule__UnaryExpr__Group_7__0");
			builder.put(grammarAccess.getArithmeticUnaryExprAccess().getGroup(), "rule__ArithmeticUnaryExpr__Group__0");
			builder.put(grammarAccess.getNegationExprAccess().getGroup(), "rule__NegationExpr__Group__0");
			builder.put(grammarAccess.getAggregationExprAccess().getGroup(), "rule__AggregationExpr__Group__0");
			builder.put(grammarAccess.getAggregationExprAccess().getGroup_3(), "rule__AggregationExpr__Group_3__0");
			builder.put(grammarAccess.getModalExprAccess().getGroup(), "rule__ModalExpr__Group__0");
			builder.put(grammarAccess.getModalExprAccess().getGroup_0_0(), "rule__ModalExpr__Group_0_0__0");
			builder.put(grammarAccess.getModalExprAccess().getGroup_0_1(), "rule__ModalExpr__Group_0_1__0");
			builder.put(grammarAccess.getAtomAccess().getGroup(), "rule__Atom__Group__0");
			builder.put(grammarAccess.getAtomAccess().getGroup_3(), "rule__Atom__Group_3__0");
			builder.put(grammarAccess.getAtomAccess().getGroup_3_1(), "rule__Atom__Group_3_1__0");
			builder.put(grammarAccess.getInfiniteConstantAccess().getGroup(), "rule__InfiniteConstant__Group__0");
			builder.put(grammarAccess.getAssertionAccess().getGroup(), "rule__Assertion__Group__0");
			builder.put(grammarAccess.getAssertionAccess().getGroup_1_0(), "rule__Assertion__Group_1_0__0");
			builder.put(grammarAccess.getAssertionAccess().getGroup_1_0_2(), "rule__Assertion__Group_1_0_2__0");
			builder.put(grammarAccess.getAssertionAccess().getGroup_1_0_2_1(), "rule__Assertion__Group_1_0_2_1__0");
			builder.put(grammarAccess.getAssertionAccess().getGroup_1_1(), "rule__Assertion__Group_1_1__0");
			builder.put(grammarAccess.getAssertionAccess().getGroup_1_1_3(), "rule__Assertion__Group_1_1_3__0");
			builder.put(grammarAccess.getAssertionAccess().getGroup_1_1_3_1(), "rule__Assertion__Group_1_1_3_1__0");
			builder.put(grammarAccess.getWildcardAssertionArgumentAccess().getGroup(), "rule__WildcardAssertionArgument__Group__0");
			builder.put(grammarAccess.getShortLogicConstantAccess().getGroup(), "rule__ShortLogicConstant__Group__0");
			builder.put(grammarAccess.getScopeDeclarationAccess().getGroup(), "rule__ScopeDeclaration__Group__0");
			builder.put(grammarAccess.getScopeDeclarationAccess().getGroup_2(), "rule__ScopeDeclaration__Group_2__0");
			builder.put(grammarAccess.getTypeScopeAccess().getGroup(), "rule__TypeScope__Group__0");
			builder.put(grammarAccess.getRangeMultiplicityAccess().getGroup(), "rule__RangeMultiplicity__Group__0");
			builder.put(grammarAccess.getQualifiedNameAccess().getGroup(), "rule__QualifiedName__Group__0");
			builder.put(grammarAccess.getQualifiedNameAccess().getGroup_2(), "rule__QualifiedName__Group_2__0");
			builder.put(grammarAccess.getNonContainmentQualifiedNameAccess().getGroup(), "rule__NonContainmentQualifiedName__Group__0");
			builder.put(grammarAccess.getNonContainmentQualifiedNameAccess().getGroup_0_1(), "rule__NonContainmentQualifiedName__Group_0_1__0");
			builder.put(grammarAccess.getNonContainmentQualifiedNameAccess().getGroup_1(), "rule__NonContainmentQualifiedName__Group_1__0");
			builder.put(grammarAccess.getRealAccess().getGroup_1(), "rule__Real__Group_1__0");
			builder.put(grammarAccess.getProblemAccess().getKindAssignment_0_0(), "rule__Problem__KindAssignment_0_0");
			builder.put(grammarAccess.getProblemAccess().getNameAssignment_0_1(), "rule__Problem__NameAssignment_0_1");
			builder.put(grammarAccess.getProblemAccess().getStatementsAssignment_1(), "rule__Problem__StatementsAssignment_1");
			builder.put(grammarAccess.getAnnotatedStatementAccess().getAbstractAssignment_1_0_1(), "rule__AnnotatedStatement__AbstractAssignment_1_0_1");
			builder.put(grammarAccess.getAnnotatedStatementAccess().getNameAssignment_1_0_3(), "rule__AnnotatedStatement__NameAssignment_1_0_3");
			builder.put(grammarAccess.getAnnotatedStatementAccess().getSuperTypesAssignment_1_0_4_1(), "rule__AnnotatedStatement__SuperTypesAssignment_1_0_4_1");
			builder.put(grammarAccess.getAnnotatedStatementAccess().getSuperTypesAssignment_1_0_4_2_1(), "rule__AnnotatedStatement__SuperTypesAssignment_1_0_4_2_1");
			builder.put(grammarAccess.getAnnotatedStatementAccess().getFeatureDeclarationsAssignment_1_0_5_0_1_0(), "rule__AnnotatedStatement__FeatureDeclarationsAssignment_1_0_5_0_1_0");
			builder.put(grammarAccess.getAnnotatedStatementAccess().getNameAssignment_1_1_2(), "rule__AnnotatedStatement__NameAssignment_1_1_2");
			builder.put(grammarAccess.getAnnotatedStatementAccess().getLiteralsAssignment_1_1_3_0_1_0(), "rule__AnnotatedStatement__LiteralsAssignment_1_1_3_0_1_0");
			builder.put(grammarAccess.getAnnotatedStatementAccess().getLiteralsAssignment_1_1_3_0_1_1_1(), "rule__AnnotatedStatement__LiteralsAssignment_1_1_3_0_1_1_1");
			builder.put(grammarAccess.getAnnotatedStatementAccess().getNameAssignment_1_2_3(), "rule__AnnotatedStatement__NameAssignment_1_2_3");
			builder.put(grammarAccess.getAnnotatedStatementAccess().getNameAssignment_1_3_3(), "rule__AnnotatedStatement__NameAssignment_1_3_3");
			builder.put(grammarAccess.getAnnotatedStatementAccess().getShadowAssignment_1_4_3(), "rule__AnnotatedStatement__ShadowAssignment_1_4_3");
			builder.put(grammarAccess.getAnnotatedStatementAccess().getNameAssignment_1_4_4(), "rule__AnnotatedStatement__NameAssignment_1_4_4");
			builder.put(grammarAccess.getAnnotatedStatementAccess().getParametersAssignment_1_4_6_0(), "rule__AnnotatedStatement__ParametersAssignment_1_4_6_0");
			builder.put(grammarAccess.getAnnotatedStatementAccess().getParametersAssignment_1_4_6_1_1(), "rule__AnnotatedStatement__ParametersAssignment_1_4_6_1_1");
			builder.put(grammarAccess.getAnnotatedStatementAccess().getKindAssignment_1_5_1_0(), "rule__AnnotatedStatement__KindAssignment_1_5_1_0");
			builder.put(grammarAccess.getAnnotatedStatementAccess().getKindAssignment_1_5_1_1_0(), "rule__AnnotatedStatement__KindAssignment_1_5_1_1_0");
			builder.put(grammarAccess.getAnnotatedStatementAccess().getNameAssignment_1_5_2(), "rule__AnnotatedStatement__NameAssignment_1_5_2");
			builder.put(grammarAccess.getAnnotatedStatementAccess().getParametersAssignment_1_5_4_0(), "rule__AnnotatedStatement__ParametersAssignment_1_5_4_0");
			builder.put(grammarAccess.getAnnotatedStatementAccess().getParametersAssignment_1_5_4_1_1(), "rule__AnnotatedStatement__ParametersAssignment_1_5_4_1_1");
			builder.put(grammarAccess.getAnnotatedStatementAccess().getSuperSetsAssignment_1_5_6_1(), "rule__AnnotatedStatement__SuperSetsAssignment_1_5_6_1");
			builder.put(grammarAccess.getAnnotatedStatementAccess().getSuperSetsAssignment_1_5_6_2_1(), "rule__AnnotatedStatement__SuperSetsAssignment_1_5_6_2_1");
			builder.put(grammarAccess.getAnnotatedStatementAccess().getBodiesAssignment_1_5_7_1(), "rule__AnnotatedStatement__BodiesAssignment_1_5_7_1");
			builder.put(grammarAccess.getAnnotatedStatementAccess().getBodiesAssignment_1_5_7_2_1(), "rule__AnnotatedStatement__BodiesAssignment_1_5_7_2_1");
			builder.put(grammarAccess.getAnnotatedStatementAccess().getShadowAssignment_1_6_1(), "rule__AnnotatedStatement__ShadowAssignment_1_6_1");
			builder.put(grammarAccess.getAnnotatedStatementAccess().getFunctionTypeAssignment_1_6_2(), "rule__AnnotatedStatement__FunctionTypeAssignment_1_6_2");
			builder.put(grammarAccess.getAnnotatedStatementAccess().getNameAssignment_1_6_3(), "rule__AnnotatedStatement__NameAssignment_1_6_3");
			builder.put(grammarAccess.getAnnotatedStatementAccess().getParametersAssignment_1_6_5_0(), "rule__AnnotatedStatement__ParametersAssignment_1_6_5_0");
			builder.put(grammarAccess.getAnnotatedStatementAccess().getParametersAssignment_1_6_5_1_1(), "rule__AnnotatedStatement__ParametersAssignment_1_6_5_1_1");
			builder.put(grammarAccess.getAnnotatedStatementAccess().getCasesAssignment_1_6_7_1(), "rule__AnnotatedStatement__CasesAssignment_1_6_7_1");
			builder.put(grammarAccess.getAnnotatedStatementAccess().getCasesAssignment_1_6_7_2_1(), "rule__AnnotatedStatement__CasesAssignment_1_6_7_2_1");
			builder.put(grammarAccess.getAnnotatedStatementAccess().getKindAssignment_1_7_1(), "rule__AnnotatedStatement__KindAssignment_1_7_1");
			builder.put(grammarAccess.getAnnotatedStatementAccess().getNameAssignment_1_7_3(), "rule__AnnotatedStatement__NameAssignment_1_7_3");
			builder.put(grammarAccess.getAnnotatedStatementAccess().getParametersAssignment_1_7_5_0(), "rule__AnnotatedStatement__ParametersAssignment_1_7_5_0");
			builder.put(grammarAccess.getAnnotatedStatementAccess().getParametersAssignment_1_7_5_1_1(), "rule__AnnotatedStatement__ParametersAssignment_1_7_5_1_1");
			builder.put(grammarAccess.getAnnotatedStatementAccess().getPreconditionsAssignment_1_7_7_1(), "rule__AnnotatedStatement__PreconditionsAssignment_1_7_7_1");
			builder.put(grammarAccess.getAnnotatedStatementAccess().getPreconditionsAssignment_1_7_7_2_1(), "rule__AnnotatedStatement__PreconditionsAssignment_1_7_7_2_1");
			builder.put(grammarAccess.getAnnotatedStatementAccess().getConsequentsAssignment_1_7_8_1(), "rule__AnnotatedStatement__ConsequentsAssignment_1_7_8_1");
			builder.put(grammarAccess.getAnnotatedStatementAccess().getConsequentsAssignment_1_7_8_2_1(), "rule__AnnotatedStatement__ConsequentsAssignment_1_7_8_2_1");
			builder.put(grammarAccess.getAnnotatedStatementAccess().getNameAssignment_1_8_3(), "rule__AnnotatedStatement__NameAssignment_1_8_3");
			builder.put(grammarAccess.getAnnotatedStatementAccess().getParametersAssignment_1_8_5_0(), "rule__AnnotatedStatement__ParametersAssignment_1_8_5_0");
			builder.put(grammarAccess.getAnnotatedStatementAccess().getParametersAssignment_1_8_5_1_1(), "rule__AnnotatedStatement__ParametersAssignment_1_8_5_1_1");
			builder.put(grammarAccess.getAnnotatedStatementAccess().getKindAssignment_1_9_1_1_1(), "rule__AnnotatedStatement__KindAssignment_1_9_1_1_1");
			builder.put(grammarAccess.getAnnotatedStatementAccess().getNodesAssignment_1_9_2(), "rule__AnnotatedStatement__NodesAssignment_1_9_2");
			builder.put(grammarAccess.getAnnotatedStatementAccess().getNodesAssignment_1_9_3_1(), "rule__AnnotatedStatement__NodesAssignment_1_9_3_1");
			builder.put(grammarAccess.getAnnotationContainerAccess().getAnnotationsAssignment_1_1(), "rule__AnnotationContainer__AnnotationsAssignment_1_1");
			builder.put(grammarAccess.getTopLevelAnnotationAccess().getAnnotationAssignment_1(), "rule__TopLevelAnnotation__AnnotationAssignment_1");
			builder.put(grammarAccess.getAnnotationAccess().getDeclarationAssignment_1(), "rule__Annotation__DeclarationAssignment_1");
			builder.put(grammarAccess.getAnnotationAccess().getArgumentsAssignment_2_1_0(), "rule__Annotation__ArgumentsAssignment_2_1_0");
			builder.put(grammarAccess.getAnnotationAccess().getArgumentsAssignment_2_1_1_1(), "rule__Annotation__ArgumentsAssignment_2_1_1_1");
			builder.put(grammarAccess.getAnnotationArgumentAccess().getParameterAssignment_1_0(), "rule__AnnotationArgument__ParameterAssignment_1_0");
			builder.put(grammarAccess.getAnnotationArgumentAccess().getValueAssignment_2(), "rule__AnnotationArgument__ValueAssignment_2");
			builder.put(grammarAccess.getImportStatementAccess().getImportedModuleAssignment_1(), "rule__ImportStatement__ImportedModuleAssignment_1");
			builder.put(grammarAccess.getImportStatementAccess().getAliasAssignment_2_1(), "rule__ImportStatement__AliasAssignment_2_1");
			builder.put(grammarAccess.getEnumLiteralAccess().getAnnotationsAssignment_0(), "rule__EnumLiteral__AnnotationsAssignment_0");
			builder.put(grammarAccess.getEnumLiteralAccess().getNameAssignment_1(), "rule__EnumLiteral__NameAssignment_1");
			builder.put(grammarAccess.getReferenceDeclarationAccess().getAnnotationsAssignment_0(), "rule__ReferenceDeclaration__AnnotationsAssignment_0");
			builder.put(grammarAccess.getReferenceDeclarationAccess().getReferenceTypeAssignment_1_0(), "rule__ReferenceDeclaration__ReferenceTypeAssignment_1_0");
			builder.put(grammarAccess.getReferenceDeclarationAccess().getKindAssignment_1_1_0(), "rule__ReferenceDeclaration__KindAssignment_1_1_0");
			builder.put(grammarAccess.getReferenceDeclarationAccess().getReferenceTypeAssignment_1_1_1(), "rule__ReferenceDeclaration__ReferenceTypeAssignment_1_1_1");
			builder.put(grammarAccess.getReferenceDeclarationAccess().getMultiplicityAssignment_2(), "rule__ReferenceDeclaration__MultiplicityAssignment_2");
			builder.put(grammarAccess.getReferenceDeclarationAccess().getNameAssignment_3(), "rule__ReferenceDeclaration__NameAssignment_3");
			builder.put(grammarAccess.getReferenceDeclarationAccess().getOppositeAssignment_4_0_1(), "rule__ReferenceDeclaration__OppositeAssignment_4_0_1");
			builder.put(grammarAccess.getReferenceDeclarationAccess().getSuperSetsAssignment_4_1_1(), "rule__ReferenceDeclaration__SuperSetsAssignment_4_1_1");
			builder.put(grammarAccess.getReferenceDeclarationAccess().getSuperSetsAssignment_4_1_2_1(), "rule__ReferenceDeclaration__SuperSetsAssignment_4_1_2_1");
			builder.put(grammarAccess.getConjunctionAccess().getLiteralsAssignment_0(), "rule__Conjunction__LiteralsAssignment_0");
			builder.put(grammarAccess.getConjunctionAccess().getLiteralsAssignment_1_1(), "rule__Conjunction__LiteralsAssignment_1_1");
			builder.put(grammarAccess.getCaseAccess().getConditionAssignment_0(), "rule__Case__ConditionAssignment_0");
			builder.put(grammarAccess.getCaseAccess().getValueAssignment_1_1(), "rule__Case__ValueAssignment_1_1");
			builder.put(grammarAccess.getParameterAccess().getAnnotationsAssignment_0(), "rule__Parameter__AnnotationsAssignment_0");
			builder.put(grammarAccess.getParameterAccess().getKindAssignment_1_0(), "rule__Parameter__KindAssignment_1_0");
			builder.put(grammarAccess.getParameterAccess().getParameterTypeAssignment_1_1(), "rule__Parameter__ParameterTypeAssignment_1_1");
			builder.put(grammarAccess.getParameterAccess().getNameAssignment_2(), "rule__Parameter__NameAssignment_2");
			builder.put(grammarAccess.getConsequentAccess().getActionsAssignment_0(), "rule__Consequent__ActionsAssignment_0");
			builder.put(grammarAccess.getConsequentAccess().getActionsAssignment_1_1(), "rule__Consequent__ActionsAssignment_1_1");
			builder.put(grammarAccess.getAssertionActionAccess().getRelationAssignment_0_0(), "rule__AssertionAction__RelationAssignment_0_0");
			builder.put(grammarAccess.getAssertionActionAccess().getArgumentsAssignment_0_2_0(), "rule__AssertionAction__ArgumentsAssignment_0_2_0");
			builder.put(grammarAccess.getAssertionActionAccess().getArgumentsAssignment_0_2_1_1(), "rule__AssertionAction__ArgumentsAssignment_0_2_1_1");
			builder.put(grammarAccess.getAssertionActionAccess().getValueAssignment_0_5(), "rule__AssertionAction__ValueAssignment_0_5");
			builder.put(grammarAccess.getAssertionActionAccess().getValueAssignment_1_0(), "rule__AssertionAction__ValueAssignment_1_0");
			builder.put(grammarAccess.getAssertionActionAccess().getRelationAssignment_1_1(), "rule__AssertionAction__RelationAssignment_1_1");
			builder.put(grammarAccess.getAssertionActionAccess().getArgumentsAssignment_1_3_0(), "rule__AssertionAction__ArgumentsAssignment_1_3_0");
			builder.put(grammarAccess.getAssertionActionAccess().getArgumentsAssignment_1_3_1_1(), "rule__AssertionAction__ArgumentsAssignment_1_3_1_1");
			builder.put(grammarAccess.getTheoryActionAccess().getTermAssignment_1(), "rule__TheoryAction__TermAssignment_1");
			builder.put(grammarAccess.getAssignmentExprAccess().getRightAssignment_1_2(), "rule__AssignmentExpr__RightAssignment_1_2");
			builder.put(grammarAccess.getBooleanExprAccess().getOpAssignment_1_1(), "rule__BooleanExpr__OpAssignment_1_1");
			builder.put(grammarAccess.getBooleanExprAccess().getRightAssignment_1_2(), "rule__BooleanExpr__RightAssignment_1_2");
			builder.put(grammarAccess.getComparisonExprAccess().getOpAssignment_1_0_1(), "rule__ComparisonExpr__OpAssignment_1_0_1");
			builder.put(grammarAccess.getComparisonExprAccess().getRightAssignment_1_0_2(), "rule__ComparisonExpr__RightAssignment_1_0_2");
			builder.put(grammarAccess.getComparisonExprAccess().getOpAssignment_1_1_1(), "rule__ComparisonExpr__OpAssignment_1_1_1");
			builder.put(grammarAccess.getComparisonExprAccess().getRightAssignment_1_1_2(), "rule__ComparisonExpr__RightAssignment_1_1_2");
			builder.put(grammarAccess.getLatticeExprAccess().getOpAssignment_1_1(), "rule__LatticeExpr__OpAssignment_1_1");
			builder.put(grammarAccess.getLatticeExprAccess().getRightAssignment_1_2(), "rule__LatticeExpr__RightAssignment_1_2");
			builder.put(grammarAccess.getAdditiveExprAccess().getOpAssignment_1_1(), "rule__AdditiveExpr__OpAssignment_1_1");
			builder.put(grammarAccess.getAdditiveExprAccess().getRightAssignment_1_2(), "rule__AdditiveExpr__RightAssignment_1_2");
			builder.put(grammarAccess.getMultiplicativeExprAccess().getOpAssignment_1_1(), "rule__MultiplicativeExpr__OpAssignment_1_1");
			builder.put(grammarAccess.getMultiplicativeExprAccess().getRightAssignment_1_2(), "rule__MultiplicativeExpr__RightAssignment_1_2");
			builder.put(grammarAccess.getExponentialExprAccess().getOpAssignment_1_1(), "rule__ExponentialExpr__OpAssignment_1_1");
			builder.put(grammarAccess.getExponentialExprAccess().getRightAssignment_1_2(), "rule__ExponentialExpr__RightAssignment_1_2");
			builder.put(grammarAccess.getRangeExprAccess().getRightAssignment_1_2(), "rule__RangeExpr__RightAssignment_1_2");
			builder.put(grammarAccess.getArithmeticUnaryExprAccess().getOpAssignment_0(), "rule__ArithmeticUnaryExpr__OpAssignment_0");
			builder.put(grammarAccess.getArithmeticUnaryExprAccess().getBodyAssignment_1(), "rule__ArithmeticUnaryExpr__BodyAssignment_1");
			builder.put(grammarAccess.getNegationExprAccess().getBodyAssignment_1(), "rule__NegationExpr__BodyAssignment_1");
			builder.put(grammarAccess.getAggregationExprAccess().getAggregatorAssignment_0(), "rule__AggregationExpr__AggregatorAssignment_0");
			builder.put(grammarAccess.getAggregationExprAccess().getConditionAssignment_2(), "rule__AggregationExpr__ConditionAssignment_2");
			builder.put(grammarAccess.getAggregationExprAccess().getValueAssignment_3_1(), "rule__AggregationExpr__ValueAssignment_3_1");
			builder.put(grammarAccess.getModalExprAccess().getConcretenessAssignment_0_0_0(), "rule__ModalExpr__ConcretenessAssignment_0_0_0");
			builder.put(grammarAccess.getModalExprAccess().getModalityAssignment_0_0_1(), "rule__ModalExpr__ModalityAssignment_0_0_1");
			builder.put(grammarAccess.getModalExprAccess().getModalityAssignment_0_1_0(), "rule__ModalExpr__ModalityAssignment_0_1_0");
			builder.put(grammarAccess.getModalExprAccess().getConcretenessAssignment_0_1_1(), "rule__ModalExpr__ConcretenessAssignment_0_1_1");
			builder.put(grammarAccess.getModalExprAccess().getBodyAssignment_1(), "rule__ModalExpr__BodyAssignment_1");
			builder.put(grammarAccess.getAtomAccess().getRelationAssignment_0(), "rule__Atom__RelationAssignment_0");
			builder.put(grammarAccess.getAtomAccess().getTransitiveClosureAssignment_1(), "rule__Atom__TransitiveClosureAssignment_1");
			builder.put(grammarAccess.getAtomAccess().getArgumentsAssignment_3_0(), "rule__Atom__ArgumentsAssignment_3_0");
			builder.put(grammarAccess.getAtomAccess().getArgumentsAssignment_3_1_1(), "rule__Atom__ArgumentsAssignment_3_1_1");
			builder.put(grammarAccess.getVariableOrNodeExprAccess().getElementAssignment(), "rule__VariableOrNodeExpr__ElementAssignment");
			builder.put(grammarAccess.getIntConstantAccess().getIntValueAssignment(), "rule__IntConstant__IntValueAssignment");
			builder.put(grammarAccess.getRealConstantAccess().getRealValueAssignment(), "rule__RealConstant__RealValueAssignment");
			builder.put(grammarAccess.getStringConstantAccess().getStringValueAssignment(), "rule__StringConstant__StringValueAssignment");
			builder.put(grammarAccess.getLogicConstantAccess().getLogicValueAssignment(), "rule__LogicConstant__LogicValueAssignment");
			builder.put(grammarAccess.getAssertionAccess().getDefaultAssignment_0(), "rule__Assertion__DefaultAssignment_0");
			builder.put(grammarAccess.getAssertionAccess().getRelationAssignment_1_0_0(), "rule__Assertion__RelationAssignment_1_0_0");
			builder.put(grammarAccess.getAssertionAccess().getArgumentsAssignment_1_0_2_0(), "rule__Assertion__ArgumentsAssignment_1_0_2_0");
			builder.put(grammarAccess.getAssertionAccess().getArgumentsAssignment_1_0_2_1_1(), "rule__Assertion__ArgumentsAssignment_1_0_2_1_1");
			builder.put(grammarAccess.getAssertionAccess().getValueAssignment_1_0_5(), "rule__Assertion__ValueAssignment_1_0_5");
			builder.put(grammarAccess.getAssertionAccess().getValueAssignment_1_1_0(), "rule__Assertion__ValueAssignment_1_1_0");
			builder.put(grammarAccess.getAssertionAccess().getRelationAssignment_1_1_1(), "rule__Assertion__RelationAssignment_1_1_1");
			builder.put(grammarAccess.getAssertionAccess().getArgumentsAssignment_1_1_3_0(), "rule__Assertion__ArgumentsAssignment_1_1_3_0");
			builder.put(grammarAccess.getAssertionAccess().getArgumentsAssignment_1_1_3_1_1(), "rule__Assertion__ArgumentsAssignment_1_1_3_1_1");
			builder.put(grammarAccess.getNodeAssertionArgumentAccess().getNodeAssignment(), "rule__NodeAssertionArgument__NodeAssignment");
			builder.put(grammarAccess.getShortLogicConstantAccess().getLogicValueAssignment_1(), "rule__ShortLogicConstant__LogicValueAssignment_1");
			builder.put(grammarAccess.getScopeDeclarationAccess().getTypeScopesAssignment_1(), "rule__ScopeDeclaration__TypeScopesAssignment_1");
			builder.put(grammarAccess.getScopeDeclarationAccess().getTypeScopesAssignment_2_1(), "rule__ScopeDeclaration__TypeScopesAssignment_2_1");
			builder.put(grammarAccess.getTypeScopeAccess().getTargetTypeAssignment_0(), "rule__TypeScope__TargetTypeAssignment_0");
			builder.put(grammarAccess.getTypeScopeAccess().getIncrementAssignment_1_0(), "rule__TypeScope__IncrementAssignment_1_0");
			builder.put(grammarAccess.getTypeScopeAccess().getMultiplicityAssignment_2(), "rule__TypeScope__MultiplicityAssignment_2");
			builder.put(grammarAccess.getRangeMultiplicityAccess().getLowerBoundAssignment_0(), "rule__RangeMultiplicity__LowerBoundAssignment_0");
			builder.put(grammarAccess.getRangeMultiplicityAccess().getUpperBoundAssignment_2(), "rule__RangeMultiplicity__UpperBoundAssignment_2");
			builder.put(grammarAccess.getExactMultiplicityAccess().getExactValueAssignment(), "rule__ExactMultiplicity__ExactValueAssignment");
			builder.put(grammarAccess.getReferenceDeclarationAccess().getUnorderedGroup_4(), "rule__ReferenceDeclaration__UnorderedGroup_4");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private ProblemGrammarAccess grammarAccess;

	@Override
	protected InternalProblemParser createParser() {
		InternalProblemParser result = new InternalProblemParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected TokenSource createLexer(CharStream stream) {
		return new ProblemTokenSource(super.createLexer(stream));
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public ProblemGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ProblemGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
