/*
 *  Copyright 2026 Budapest University of Technology and Economics
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package hu.bme.mit.theta.frontend

import hu.bme.mit.theta.common.Tuple2
import hu.bme.mit.theta.frontend.transformation.ArchitectureConfig.ArchitectureType
import hu.bme.mit.theta.frontend.transformation.model.types.complex.CComplexType
import hu.bme.mit.theta.frontend.transformation.model.types.complex.compound.CStruct
import hu.bme.mit.theta.frontend.transformation.model.types.complex.compound.ObjectLayout
import hu.bme.mit.theta.frontend.transformation.model.types.complex.integer.cchar.CUnsignedChar
import hu.bme.mit.theta.frontend.transformation.model.types.complex.integer.cshort.CSignedShort
import hu.bme.mit.theta.frontend.transformation.model.types.complex.real.CDouble
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Test

/**
 * The byte-exact object layout AD7 is built on (PLAN.md Phase 6 / AD7 step 1). Pure and unwired,
 * like [BitfieldLayoutTest] before it.
 *
 * Every expectation here is **generated by gcc**, not reasoned out: the fixture struct was compiled
 * with `gcc -m32` and `gcc -m64` and its `sizeof`/`_Alignof`/`offsetof` printed. Sizes are in bytes
 * in the comments (as gcc reports them) and bits in the assertions (as the layout computes them).
 * Deriving these by hand is exactly how an ABI quirk gets baked in as a "rule".
 */
class ObjectLayoutTest {

  private fun ctx(arch: ArchitectureType) = ParseContext().apply { setArchitecture(arch) }

  private fun struct(
    parseContext: ParseContext,
    fields: List<Pair<String, CComplexType>>,
    bitfieldWidths: List<Int> = fields.map { -1 },
    union: Boolean = false,
  ) =
    CStruct(
      null,
      fields.map { Tuple2.of(it.first, it.second) },
      union,
      parseContext,
      bitfieldWidths,
    )

  private fun int(c: ParseContext) = CComplexType.getSignedInt(c)

  private fun uint(c: ParseContext) = CComplexType.getUnsignedInt(c)

  private fun longlong(c: ParseContext) = CComplexType.getSignedLongLong(c)

  private fun uchar(c: ParseContext) = CUnsignedChar(null, c)

  private fun short(c: ParseContext) = CSignedShort(null, c)

  private fun double(c: ParseContext) = CDouble(null, c)

  @Test
  fun charThenIntPadsToTheIntsAlignment() {
    // gcc both models: struct S1 { char a; int b; } size=8 align=4 a=0 b=4
    for (arch in listOf(ArchitectureType.ILP32, ArchitectureType.LP64)) {
      val c = ctx(arch)
      val layout =
        ObjectLayout.of(struct(c, listOf("a" to uchar(c), "b" to int(c))), arch)
      assertEquals(64, layout.bitSize, "size, $arch")
      assertEquals(32, layout.bitAlignment, "alignment, $arch")
      assertEquals(0, layout.field("a")!!.bitOffset, "a offset, $arch")
      assertEquals(32, layout.field("b")!!.bitOffset, "b offset, $arch")
    }
  }

  @Test
  fun intThenCharGetsTailPadding() {
    // gcc both models: struct S2 { int a; char b; } size=8 align=4
    // Without tail padding an array of these would misalign every second element.
    for (arch in listOf(ArchitectureType.ILP32, ArchitectureType.LP64)) {
      val c = ctx(arch)
      val layout = ObjectLayout.of(struct(c, listOf("a" to int(c), "b" to uchar(c))), arch)
      assertEquals(64, layout.bitSize, "size, $arch")
      assertEquals(40, layout.field("b")!!.bitOffset + 8, "b ends at bit 40, $arch")
    }
  }

  @Test
  fun longLongAlignsToFourBytesOnIlp32ButEightOnLp64() {
    // The i386 ABI quirk, and the single best reason to generate these numbers rather than assume
    // "alignment == size": gcc -m32 gives struct S3 { char a; long long b; } size=12 align=4 b=4,
    // gcc -m64 gives size=16 align=8 b=8.
    val c32 = ctx(ArchitectureType.ILP32)
    val l32 =
      ObjectLayout.of(
        struct(c32, listOf("a" to uchar(c32), "b" to longlong(c32))),
        ArchitectureType.ILP32,
      )
    assertEquals(96, l32.bitSize, "ILP32 size = 12 bytes")
    assertEquals(32, l32.bitAlignment, "ILP32 alignment = 4 bytes")
    assertEquals(32, l32.field("b")!!.bitOffset, "ILP32 b at byte 4")

    val c64 = ctx(ArchitectureType.LP64)
    val l64 =
      ObjectLayout.of(
        struct(c64, listOf("a" to uchar(c64), "b" to longlong(c64))),
        ArchitectureType.LP64,
      )
    assertEquals(128, l64.bitSize, "LP64 size = 16 bytes")
    assertEquals(64, l64.bitAlignment, "LP64 alignment = 8 bytes")
    assertEquals(64, l64.field("b")!!.bitOffset, "LP64 b at byte 8")
  }

  @Test
  fun doubleFollowsTheSameSplitAsLongLong() {
    // gcc: struct S4 { char a; double d; } -m32 size=12 align=4 d=4; -m64 size=16 align=8 d=8
    val c32 = ctx(ArchitectureType.ILP32)
    val l32 =
      ObjectLayout.of(
        struct(c32, listOf("a" to uchar(c32), "d" to double(c32))),
        ArchitectureType.ILP32,
      )
    assertEquals(96, l32.bitSize)
    assertEquals(32, l32.field("d")!!.bitOffset)

    val c64 = ctx(ArchitectureType.LP64)
    val l64 =
      ObjectLayout.of(
        struct(c64, listOf("a" to uchar(c64), "d" to double(c64))),
        ArchitectureType.LP64,
      )
    assertEquals(128, l64.bitSize)
    assertEquals(64, l64.field("d")!!.bitOffset)
  }

  @Test
  fun shortSitsInThePaddingAfterAChar() {
    // gcc both: struct S5 { char a; short b; int c; } size=8 align=4 a=0 b=2 c=4
    for (arch in listOf(ArchitectureType.ILP32, ArchitectureType.LP64)) {
      val c = ctx(arch)
      val layout =
        ObjectLayout.of(
          struct(c, listOf("a" to uchar(c), "b" to short(c), "c" to int(c))),
          arch,
        )
      assertEquals(64, layout.bitSize, "size, $arch")
      assertEquals(16, layout.field("b")!!.bitOffset, "b at byte 2, $arch")
      assertEquals(32, layout.field("c")!!.bitOffset, "c at byte 4, $arch")
    }
  }

  @Test
  fun twoNibbleBitfieldsShareOneWord() {
    // gcc both: struct S6 { unsigned a:4; unsigned b:4; } size=4 align=4
    for (arch in listOf(ArchitectureType.ILP32, ArchitectureType.LP64)) {
      val c = ctx(arch)
      val layout =
        ObjectLayout.of(
          struct(c, listOf("a" to uint(c), "b" to uint(c)), bitfieldWidths = listOf(4, 4)),
          arch,
        )
      assertEquals(32, layout.bitSize, "size = 4 bytes, $arch")
      assertEquals(0, layout.field("a")!!.bitOffset, "$arch")
      assertEquals(4, layout.field("b")!!.bitOffset, "b starts at bit 4, $arch")
    }
  }

  @Test
  fun aBitfieldThatWouldStraddleAWordStartsANewOne() {
    // gcc both: struct S9 { unsigned a:30; unsigned b:4; } size=8 align=4
    // b cannot span the 32-bit boundary, so it opens the next storage unit.
    for (arch in listOf(ArchitectureType.ILP32, ArchitectureType.LP64)) {
      val c = ctx(arch)
      val layout =
        ObjectLayout.of(
          struct(c, listOf("a" to uint(c), "b" to uint(c)), bitfieldWidths = listOf(30, 4)),
          arch,
        )
      assertEquals(64, layout.bitSize, "size = 8 bytes, $arch")
      assertEquals(32, layout.field("b")!!.bitOffset, "b restarts at bit 32, $arch")
    }
  }

  @Test
  fun charSizedBitfieldsPackIntoTheFollowingByte() {
    // gcc both: struct S8 { unsigned char a; unsigned char b:2, c:2, d:4; } size=2 align=1
    // This is the ldv-memsafety-bitfields shape, so its layout is worth pinning exactly.
    for (arch in listOf(ArchitectureType.ILP32, ArchitectureType.LP64)) {
      val c = ctx(arch)
      val layout =
        ObjectLayout.of(
          struct(
            c,
            listOf("a" to uchar(c), "b" to uchar(c), "c" to uchar(c), "d" to uchar(c)),
            bitfieldWidths = listOf(-1, 2, 2, 4),
          ),
          arch,
        )
      assertEquals(16, layout.bitSize, "size = 2 bytes, $arch")
      assertEquals(8, layout.bitAlignment, "alignment = 1 byte, $arch")
      assertEquals(8, layout.field("b")!!.bitOffset, "b at bit 8, $arch")
      assertEquals(10, layout.field("c")!!.bitOffset, "c at bit 10, $arch")
      assertEquals(12, layout.field("d")!!.bitOffset, "d at bit 12, $arch")
    }
  }

  @Test
  fun aNestedStructKeepsItsOwnAlignment() {
    // gcc both: struct S10 { char a; struct S1 inner; char z; } size=16 align=4 a=0 inner=4 z=12
    for (arch in listOf(ArchitectureType.ILP32, ArchitectureType.LP64)) {
      val c = ctx(arch)
      val inner = struct(c, listOf("a" to uchar(c), "b" to int(c)))
      val layout =
        ObjectLayout.of(
          struct(c, listOf("a" to uchar(c), "inner" to inner, "z" to uchar(c))),
          arch,
        )
      assertEquals(128, layout.bitSize, "size = 16 bytes, $arch")
      assertEquals(32, layout.field("inner")!!.bitOffset, "inner at byte 4, $arch")
      assertEquals(96, layout.field("z")!!.bitOffset, "z at byte 12, $arch")
    }
  }

  @Test
  fun unionMembersAllStartAtZeroAndTakeTheWidest() {
    // gcc: union U2 { char a; double d; } -m32 size=8 align=4; -m64 size=8 align=8
    for (arch in listOf(ArchitectureType.ILP32, ArchitectureType.LP64)) {
      val c = ctx(arch)
      val layout =
        ObjectLayout.of(
          struct(c, listOf("a" to uchar(c), "d" to double(c)), union = true),
          arch,
        )
      assertEquals(64, layout.bitSize, "size = 8 bytes, $arch")
      assertEquals(0, layout.field("a")!!.bitOffset, "$arch")
      assertEquals(0, layout.field("d")!!.bitOffset, "both members start at bit 0, $arch")
    }
    assertEquals(
      32,
      ObjectLayout.of(
          ctx(ArchitectureType.ILP32).let {
            struct(it, listOf("a" to uchar(it), "d" to double(it)), union = true)
          },
          ArchitectureType.ILP32,
        )
        .bitAlignment,
      "ILP32 aligns a double to 4 bytes",
    )
  }

  @Test
  fun aPointerMemberFollowsTheDataModel() {
    // gcc: struct S12 { char a; void *p; } -m32 size=8 align=4 p=4; -m64 size=16 align=8 p=8
    val c32 = ctx(ArchitectureType.ILP32)
    val l32 =
      ObjectLayout.of(
        struct(c32, listOf("a" to uchar(c32), "p" to CComplexType.getUnsignedLong(c32))),
        ArchitectureType.ILP32,
      )
    assertEquals(64, l32.bitSize, "ILP32 size = 8 bytes")
    assertEquals(32, l32.field("p")!!.bitOffset, "ILP32 pointer at byte 4")

    val c64 = ctx(ArchitectureType.LP64)
    val l64 =
      ObjectLayout.of(
        struct(c64, listOf("a" to uchar(c64), "p" to CComplexType.getUnsignedLong(c64))),
        ArchitectureType.LP64,
      )
    assertEquals(128, l64.bitSize, "LP64 size = 16 bytes")
    assertEquals(64, l64.field("p")!!.bitOffset, "LP64 pointer at byte 8")
  }
}
