name: 'Create specification-transformation binary'
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
    - name: Print file path
      shell: bash
      run: |
        echo ${{ format('{0}/{1}', github.action_path, 'specification-transformation.zip') }}
        ls -l ${{ format('{0}/{1}', github.action_path, 'specification-transformation.zip') }} && echo "file_exists=true" >> "$GITHUB_ENV" || echo "file_exists=false" >> "$GITHUB_ENV"
    - name: Setup java 17
      if: env.file_exists == 'false'
      uses: actions/setup-java@5ffc13f4174014e2d4d4572b3d74c3fa61aeb2c2 # v3.11.0
      with:
        distribution: temurin
        java-version: 17
    - name: Checkout specification-transformation
      if: env.file_exists == 'false'
      shell: bash
      run: |
        git clone https://gitlab.com/sosy-lab/software/transver.git specification-transformation
        cd specification-transformation
        git checkout cb403db10ca9eb9c0ef6d38afc16eb63799410dc # Fri Oct 10 18:53:56 2025 
    - name: Build cpachecker
      if: env.file_exists == 'false'
      shell: bash
      run: |
        cd specification-transformation/
        make setup
        cd lib/cpachecker
        rm lib/java/runtime/libLLVM-9.so lib/java/runtime/lib{z3,cvc}*
    - name: zip file
      if: env.file_exists == 'false'
      shell: bash
      run: |
        zip specification-transformation.zip specification-transformation -r
    - name: Move if exists
      if: env.file_exists == 'true'
      shell: bash
      run: |
        mkdir specification-transformation
        mv $GITHUB_ACTION_PATH/specification-transformation.zip ./
    - name: Upload results
      uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v3.1.2
      with:
        name: specification-transformation
        path: specification-transformation.zip
