name: 'Create specification-transformation binary'
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
    - name: Print file path
      shell: bash
      run: |
        echo ${{ format('{0}/{1}', github.action_path, 'specification-transformation.zip') }}
        ls -l ${{ format('{0}/{1}', github.action_path, 'specification-transformation.zip') }} && echo "file_exists=true" >> "$GITHUB_ENV" || echo "file_exists=false" >> "$GITHUB_ENV"
    - name: Setup java 17
      if: env.file_exists == 'false'
      uses: actions/setup-java@5ffc13f4174014e2d4d4572b3d74c3fa61aeb2c2 # v3.11.0
      with:
        distribution: temurin
        java-version: 17
    - name: Checkout specification-transformation
      if: env.file_exists == 'false'
      shell: bash
      run: |
        git clone https://gitlab.com/sosy-lab/software/specification-transformation.git specification-transformation
        cd specification-transformation
        git checkout d966deb4ea0e34c1bc658d7c979a032340c93b13 # Fri Nov 8 10:43:02 2024 
        git apply $GITHUB_ACTION_PATH/patch.diff
    - name: Build cpachecker
      if: env.file_exists == 'false'
      shell: bash
      run: |
        cd specification-transformation/lib
        git clone https://github.com/sosy-lab/cpachecker.git cpachecker
        cd cpachecker
        git checkout c087875f139c14692b08a33f7d2cc77006c80ddc
        ant jar
        cd ../../
        mkdir cpachecker/runtime -p
        mv lib/cpachecker/lib/java/runtime/*.jar cpachecker/runtime/
        mv lib/cpachecker/config cpachecker/
        mv lib/cpachecker/cpachecker.jar cpachecker/
    - name: zip file
      if: env.file_exists == 'false'
      shell: bash
      run: |
        zip specification-transformation.zip specification-transformation/cpachecker specification-transformation/src -r
    - name: Move if exists
      if: env.file_exists == 'true'
      shell: bash
      run: |
        mkdir specification-transformation
        mv $GITHUB_ACTION_PATH/specification-transformation.zip ./
    - name: Upload results
      uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v3.1.2
      with:
        name: specification-transformation
        path: specification-transformation.zip
