name: 'Install LLVM'
inputs:
    version:
        required: true

runs:
  using: "composite"
  steps:
    - name: Create folder
      shell: bash
      run: |
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh ${{ inputs.version }}