name: 'Create SV-COMP binary'
inputs:
    name:
        required: true
    inputflag:
        required: true
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
    - name: Determine version
      id: version
      shell: bash
      run: |
        echo version=$(./gradlew properties --no-daemon --console=plain -q | grep "^version:" | awk '{printf $2}') >> $GITHUB_OUTPUT
    - uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v3.0.2
      name: Get JAR
      with:
        name: ThetaJars
        path: jar/
    - name: Create folder structure
      shell: bash
      run: |
        mkdir -p ${{ inputs.name }}/${{ inputs.name }}/
        mkdir -p ${{ inputs.name }}/${{ inputs.name }}/solvers
        cp lib ${{ inputs.name }}/${{ inputs.name }}/lib -r
        cp CONTRIBUTORS.md ${{ inputs.name }}/${{ inputs.name }}/
        cp lib/README.md ${{ inputs.name }}/${{ inputs.name }}/LIB_LICENSES.md
        cp LICENSE ${{ inputs.name }}/${{ inputs.name }}/
        cp README.md ${{ inputs.name }}/${{ inputs.name }}/GENERAL_README.md
        cp scripts/theta-start.sh ${{ inputs.name }}/${{ inputs.name }}/theta-start.sh
        sed -i 's/TOOL_NAME/${{ inputs.name }}/g' ${{ inputs.name }}/${{ inputs.name }}/theta-start.sh
        sed -i 's/TOOL_VERSION/${{ steps.version.outputs.version }}/g' ${{ inputs.name }}/${{ inputs.name }}/theta-start.sh
        chmod +x ${{ inputs.name }}/${{ inputs.name }}/theta-start.sh
        sed "s/COMMIT_ID/$GITHUB_SHA/g" $GITHUB_ACTION_PATH/README.md > ${{ inputs.name }}/${{ inputs.name }}/README.md 
        sed -i 's/TOOL_NAME/${{ inputs.name }}/g' ${{ inputs.name }}/${{ inputs.name }}/README.md
        sed -i 's/INPUT_FLAG/${{ inputs.inputflag }}/g' ${{ inputs.name }}/${{ inputs.name }}/README.md
    - name: Extract theta-xcfa-cli and theta-smtlib-cli
      shell: bash
      run: |
        mv jar/xcfa/xcfa-cli/build/libs/*-all.jar ${{ inputs.name }}/${{ inputs.name }}/theta.jar
        mv jar/solver/solver-smtlib-cli/build/libs/*-all.jar ${{ inputs.name }}/${{ inputs.name }}/theta-smtlib.jar
    - name: Setup java 17
      uses: actions/setup-java@5ffc13f4174014e2d4d4572b3d74c3fa61aeb2c2 # v3.11.0
      with:
        distribution: temurin
        java-version: 17
    - name: Install solvers
      shell: bash
      run: |
        for i in $(cat $GITHUB_ACTION_PATH/necessary-solvers.txt)
        do
          java -jar ${{ inputs.name }}/${{ inputs.name }}/theta-smtlib.jar --home ${{ inputs.name }}/${{ inputs.name }}/solvers install $i
        done
    - name: Download specification-transformation binary
      uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v3.0.2
      with:
        name: specification-transformation
        path: ./
    - name: Move file to overwrite specification-transformation.bin
      shell: bash
      run: |
        mv specification-transformation.bin $GITHUB_ACTION_PATH/specification-transformation.bin
    - name: Copy specification transformation binary and license
      shell: bash
      run: |
        cp $GITHUB_ACTION_PATH/specification-transformation.bin ${{ inputs.name }}/${{ inputs.name }}/
        chmod +x ${{ inputs.name }}/${{ inputs.name }}/specification-transformation.bin
        cp $GITHUB_ACTION_PATH/specification-transformation.bin.LICENSE ${{ inputs.name }}/${{ inputs.name }}/
        cp $GITHUB_ACTION_PATH/offset.sh ${{ inputs.name }}/${{ inputs.name }}/
    - name: ZIP archive
      shell: bash
      run: |
        cd ${{ inputs.name }}
        zip ${{ inputs.name }}.zip ${{ inputs.name }} -r
    - name: Upload results
      uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v3.1.2
      with:
        name: ${{ inputs.name }}_SV-COMP
        path: ${{ inputs.name }}/${{ inputs.name }}.zip
