name: CI-build

on:
  workflow_dispatch:
  workflow_call:

jobs:
  # Builds Theta
  build:
    strategy:
      fail-fast: false
      matrix:
        java: [ 17 ]
    runs-on: ubuntu-latest
    name: Build with JDK ${{ matrix.java }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up Java ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build -x test --no-daemon