name: CI-build

on:
  workflow_dispatch:
    inputs:
      java-version:
        type: string
        description: "The java version to use"
        required: false
      java-distribution:
        type: string
        description: "The Java distribution to use"
        required: false

jobs:
  # Builds Theta
  build:
    runs-on: ubuntu-latest
    name: Build Theta
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Build Theta
        uses: ./.github/actions/build-linux
        with:
          java-version: ${{ github.event.inputs.java-version }}
          java-distribution: ${{ github.event.inputs.java-distribution }}