name: release

on:
  workflow_dispatch:
    inputs:
      mode:
        description: 'The type of version bump'
        required: true
        type: choice
        options:
          - major
          - minor
          - patch
          - 'custom_override'
        default: patch
      custom_override:
        description: The custom version to override the current version with
        required: false
        type: string
      deploy_docs:
        description: Whether to deploy the documentation as well
        required: true
        type: boolean
        default: true

jobs: