name: Build sts-cli dockerfile

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  sts-cli-docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build sts Docker image
      run: docker build -t theta-sts-cli -f docker/theta-sts-cli.Dockerfile .
