name: Build xta-cli dockerfile

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  xta-cli-docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build XTA Docker image
      run: docker build -t theta-xta-cli -f docker/theta-xta-cli.Dockerfile .
    - name: Run docker on example
      run: ./docker/run-theta-xta-cli.sh subprojects/xta/src/test/resources/csma-2.xta -c LU -s BFS
